// app/corpora/lc/index.js
// LC = Law Commission of India.
// ~290 reports across 22 Commission terms (1st = 1955-58, 22nd = 2020-24).
// Daily-mirrored from lawcommissionofindia.nic.in via parliamentwatch-data's
// build_lc.py + lc.yml.
//
// Fourth registered corpus under SansadSaar. Structurally mirrors the CAG
// module (data fetch, list/detail rendering, deep-search bundle+index) with
// LC-specifics: flat reportKeys (`lc|<report_number>`), filters by
// commission term / year, no gov_type or sector groupings, simpler detail
// panel (no department/state/report_no).
//
// Independence Principle: this file does not import from cag/index.js or
// drsc/index.js. Some helper code is duplicated (parseQuery via the shared
// corpus-search module, but list rendering etc are corpus-local) — the
// duplication is intentional per spec v0.4 §"Independence Principle".

import {
  idbGet, idbPut, idbCursor,
  escapeHtml, debounce,
  loadSettings, saveSettings,
  formatLocalTimestamp,
} from '../../deps.js';
import { streamWithPersistence } from '../../ai-streaming.js';
import {
  parseQuery, highlightMatches,
  loadSearchBundle as sharedLoadSearchBundle,
  loadSearchIndex  as sharedLoadSearchIndex,
  expandTokenToDocs,
} from '../../corpus-search.js';
import { hydrateFromIDB } from '../../corpus-data.js';
import { loadTextFromShards } from '../../text-shards.js';

const CORPUS_PREFIX = 'lc/';

// PDF archive companion repo. Auto-populated by the parliamentwatch-data
// daily Action: every freshly-downloaded LC PDF gets a byte-identical
// copy committed here. The detail panel surfaces an "Archive copy" link
// for any report we can confirm is in the archive (we don't want broken
// links). See parliamentwatch-data/lc/scraper.py archive_pdf() +
// .github/workflows/lc.yml for the upstream side.
//
// URL shape:
//   https://raw.githubusercontent.com/NakliTechie/sansadsaar-lc/main/pdfs/<n>.pdf
//   https://raw.githubusercontent.com/NakliTechie/sansadsaar-lc/main/index.json
//
// `raw.githubusercontent.com` serves with `access-control-allow-origin: *`
// so we can fetch index.json client-side without a proxy.
const ARCHIVE_REPO_URL  = 'https://github.com/NakliTechie/sansadsaar-lc';
const ARCHIVE_RAW_BASE  = 'https://raw.githubusercontent.com/NakliTechie/sansadsaar-lc/main';
const ARCHIVE_INDEX_URL = `${ARCHIVE_RAW_BASE}/index.json`;
const ARCHIVE_PDF_URL   = (n) => `${ARCHIVE_RAW_BASE}/pdfs/${n}.pdf`;

// ── Constants ───────────────────────────────────────────────────────────────

// Commission term → short ordinal label. Used in list-row pills and the
// detail panel. The Commission term is the primary structural axis of the
// LC corpus (the only "grouping" dimension upstream supplies).
const COMMISSION_ORDINAL = {
  1:'1st',   2:'2nd',   3:'3rd',   4:'4th',   5:'5th',
  6:'6th',   7:'7th',   8:'8th',   9:'9th',  10:'10th',
  11:'11th', 12:'12th', 13:'13th', 14:'14th', 15:'15th',
  16:'16th', 17:'17th', 18:'18th', 19:'19th', 20:'20th',
  21:'21st', 22:'22nd',
};

// Pill colour rotation by Commission term. Cycles through the four
// cat-badge palette buckets already defined in index.html so the pill
// ribbon reads as a visual grouping at a glance. Buckets:
//   DFG    — green   (1, 5, 9, 13, 17, 21)
//   AT     — navy    (2, 6, 10, 14, 18, 22)
//   SUBJ   — orange  (3, 7, 11, 15, 19)
//   ASSURE — neutral (4, 8, 12, 16, 20)
function commissionPillClass(term) {
  const buckets = ['DFG', 'AT', 'SUBJ', 'ASSURE'];
  return buckets[(term - 1) % buckets.length];
}

const SUMMARY_PROMPT = `You are summarising a report from the Law Commission of India. Read the report excerpt below and produce a clear, plain-English briefing for a busy reader. Use this structure:

1. **What the report covers** (1-2 sentences — the legal area, the question being addressed)
2. **Background / context** (2-4 bullets — why this report was commissioned, prior law / case law cited, any constitutional dimension)
3. **Key recommendations** (3-6 bullets — the concrete legal-reform proposals)
4. **Reasoning** (2-4 bullets — the Commission's primary arguments for the recommendations)
5. **Status / implementation note** (1 sentence if the report's recommendations are known to have been adopted, partially adopted, or pending)

Keep it neutral, factual, and accessible to a non-specialist. Do not invent figures, statutes, or recommendations that aren't in the text.

REPORT:
{TEXT}`;

function buildAskPrompt({ summary, text, searchResults, question }) {
  const parts = [
    'You are answering questions about a specific report from the Law Commission of India. Use only the supplied material below to answer. If the answer isn\'t in the supplied material, say so clearly.',
  ];
  if (summary) parts.push('', 'SUMMARY (previously generated by AI):', summary);
  parts.push('', 'REPORT:', text);
  if (searchResults && searchResults.length) {
    parts.push('', 'RECENT WEB CONTEXT (use cautiously, prefer the report itself when they conflict):');
    for (const r of searchResults) parts.push(`- ${r.title}\n  ${r.url}\n  ${r.snippet}`);
  }
  parts.push('', '---', '', 'QUESTION: ' + question);
  return parts.join('\n');
}

// ── Module-private state ────────────────────────────────────────────────────

const state = {
  // reports is a FLAT dict keyed by report_number-as-string.
  data: { reports: {}, manifest: {}, meta: null },
  filtered: [],
  selectedReport: null,
  filters: { search: '', commission_term: '', year: '', sort: 'number_desc' },

  cache: {
    summaries: {},   // reportKey -> string
    text:      {},   // reportKey -> string (in-memory; IDB-backed)
    chats:     {},   // reportKey -> [{role, content, error?}]
  },

  dialogChat: [],

  searchBundle: null,
  bundleLoading: false,
  bundleLoaded:  false,

  searchIndex:  null,
  indexLoading: false,
  indexLoaded:  false,

  deepSearch: false,
  matchAny:   false,

  // archiveIndex: dict keyed by report_number (string) → {sha256, size_bytes,
  // archived_at, source_url}. Populated lazily from sansadsaar-lc's
  // index.json. When a report_number is present, the detail panel shows an
  // "Archive copy" link; absent means we don't link (avoids 404s).
  archiveIndex: {},
  archiveLoaded: false,

  streamingContext: null,
};

let _deps = null;
let _activated = false;   // gates one-time setup; activate() can re-run cheaply

// ── Helpers ─────────────────────────────────────────────────────────────────

function reportKey(r) {
  return `lc|${r.report_number}`;
}

function reportDate(r) {
  // date_submitted is ISO yyyy-mm-dd when parseable, else raw.
  if (r.date_submitted) {
    const d = new Date(r.date_submitted);
    if (!isNaN(d)) return d;
  }
  if (r.year) {
    const y = new Date(`Jan 1, ${r.year}`);
    if (!isNaN(y)) return y;
  }
  return null;
}

function formatDate(d) {
  if (!d) return '—';
  return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

function commissionLabel(term) {
  return COMMISSION_ORDINAL[term] || `${term}th`;
}

// ── Data fetching ───────────────────────────────────────────────────────────

async function fetchData(forceRefresh = false) {
  const splash    = document.getElementById('splash');   // shared with shell
  const splashErr = document.getElementById('splashError');
  const dataUrl   = _deps.config.dataBaseUrl;

  if (!forceRefresh) {
    try {
      const [reportsBlob, manifestBlob, metaBlob] = await Promise.all([
        idbGet('blobs', 'lc-reports.json'),
        idbGet('blobs', 'lc-manifest.json'),
        idbGet('blobs', 'lc-meta.json'),
      ]);
      if (reportsBlob && manifestBlob) {
        state.data.reports  = reportsBlob;
        state.data.manifest = manifestBlob;
        state.data.meta     = metaBlob || null;
      }
    } catch (e) { console.warn('LC IDB cache miss', e); }
  }

  const haveCache = Object.keys(state.data.reports).length > 0;
  const bucket = Math.floor(Date.now() / 300000);
  const v = forceRefresh ? `?v=${Date.now()}` : `?v=${bucket}`;
  const fetchOpts = { cache: 'no-cache' };

  try {
    const [reports, manifest, meta] = await Promise.all([
      fetch(dataUrl + CORPUS_PREFIX + 'reports.json'  + v, fetchOpts).then(r => r.ok ? r.json() : Promise.reject(`reports.json: ${r.status}`)),
      fetch(dataUrl + CORPUS_PREFIX + 'manifest.json' + v, fetchOpts).then(r => r.ok ? r.json() : { texts: {} }).catch(() => ({ texts: {} })),
      fetch(dataUrl + CORPUS_PREFIX + 'meta.json'     + v, fetchOpts).then(r => r.ok ? r.json() : null).catch(() => null),
    ]);
    state.data.reports  = reports;
    state.data.manifest = manifest;
    state.data.meta     = meta;

    // Cache under lc-prefixed IDB keys so corpora don't collide on
    // 'reports.json' / 'manifest.json' / 'meta.json'.
    idbPut('blobs', 'lc-reports.json',  reports).catch(() => {});
    idbPut('blobs', 'lc-manifest.json', manifest).catch(() => {});
    if (meta) idbPut('blobs', 'lc-meta.json', meta).catch(() => {});
  } catch (err) {
    console.error('LC fetch failed', err);
    if (!haveCache) {
      _deps.ui.toast('Could not fetch LC data — see console for details');
      return false;
    }
    _deps.ui.toast('LC offline — using cached data');
  }

  splash?.classList.add('hide');
  return true;
}

async function fetchArchiveIndex() {
  // Best-effort: pull sansadsaar-lc/index.json so renderDetailsTab can
  // tell which reports have an archived PDF. IDB-cached. Silent on
  // failure (the archive is a hedge — if we can't reach raw.gh, we just
  // don't surface the fallback link). 5-min cache bucket on the URL keeps
  // browsers from over-fetching while still picking up new entries
  // within the day.
  try {
    const cached = await idbGet('blobs', 'lc-archive-index.json');
    if (cached?.reports) {
      state.archiveIndex = cached.reports;
      state.archiveLoaded = true;
    }
  } catch {}
  const bucket = Math.floor(Date.now() / 300000);
  try {
    const res = await fetch(`${ARCHIVE_INDEX_URL}?v=${bucket}`, { cache: 'no-cache' });
    if (!res.ok) {
      // 404 is expected before the first archive commit lands. Don't toast.
      if (res.status !== 404) console.warn('LC archive index fetch:', res.status);
      return;
    }
    const data = await res.json();
    if (data?.reports) {
      state.archiveIndex = data.reports;
      state.archiveLoaded = true;
      idbPut('blobs', 'lc-archive-index.json', data).catch(() => {});
    }
  } catch (e) {
    console.warn('LC archive index fetch failed', e);
  }
}

function archiveEntry(r) {
  return state.archiveIndex?.[String(r.report_number)] || null;
}

async function fetchReportText(report) {
  const key = reportKey(report);
  if (state.cache.text[key]) return state.cache.text[key];

  try {
    const cached = await idbGet('texts', key);
    if (cached) {
      state.cache.text[key] = cached;
      return cached;
    }
  } catch {}

  const entry = state.data.manifest?.texts?.[String(report.report_number)];
  if (!entry) return null;

  // Primary path: bundled text-shards. LC composite key = report_number.
  try {
    const text = await loadTextFromShards('lc', String(report.report_number), _deps.config.dataBaseUrl);
    if (text !== null) {
      state.cache.text[key] = text;
      idbPut('texts', key, text).catch(() => {});
      _deps.disk?.write?.('lc', entry.url, text).catch(() => {});
      return text;
    }
  } catch (e) {
    console.warn('lc: text-shard fetch failed, falling back to legacy URL', e);
  }

  // Legacy fallback: per-file text/<id>.txt.
  try {
    const res = await fetch(_deps.config.dataBaseUrl + CORPUS_PREFIX + entry.url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const text = await res.text();
    state.cache.text[key] = text;
    idbPut('texts', key, text).catch(() => {});
    // Lazily mirror to disk if a folder is connected. Best-effort, silent
    // when no folder. See CONV.md "Save-to-Disk pattern".
    _deps.disk?.write?.('lc', entry.url, text).catch(() => {});
    return text;
  } catch (e) {
    // Network failed. Fall back to disk if connected.
    try {
      const fromDisk = await _deps.disk?.read?.('lc', entry.url);
      if (fromDisk) {
        state.cache.text[key] = fromDisk;
        idbPut('texts', key, fromDisk).catch(() => {});
        return fromDisk;
      }
    } catch {}
    console.warn('LC: failed to fetch text', e);
    return null;
  }
}

// ── Filtering / list rendering ──────────────────────────────────────────────

function getAllReports() {
  return Object.values(state.data.reports).map(r => ({
    ...r,
    _date: reportDate(r),
  }));
}

function applyFilters() {
  const all = getAllReports();
  const f = state.filters;
  const rawQ = f.search.trim();
  const parsedQ = rawQ ? parseQuery(rawQ) : null;
  const bundle = state.searchBundle;

  const tokenIndexSets = parsedQ
    ? parsedQ.tokens.map(t => expandTokenToDocs(state.searchIndex, t))
    : [];

  const filtered = all.filter(r => {
    if (f.commission_term && String(r.commission_term) !== f.commission_term) return false;
    if (f.year && String(r.year || '') !== f.year) return false;
    if (!parsedQ) return true;

    const key = reportKey(r);
    const titleLower  = (r.title || '').toLowerCase();
    const bundleEntry = bundle ? bundle.map.get(key) : null;
    const headLower   = bundleEntry ? bundleEntry.head.toLowerCase() : '';
    const cached      = state.cache.text[key];
    const cachedLower = cached ? cached.toLowerCase() : '';

    function tokenHits(tok, indexSet) {
      if (indexSet && indexSet.has(key)) return true;
      if (titleLower.includes(tok)) return true;
      if (headLower && headLower.includes(tok)) return true;
      if (cachedLower && cachedLower.includes(tok)) return true;
      return false;
    }
    function phraseHits(phrase) {
      if (titleLower.includes(phrase)) return true;
      if (headLower && headLower.includes(phrase)) return true;
      if (cachedLower && cachedLower.includes(phrase)) return true;
      return false;
    }

    if (state.matchAny) {
      const hit = parsedQ.tokens.some((t, i) => tokenHits(t, tokenIndexSets[i]))
              ||  parsedQ.phrases.some(phraseHits);
      if (!hit) return false;
    } else {
      if (!parsedQ.tokens.every((t, i) => tokenHits(t, tokenIndexSets[i]))) return false;
      if (!parsedQ.phrases.every(phraseHits)) return false;
    }
    return true;
  });

  filtered.sort((a, b) => {
    switch (f.sort) {
      case 'date_desc':    return (b._date || 0) - (a._date || 0);
      case 'date_asc':     return (a._date || 0) - (b._date || 0);
      case 'number_asc':   return (a.report_number || 0) - (b.report_number || 0);
      case 'commission_desc': {
        const t = (b.commission_term || 0) - (a.commission_term || 0);
        if (t !== 0) return t;
        return (b.report_number || 0) - (a.report_number || 0);
      }
      case 'number_desc':
      default:             return (b.report_number || 0) - (a.report_number || 0);
    }
  });

  state.filtered = filtered;
  renderList();
  renderResultsLine();
}

function renderResultsLine() {
  const el = document.getElementById('resultsLine');
  if (!el) return;
  const total = getAllReports().length;
  const shown = state.filtered.length;
  const meta = state.data.meta;
  let metaLine = '';
  if (meta?.generated_at) {
    metaLine = `Mirror updated <b>${escapeHtml(formatLocalTimestamp(meta.generated_at))}</b>`;
  }

  let indexLine = '';
  const bundle = state.searchBundle;
  const idx = state.searchIndex;
  const mirrorWithText = Object.keys(state.data.manifest?.texts || {}).length;
  const loading = state.bundleLoading || state.indexLoading;
  if (loading) {
    const what = state.bundleLoading && state.indexLoading
      ? 'bundle + index'
      : state.bundleLoading ? 'bundle' : 'index';
    indexLine = `<span class="indexing">Loading search ${what}…</span>`;
  } else if (state.deepSearch && state.bundleLoaded && bundle) {
    const tooltip = idx
      ? `Search hits titles + first ${bundle.head_chars} chars of every report, plus body-token presence across the corpus.`
      : `Search hits titles + first ${bundle.head_chars} chars of every report.`;
    indexLine = `<span title="${escapeHtml(tooltip)}">Full-text search · ${bundle.total} reports</span>`
              + ` · <label class="match-any-toggle"><input type="checkbox" id="matchAnyToggle"${state.matchAny ? ' checked' : ''}>match any</label>`;
  } else if (mirrorWithText === 0) {
    indexLine = '';
  } else {
    indexLine = `<span>Title search only · <b>${mirrorWithText}</b> reports with text · <a href="#" id="enableDeepLink" style="color:var(--accent)">enable deep search</a></span>`;
  }
  el.innerHTML = (shown > 0 && shown < total)
    ? `<div class="rl-primary">Showing <b>${shown}</b> of <b>${total}</b></div>`
    : '';

  const enableLink = document.getElementById('enableDeepLink');
  if (enableLink) {
    enableLink.addEventListener('click', (e) => {
      e.preventDefault();
      state.deepSearch = true;
      const s = loadSettings();
      s.lc_deepSearch = true;
      saveSettings(s);
      renderResultsLine();
      Promise.all([loadSearchBundle(), loadSearchIndex()]).then(() => {
        renderResultsLine();
        if (state.filters.search) applyFilters();
      });
    });
  }
  const matchAnyToggle = document.getElementById('matchAnyToggle');
  if (matchAnyToggle) {
    matchAnyToggle.addEventListener('change', (e) => {
      state.matchAny = !!e.target.checked;
      const s = loadSettings();
      s.lc_matchAny = state.matchAny;
      saveSettings(s);
      applyFilters();
    });
  }

  const sumBtn = document.getElementById('exportSummariesBtn');
  if (sumBtn) {
    const n = Object.keys(state.cache.summaries || {}).length;
    sumBtn.disabled = n === 0;
    sumBtn.textContent = n ? `⬇ Summaries (MD, ${n})` : '⬇ Summaries (MD)';
  }
}

function hasExtractedText(r) {
  return !!state.data.manifest?.texts?.[String(r.report_number)];
}
function hasSummary(r) {
  return !!state.cache.summaries[reportKey(r)];
}

function renderList() {
  const list = document.getElementById('reportsList');
  if (!list) return;
  if (!state.filtered.length) {
    list.innerHTML = `<div class="empty-state"><h3>No reports match</h3><p>Try clearing filters.</p></div>`;
    return;
  }
  const slice = state.filtered.slice(0, 200);
  const rawQ = state.filters.search.trim();
  const parsedQ = rawQ ? parseQuery(rawQ) : null;
  list.innerHTML = slice.map(r => {
    const titleHTML = parsedQ ? highlightMatches(r.title || '(untitled)', parsedQ)
                              : escapeHtml(r.title || '(untitled)');
    const term      = r.commission_term;
    const termLabel = commissionLabel(term);
    const termClass = commissionPillClass(term);
    const subline   = `Report #${r.report_number} · ${escapeHtml(r.date_submitted_raw || r.date_submitted || '—')}`;
    const yearStr   = r.year ?? '—';
    return `
      <div class="report-row" data-key="${escapeHtml(reportKey(r))}">
        <div>
          <div class="report-title">${titleHTML}</div>
          <div class="report-meta">${subline}</div>
        </div>
        <span class="cat-badge cat-${termClass}" title="${escapeHtml(termLabel + ' Law Commission')}">${escapeHtml(termLabel)}</span>
        <span class="report-meta">${escapeHtml(String(yearStr))}</span>
        <span class="text-status ${hasSummary(r) ? 'summary' : (hasExtractedText(r) ? 'ok' : '')}">
          ${hasSummary(r) ? 'summary' : (hasExtractedText(r) ? 'text' : 'metadata')}
        </span>
      </div>
    `;
  }).join('');
  if (state.filtered.length > 200) {
    list.insertAdjacentHTML('beforeend',
      `<div class="empty-state" style="padding:18px"><p>Showing first 200 of ${state.filtered.length} matches — refine filters to narrow further.</p></div>`);
  }
}

function renderHeaderStats() {
  const el = document.getElementById('headerStats');
  if (!el) return;
  const total = Object.keys(state.data.reports).length;
  const withText = Object.keys(state.data.manifest?.texts || {}).length;
  el.innerHTML = `
    <span><b>${total}</b> reports</span>
    <span><b>${withText}</b> with text</span>
  `;
}

function populateFilters() {
  const reports = Object.values(state.data.reports);
  const termSet = new Set();
  const yearSet = new Set();
  for (const r of reports) {
    if (r.commission_term != null) termSet.add(r.commission_term);
    if (r.year) yearSet.add(r.year);
  }

  const termSel = document.getElementById('filterCommissionTerm');
  if (termSel) {
    // Sort terms descending (22nd → 1st) so the active Commission is on top.
    termSel.innerHTML = '<option value="">All Commissions</option>' +
      [...termSet].sort((a, b) => b - a).map(t =>
        `<option value="${t}">${escapeHtml(commissionLabel(t))} Commission</option>`).join('');
  }
  const yearSel = document.getElementById('filterYear');
  if (yearSel) {
    yearSel.innerHTML = '<option value="">All years</option>' +
      [...yearSet].sort((a, b) => b - a).map(v => `<option value="${v}">${v}</option>`).join('');
  }

  // Re-apply persisted state values so corpus-switch round-trips show the
  // active selection in the dropdown UI (not just in state.filters).
  if (termSel) termSel.value = state.filters.commission_term || '';
  if (yearSel) yearSel.value = state.filters.year || '';
}

// ── Report dialog ───────────────────────────────────────────────────────────

function openReportByKey(key) {
  const all = getAllReports();
  const r = all.find(x => reportKey(x) === key);
  if (!r) return;
  if (_deps.ai.streaming() && state.streamingContext?.reportKey !== key) {
    _deps.ai.stop();
    state.streamingContext = null;
  }
  state.selectedReport = r;
  state.dialogChat = state.cache.chats[key] ? [...state.cache.chats[key]] : [];
  document.getElementById('reportTitle').textContent = r.title || '(untitled)';
  renderDetailsTab(r);
  switchReportTab('details');
  document.getElementById('reportModal').classList.add('open');
}

function renderDetailsTab(r) {
  const termLabel = commissionLabel(r.commission_term);
  const dateLine  = r.date_submitted_raw || r.date_submitted || '—';
  // LC source pages use the per-Commission listing as the closest thing to
  // a "source URL" — no individual detail page exists. Synthesize the link
  // from the Commission term.
  const ordinalSlug = ({
    1:'first',2:'second',3:'third',4:'fourth',5:'fifth',6:'sixth',7:'seventh',
    8:'eighth',9:'ninth',10:'tenth',11:'eleventh',12:'twelfth',13:'thirteenth',
    14:'fourteenth',15:'fifteenth',16:'sixteenth',17:'seventeenth',
    18:'eighteenth',19:'nineteenth',20:'twentieth',21:'twentyfirst',
    22:'twentysecond',
  })[r.commission_term];
  const sourceUrl = ordinalSlug
    ? `https://lawcommissionofindia.nic.in/report_${ordinalSlug}/`
    : 'https://lawcommissionofindia.nic.in/law-commission-reports/';

  // Archive copy — shown only when sansadsaar-lc has confirmed the PDF.
  // The upstream WordPress / S3WaaS site is fragile; we link to it as
  // primary but offer the archive as a one-click fallback. See the top
  // of this file for the archive URL pattern + rationale.
  const arch = archiveEntry(r);
  const archiveLine = arch
    ? `<dt title="Mirror copy in sansadsaar-lc, kept in case upstream URL rotates / goes offline.">Archive copy</dt><dd><a href="${escapeHtml(ARCHIVE_PDF_URL(r.report_number))}" target="_blank" rel="noopener">${r.report_number}.pdf</a> <span class="report-meta" style="font-size:0.78rem">· archived ${escapeHtml((arch.archived_at || '').split('T')[0] || '—')}</span></dd>`
    : '';

  document.getElementById('detailsTab').innerHTML = `
    <dl class="meta-grid">
      <dt>Title</dt><dd>${escapeHtml(r.title || '—')}</dd>
      <dt>Report no.</dt><dd>${escapeHtml(String(r.report_number))}</dd>
      <dt>Commission</dt><dd>${escapeHtml(termLabel)} Law Commission of India</dd>
      <dt>Date submitted</dt><dd>${escapeHtml(dateLine)}</dd>
      ${r.year ? `<dt>Year</dt><dd>${r.year}</dd>` : ''}
      ${r.pdf_url ? `<dt>PDF</dt><dd><a href="${escapeHtml(r.pdf_url)}" target="_blank" rel="noopener">${escapeHtml(r.pdf_url.split('/').pop())}</a></dd>` : ''}
      ${archiveLine}
      <dt>Source</dt><dd><a href="${escapeHtml(sourceUrl)}" target="_blank" rel="noopener">lawcommissionofindia.nic.in</a></dd>
    </dl>
    <p style="margin-top:14px; font-size:0.82rem; color:var(--muted)">
      ${hasExtractedText(r)
        ? 'Full text has been extracted by the mirror — see the "Full text" tab or generate an AI summary.'
        : 'Full text has not yet been extracted by the mirror. The daily Action picks reports up incrementally — check back, or open the PDF directly.'}
    </p>
  `;
}

async function loadTextTab() {
  const r = state.selectedReport;
  const tab = document.getElementById('textTab');
  if (!r) { tab.innerHTML = ''; return; }
  if (!hasExtractedText(r)) {
    tab.innerHTML = `<p>Full text hasn't been extracted yet. Open the PDF link from the Details tab.</p>`;
    return;
  }
  tab.innerHTML = `<p style="color:var(--muted)">Loading…</p>`;
  const text = await fetchReportText(r);
  if (!text) { tab.innerHTML = `<p>Could not load the extracted text.</p>`; return; }
  tab.innerHTML = `<pre>${escapeHtml(text)}</pre>`;
  renderList();
}

function switchReportTab(name) {
  // Multi-corpus guard — every corpus binds a click listener on the
  // shared #reportModal .tab-btn elements at activate time, so clicks
  // fan out to all corpora. Only the active corpus should respond.
  // See CONV.md "Multi-corpus shared-DOM guard".
  if (_deps.activeCorpus?.() !== 'lc') return;
  document.querySelectorAll('#reportModal .tab-btn').forEach(b => b.classList.toggle('active', b.dataset.tab === name));
  document.querySelectorAll('#reportModal .tab-pane').forEach(p => p.classList.remove('active'));
  document.getElementById(name + 'Tab').classList.add('active');
  if (name === 'text')    loadTextTab();
  if (name === 'summary') renderSummaryTab();
  if (name === 'chat')    renderChatTab();
}

function renderSummaryTab() {
  const tab = document.getElementById('summaryTab');
  const r = state.selectedReport;
  if (!r) { tab.innerHTML = ''; return; }
  if (!_deps.ai.isUsable()) {
    tab.innerHTML = _deps.ai.notReadyHTML();
    _deps.ai.bindNotReadyCTA(tab);
    return;
  }
  const key = reportKey(r);
  const cached = state.cache.summaries[key];
  const isStreaming = state.streamingContext?.reportKey === key
                  &&  state.streamingContext?.tab === 'summary';

  if (isStreaming) {
    tab.innerHTML = `
      <div class="summary-actions">
        <span class="label">Generating summary… (streams in below)</span>
        <button class="ghost sm" id="stopSummaryBtn">Stop</button>
      </div>
      <div class="summary-box" id="summaryBox">${escapeHtml(cached || '')}</div>
    `;
    document.getElementById('stopSummaryBtn').addEventListener('click', () => {
      _deps.ai.stop();
      state.streamingContext = null;
    });
    return;
  }

  tab.innerHTML = `
    <div class="summary-actions">
      <span class="label">Generate a plain-English summary using your configured AI:</span>
      <button class="primary" id="generateSummaryBtn">${cached ? 'Regenerate' : 'Generate'}</button>
      <button class="ghost sm" id="copySummaryBtn" ${cached ? '' : 'style="display:none"'}>Copy</button>
    </div>
    <div class="summary-box" id="summaryBox">${cached ? escapeHtml(cached) : 'No summary yet.'}</div>
  `;
  document.getElementById('generateSummaryBtn').addEventListener('click', generateSummary);
  document.getElementById('copySummaryBtn').addEventListener('click', () => {
    navigator.clipboard.writeText(document.getElementById('summaryBox').textContent || '');
    _deps.ui.toast('Copied');
  });
}

function renderChatTab() {
  const tab = document.getElementById('chatTab');
  const r = state.selectedReport;
  if (!r) { tab.innerHTML = ''; return; }
  if (!_deps.ai.isUsable()) {
    tab.innerHTML = _deps.ai.notReadyHTML();
    _deps.ai.bindNotReadyCTA(tab);
    return;
  }
  const key = reportKey(r);
  const isStreaming = state.streamingContext?.reportKey === key
                  &&  state.streamingContext?.tab === 'chat';

  const messages = state.dialogChat.length
    ? state.dialogChat
    : [{ role: 'system', content: 'Ask anything about this Law Commission report. Your question + the report text are sent to the AI you configured (local Gemma or BYOK).' }];

  const threadHTML = messages.map(m => {
    const cls = `chat-msg ${m.role}${m.error ? ' error' : ''}`;
    return `<div class="${cls}">${escapeHtml(m.content)}</div>`;
  }).join('');

  const searchOn = _deps.search.isConfigured();
  tab.innerHTML = `
    <div class="chat-thread" id="chatThread">${threadHTML}</div>
    <div class="chat-input-row">
      <textarea id="chatInput" rows="2" placeholder="Ask a question about this Law Commission report..." ${isStreaming ? 'disabled' : ''}></textarea>
      ${searchOn ? `<button class="ghost sm" id="chatSearchSendBtn" title="Search the web AND Send" ${isStreaming ? 'disabled' : ''}>&#127760;</button>` : ''}
      <button class="primary" id="chatSendBtn" ${isStreaming ? 'disabled' : ''}>Send</button>
      <button class="ghost sm" id="chatStopBtn" ${isStreaming ? '' : 'style="display:none"'}>Stop</button>
    </div>
  `;
  document.getElementById('chatSendBtn').addEventListener('click', () => chatSend({}));
  if (searchOn) document.getElementById('chatSearchSendBtn').addEventListener('click', () => chatSend({ withSearch: true }));
  document.getElementById('chatStopBtn').addEventListener('click', () => {
    _deps.ai.stop();
    state.streamingContext = null;
  });
  document.getElementById('chatInput').addEventListener('keydown', e => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); chatSend({}); }
  });
  const t = document.getElementById('chatThread');
  if (t) t.scrollTop = t.scrollHeight;
}

function _truncateForContext(text) {
  const limit = _deps.ai.mode() === 'local' ? 12000 : 60000;
  if (text.length <= limit) return text;
  return text.slice(0, limit) + '\n\n[...truncated for context window...]';
}

async function generateSummary() {
  const r = state.selectedReport;
  if (!r) return;
  const text = await fetchReportText(r);
  if (!text) {
    _deps.ui.toast('Full text not available — extract pending');
    return;
  }
  const key = reportKey(r);
  const prompt = SUMMARY_PROMPT.replace('{TEXT}', _truncateForContext(text));
  const messages = [
    { role: 'system', content: 'You are a careful, accurate summariser of public-sector legal-reform reports.' },
    { role: 'user',   content: prompt },
  ];

  const previousCached = state.cache.summaries[key] || '';
  state.streamingContext = { reportKey: key, tab: 'summary' };
  renderSummaryTab();
  try {
    const result = await streamWithPersistence({
      generate: _deps.ai.generate,
      messages,
      onText: (full) => {
        if (state.streamingContext?.reportKey === key) {
          const box = document.getElementById('summaryBox');
          if (box) box.textContent = full;
        }
      },
    });
    if (result.ok) {
      state.cache.summaries[key] = result.text;
      idbPut('summaries', key, result.text).catch(() => {});
      if (_deps.disk?.saveAi?.() && _deps.disk?.isConnected?.()) {
        _deps.disk.write('lc', `ai/${r.report_number}.summary.md`, result.text).catch(() => {});
      }
    } else {
      state.cache.summaries[key] = previousCached;
      _deps.ui.toast('Summary generation failed: ' + result.error.message);
    }
  } finally {
    state.streamingContext = null;
    renderSummaryTab();
    renderList();
  }
}

async function chatSend(opts) {
  opts = opts || {};
  const r = state.selectedReport;
  if (!r) return;
  const input = document.getElementById('chatInput');
  const q = input.value.trim();
  if (!q) return;
  if (_deps.ai.streaming()) { _deps.ui.toast('Already responding…'); return; }
  const text = await fetchReportText(r);
  if (!text) { _deps.ui.toast('Full text not available'); return; }

  const k = reportKey(r);
  state.dialogChat.push({ role: 'user', content: q });
  try {
    let searchResults = null;
    if (opts.withSearch) {
      if (!_deps.search.isConfigured()) {
        state.dialogChat.push({ role: 'system', content: 'Web search not configured. Open Settings → Web search to add a provider.' });
        input.value = '';
        renderChatTab();
        return;
      }
      state.dialogChat.push({ role: 'system', content: `Searching the web for "${q}"…` });
      renderChatTab();
      try {
        searchResults = await _deps.search.run(q);
        const resultLine = searchResults.length
          ? `Found ${searchResults.length} result${searchResults.length === 1 ? '' : 's'}: ${searchResults.map(x => x.title).slice(0, 3).join(' · ')}${searchResults.length > 3 ? '…' : ''}`
          : 'No web results.';
        state.dialogChat[state.dialogChat.length - 1] = { role: 'system', content: resultLine };
      } catch (e) {
        state.dialogChat[state.dialogChat.length - 1] = { role: 'system', content: 'Search failed: ' + e.message };
        searchResults = null;
      }
    }
    state.dialogChat.push({ role: 'assistant', content: '' });
    state.streamingContext = { reportKey: reportKey(r), tab: 'chat' };
    input.value = '';
    renderChatTab();
    const summary = state.cache.summaries[reportKey(r)];
    const userPrompt = buildAskPrompt({
      summary: summary || null,
      text: _truncateForContext(text),
      searchResults,
      question: q,
    });
    const messages = [
      { role: 'system', content: 'You answer questions about reports from the Law Commission of India. Use only the supplied material. If the answer is not present, say so.' },
      { role: 'user',   content: userPrompt },
    ];
    const result = await streamWithPersistence({
      generate: _deps.ai.generate,
      messages,
      onText: (full) => {
        const last = state.dialogChat[state.dialogChat.length - 1];
        last.content = full;
        const lastEl = document.querySelector('#chatThread .chat-msg.assistant:last-child');
        if (lastEl) {
          lastEl.textContent = full;
          const t = document.getElementById('chatThread');
          if (t) t.scrollTop = t.scrollHeight;
        }
      },
    });
    const last = state.dialogChat[state.dialogChat.length - 1];
    if (result.ok) {
      last.content = result.text;
    } else {
      last.error = true;
      last.content = 'Error: ' + result.error.message;
    }
  } finally {
    state.streamingContext = null;
    renderChatTab();
    state.cache.chats[k] = [...state.dialogChat];
    idbPut('chats', k, state.dialogChat).catch(() => {});
    if (_deps.disk?.saveAi?.() && _deps.disk?.isConnected?.()) {
      _deps.disk.write('lc', `ai/${r.report_number}.chat.json`, JSON.stringify(state.dialogChat, null, 2)).catch(() => {});
    }
  }
}

// ── Search bundle + index ──────────────────────────────────────────────────
//
// Mechanism lives in app/corpus-search.js; these are thin wrappers that
// supply the corpus-specific IDB key + URL prefix + meta + state-update
// hooks.

async function loadSearchBundle() {
  return sharedLoadSearchBundle({
    state,
    corpusId:    'lc',
    idbKey:      'lc-search-bundle.json',
    urlPath:     CORPUS_PREFIX,
    meta:        state.data.meta,
    deps:        _deps,
    onChange:    renderResultsLine,
    onAfterLoad: () => { if (state.filters.search) applyFilters(); },
  });
}

async function loadSearchIndex() {
  return sharedLoadSearchIndex({
    state,
    corpusId:    'lc',
    idbKey:      'lc-search-index.json',
    urlPath:     CORPUS_PREFIX,
    meta:        state.data.meta,
    deps:        _deps,
    onChange:    renderResultsLine,
    onAfterLoad: () => { if (state.filters.search) applyFilters(); },
  });
}

// ── Export ──────────────────────────────────────────────────────────────────

function _csvCell(v) {
  if (v == null) return '';
  const s = String(v);
  if (/[",\n\r]/.test(s)) return '"' + s.replace(/"/g, '""') + '"';
  return s;
}

function _downloadBlob(filename, mime, content) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  setTimeout(() => { URL.revokeObjectURL(url); a.remove(); }, 100);
}

function _ts() {
  const d = new Date();
  const pad = n => String(n).padStart(2, '0');
  return `${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}`;
}

function exportMetadataCSV() {
  const rows = state.filtered;
  if (!rows.length) { _deps.ui.toast('No reports to export'); return; }
  const headers = [
    'report_number', 'title', 'commission_term', 'date_submitted',
    'date_submitted_raw', 'year', 'pdf_url', 'has_text', 'has_summary',
  ];
  const lines = [headers.join(',')];
  for (const r of rows) {
    lines.push([
      r.report_number, r.title, r.commission_term, r.date_submitted,
      r.date_submitted_raw, r.year, r.pdf_url,
      hasExtractedText(r) ? 'yes' : 'no',
      hasSummary(r) ? 'yes' : 'no',
    ].map(_csvCell).join(','));
  }
  const csv = lines.join('\n') + '\n';
  _downloadBlob(`sansadsaar-lc-metadata-${_ts()}.csv`, 'text/csv', csv);
  _deps.ui.toast(`Exported ${rows.length} Law Commission reports`);
}

function exportSummariesMD() {
  const all = getAllReports();
  const out = [];
  out.push(`# SansadSaar — Law Commission summaries`);
  out.push('');
  out.push(`Exported ${new Date().toLocaleString('en-IN')}. Source: <https://sansadsaar.naklitechie.com>.`);
  out.push('');
  let n = 0;
  for (const r of all) {
    const key = reportKey(r);
    const summary = state.cache.summaries[key];
    if (!summary) continue;
    n++;
    out.push('---');
    out.push('');
    out.push(`## #${r.report_number} — ${r.title || '(untitled)'}`);
    out.push('');
    const meta = [
      `${commissionLabel(r.commission_term)} Commission`,
      r.date_submitted_raw || r.date_submitted,
      r.year,
    ].filter(Boolean).join(' · ');
    if (meta) out.push(`*${meta}*`);
    if (r.pdf_url) out.push(`*PDF: <${r.pdf_url}>*`);
    out.push('');
    out.push(summary);
    out.push('');
  }
  if (!n) { _deps.ui.toast('No LC summaries cached yet'); return; }
  _downloadBlob(`sansadsaar-lc-summaries-${_ts()}.md`, 'text/markdown', out.join('\n'));
  _deps.ui.toast(`Exported ${n} summaries`);
}

// ── IDB hydration ──────────────────────────────────────────────────────────

const _matchLcKey = (k) => k.startsWith('lc|');

async function loadCachedSummaries() {
  // Caller gates renderList() on !silent — see drsc/index.js loadCachedSummaries
  // for rationale (silent cross-corpus preloads must not touch visible DOM).
  await hydrateFromIDB({ store: 'summaries', target: state.cache.summaries, matches: _matchLcKey });
}

async function loadCachedChats() {
  await hydrateFromIDB({ store: 'chats', target: state.cache.chats, matches: _matchLcKey });
}

async function loadCachedTexts() {
  const { added } = await hydrateFromIDB({
    store: 'texts', target: state.cache.text, matches: _matchLcKey,
  });
  return added;
}

// ── Filter row HTML + handlers ──────────────────────────────────────────────

function renderFilterRow() {
  const container = document.getElementById('filtersContainer');
  if (!container) return;
  container.innerHTML = `
    <input type="search" id="filterSearch" placeholder="Search Law Commission reports..." autocomplete="off">
    <select id="filterCommissionTerm"><option value="">All Commissions</option></select>
    <select id="filterYear"><option value="">All years</option></select>
    <select id="filterSort">
      <option value="number_desc">Report no. (high→low)</option>
      <option value="number_asc">Report no. (low→high)</option>
      <option value="date_desc">Newest first</option>
      <option value="date_asc">Oldest first</option>
      <option value="commission_desc">By Commission (recent first)</option>
    </select>
    <button class="ghost sm" id="resetFiltersBtn" title="Reset filters">&times;</button>
  `;
  // Restore current filter values after re-render.
  document.getElementById('filterSearch').value = state.filters.search || '';
  document.getElementById('filterSort').value   = state.filters.sort   || 'number_desc';
}

function attachHandlers() {
  const debouncedSearch = debounce(() => { state.filters.search = document.getElementById('filterSearch').value; applyFilters(); }, 200);
  document.getElementById('filterSearch').addEventListener('input', debouncedSearch);
  document.getElementById('filterCommissionTerm').addEventListener('change', e => { state.filters.commission_term = e.target.value; applyFilters(); });
  document.getElementById('filterYear').addEventListener('change', e => { state.filters.year = e.target.value; applyFilters(); });
  document.getElementById('filterSort').addEventListener('change', e => { state.filters.sort = e.target.value; applyFilters(); });
  document.getElementById('resetFiltersBtn').addEventListener('click', () => {
    state.filters = { search: '', commission_term: '', year: '', sort: 'number_desc' };
    document.getElementById('filterSearch').value         = '';
    document.getElementById('filterCommissionTerm').value = '';
    document.getElementById('filterYear').value           = '';
    document.getElementById('filterSort').value           = 'number_desc';
    applyFilters();
  });

  // Reports list (event delegation)
  document.getElementById('reportsList').addEventListener('click', e => {
    const row = e.target.closest('.report-row');
    if (row) openReportByKey(row.dataset.key);
  });

  // Tab buttons (shared across corpora; guard against double-binding)
  document.querySelectorAll('#reportModal .tab-btn').forEach(b => {
    if (b.dataset._lcWired) return;
    b.dataset._lcWired = '1';
    b.addEventListener('click', () => switchReportTab(b.dataset.tab));
  });
  const closeBtn = document.getElementById('reportCloseBtn');
  if (closeBtn && !closeBtn.dataset._lcWired) {
    closeBtn.dataset._lcWired = '1';
    closeBtn.addEventListener('click', () => _deps.ui.closeModal('reportModal'));
  }

  // Toolbar exports
  const exportMeta = document.getElementById('exportMetaBtn');
  const exportSum  = document.getElementById('exportSummariesBtn');
  if (exportMeta) exportMeta.onclick = exportMetadataCSV;
  if (exportSum)  exportSum.onclick  = exportSummariesMD;
}

// ── Activation / lifecycle ──────────────────────────────────────────────────

async function activate(deps, { silent = false } = {}) {
  _deps = deps;

  // Always re-render filter row + handlers on visible activation so a
  // corpus switch back to LC restores the right UI in #filtersContainer.
  // Skip when silent (preload mode — shell prefetches data for cross-
  // corpus search without disturbing the visible DOM that belongs to
  // another corpus).
  if (!silent) {
    renderFilterRow();
    attachHandlers();
  }

  if (!_activated) {
    _activated = true;

    const settings = loadSettings();
    state.deepSearch = !!settings.lc_deepSearch;
    state.matchAny   = !!settings.lc_matchAny;

    const ok = await fetchData();
    if (!ok) return false;

    if (!silent) {
      populateFilters();
      renderHeaderStats();
      applyFilters();
    }

    loadCachedSummaries().then(() => { if (!silent) renderList(); });
    loadCachedChats();
    loadCachedTexts().then((n) => {
      if (n && !silent) {
        renderList();
        renderResultsLine();
      }
      if (state.deepSearch) {
        loadSearchBundle();
        loadSearchIndex();
      }
    });
    // Archive index is small (~50KB at full corpus) and best-effort; fire-
    // and-forget so it doesn't gate the splash. If a user opens a report
    // before this lands, the Archive line just doesn't render yet — they
    // see it on the next open after the index lands.
    fetchArchiveIndex();
  } else if (!silent) {
    populateFilters();
    renderHeaderStats();
    applyFilters();
  }

  return true;
}

function refreshAIDependentTabs() {
  if (!state.selectedReport) return;
  const sumActive  = document.getElementById('summaryTab')?.classList.contains('active');
  const chatActive = document.getElementById('chatTab')?.classList.contains('active');
  if (sumActive)  renderSummaryTab();
  if (chatActive) renderChatTab();
}

// ── Settings section ───────────────────────────────────────────────────────

function renderSettingsSection(container) {
  const meta = state.data.meta;
  const bundle = state.searchBundle;
  const indexStats = meta?.search_index;
  const bundleStats = meta?.search_bundle;

  let estimateLine;
  if (state.bundleLoaded && state.indexLoaded && bundle && state.searchIndex) {
    estimateLine = `Search bundle + body index loaded: ${bundle.total} reports, ${state.searchIndex.vocab_size.toLocaleString()} tokens indexed.`;
  } else if (state.bundleLoaded && bundle) {
    estimateLine = `Bundle loaded (${bundle.total} reports). Body index will load next.`;
  } else if (bundleStats?.size_bytes && indexStats?.size_bytes) {
    const totalMB = ((bundleStats.size_bytes + indexStats.size_bytes) / (1024 * 1024)).toFixed(1);
    estimateLine = `~${totalMB} MB total across all LC shards (CF gzip serves ~30%, cached locally after).`;
  } else {
    estimateLine = `Sharded download (1-2 files for the LC corpus size), cached locally after first load.`;
  }

  container.innerHTML = `
    <div class="settings-section">
      <h3>Search (Law Commission)</h3>
      <p>Enable deep search to fetch the LC bundle (title + first 5K chars per report) and body index — both cached locally after first load. Search semantics + match-any toggle work the same as for Standing Committees and CAG audits.</p>
      <div class="settings-row">
        <label for="lcDeepSearch">Deep search</label>
        <div>
          <label style="display:inline-flex; align-items:center; gap:6px; font-size:0.86rem; color:var(--text)">
            <input type="checkbox" id="lcDeepSearch" ${state.deepSearch ? 'checked' : ''} style="width:auto"> Enable full-text search across Law Commission reports
          </label>
          <p style="font-size:0.78rem; color:var(--muted); margin-top:4px">${escapeHtml(estimateLine)}</p>
        </div>
      </div>
    </div>

    <div class="settings-section">
      <h3>Data (Law Commission)</h3>
      <p id="lcDataInfo">${meta
        ? `${_deps.ui.stalenessIndicatorHTML('lc', meta)} · ${escapeHtml(String(meta.total_reports))} reports total · ${escapeHtml(String(meta.total_with_text))} with text`
        : `Source: ${escapeHtml(_deps?.config?.dataBaseUrl || '')}lc/`}</p>
      <button class="sm" id="lcRefreshDataBtn">Refresh from mirror</button>
    </div>
  `;
  _deps.ui.bindStalenessIndicators(container);

  document.getElementById('lcRefreshDataBtn').addEventListener('click', async () => {
    _deps.ui.toast('Refreshing LC…');
    await fetchData(true);
    populateFilters();
    renderHeaderStats();
    applyFilters();
    _deps.broadcast('lc:data-refreshed');
    renderSettingsSection(container);
    _deps.ui.toast('LC data refreshed');
  });
}

function applySettingsFromUI() {
  const wasDeep = state.deepSearch;
  const cbox = document.getElementById('lcDeepSearch');
  if (cbox) state.deepSearch = !!cbox.checked;
  const s = loadSettings();
  s.lc_deepSearch = state.deepSearch;
  saveSettings(s);
  if (state.deepSearch && !wasDeep) {
    loadSearchBundle();
    loadSearchIndex();
  }
}

// ── Status (per-corpus pill) ───────────────────────────────────────────────

async function fetchStatus() {
  const meta = state.data.meta;
  const withText = Object.keys(state.data.manifest?.texts || {}).length;
  if (!meta) return { lastUpdate: null, items: getAllReports().length, withText, error: null };
  return {
    lastUpdate: meta.generated_at || null,
    items: meta.total_reports || getAllReports().length,
    withText,
    error: null,
  };
}

// ── JS API surface ─────────────────────────────────────────────────────────

const api = {
  list({ commission_term, year } = {}) {
    return getAllReports().filter(r => {
      if (commission_term != null && String(r.commission_term) !== String(commission_term)) return false;
      if (year != null && String(r.year) !== String(year)) return false;
      return true;
    });
  },
  get(key) {
    return getAllReports().find(r => reportKey(r) === key) || null;
  },
  async search(query, opts = {}) {
    if (opts.deep && (!state.bundleLoaded || !state.indexLoaded)) {
      state.deepSearch = true;
      await Promise.all([loadSearchBundle(), loadSearchIndex()]);
    }
    const parsedQ = parseQuery(query);
    if (!parsedQ.tokens.length && !parsedQ.phrases.length) return getAllReports();
    const bundle = state.searchBundle;
    const tokenIndexSets = parsedQ.tokens.map(t => expandTokenToDocs(state.searchIndex, t));
    const anyMode = !!opts.any;
    return getAllReports().filter(r => {
      const key = reportKey(r);
      const titleLower  = (r.title || '').toLowerCase();
      const bundleEntry = bundle ? bundle.map.get(key) : null;
      const headLower   = bundleEntry ? bundleEntry.head.toLowerCase() : '';
      const cached      = state.cache.text[key];
      const cachedLower = cached ? cached.toLowerCase() : '';
      const tokHit = (t, idxSet) => (idxSet && idxSet.has(key))
        || titleLower.includes(t)
        || (headLower && headLower.includes(t))
        || (cachedLower && cachedLower.includes(t));
      const phHit = p => titleLower.includes(p)
        || (headLower && headLower.includes(p))
        || (cachedLower && cachedLower.includes(p));
      if (anyMode) {
        return parsedQ.tokens.some((t, i) => tokHit(t, tokenIndexSets[i]))
            || parsedQ.phrases.some(phHit);
      }
      return parsedQ.tokens.every((t, i) => tokHit(t, tokenIndexSets[i]))
          && parsedQ.phrases.every(phHit);
    });
  },
  open(key) {
    const r = api.get(key);
    if (!r) return false;
    openReportByKey(reportKey(r));
    return true;
  },
  /**
   * Cross-corpus search adapter — calls api.search and pre-formats hits
   * into the shape the global-search modal expects:
   *   { key, title, subtitle, meta? }
   */
  async searchForGlobal(query, { deep = true, limit = 10 } = {}) {
    const items = await api.search(query, { deep });
    const subs = (r) => {
      const parts = [];
      parts.push(`#${r.report_number}`);
      if (r.commission_term) parts.push(commissionLabel(r.commission_term) + ' Comm.');
      if (r.year)            parts.push(String(r.year));
      return parts.join(' · ');
    };
    return items.slice(0, limit).map(r => ({
      key:      reportKey(r),
      title:    r.title || '(untitled)',
      subtitle: subs(r),
    }));
  },
  commissionTerms: () => [...new Set(getAllReports().map(r => r.commission_term).filter(Boolean))].sort((a, b) => b - a),
};

// ── Export the corpus contract ─────────────────────────────────────────────

export const LCCorpus = {
  id:          'lc',
  label:       'Law Commission',
  shortLabel:  'LC',
  macroGroup:  'legislation',
  primaryUnit: 'report',

  fetchStatus,
  activate,

  api,
  renderSettingsSection,
  applySettingsFromUI,
  refreshAIDependentTabs,
};
