// app/corpora/fc/index.js
// FC = Financial Committees of Parliament.
// Three LS-chaired committees: Public Accounts (PAC), Estimates,
// Public Undertakings (COPU). Daily-mirrored from sansad.in via
// parliamentwatch-data's build_fc.py + fc.yml.
//
// Fifth registered corpus alongside DRSC, CAG, Bills, LC. Uses the
// composite reportKey shape `fc|<committee>|<lok_sabha>|<report_number>`
// (similar to DRSC's `drsc|<committee>|<ls>|<num>`) — same report
// number can recur across LS terms and across committees, so each
// dimension is part of the key.
//
// No archive sidecar: sansad.in is NIC-hosted and the most-stable
// upstream we touch. DRSC and Bills sit on the same host with no
// archive; FC follows that pattern.
//
// Independence Principle: this file does not import from cag, lc,
// drsc, or bills corpus modules. Some helper code is duplicated
// (date parsing, filter handlers); intentional per spec v0.4.

import {
  idbGet, idbPut, idbCursor,
  escapeHtml, debounce,
  loadSettings, saveSettings,
  formatLocalTimestamp,
} from '../../deps.js';
import { streamWithPersistence } from '../../ai-streaming.js';
import {
  parseQuery, highlightMatches,
  loadSearchBundle as sharedLoadSearchBundle,
  loadSearchIndex  as sharedLoadSearchIndex,
  expandTokenToDocs,
} from '../../corpus-search.js';
import { hydrateFromIDB } from '../../corpus-data.js';

const CORPUS_PREFIX = 'fc/';

// ── Constants ───────────────────────────────────────────────────────────────

// Three Financial Committees + display labels. Matches fc/scraper.py
// COMMITTEES dict — keep in sync.
const COMMITTEES = {
  pac:       { short: 'PAC',  long: 'Public Accounts',       type: 'Joint' },
  estimates: { short: 'EST',  long: 'Estimates',             type: 'LS only' },
  copu:      { short: 'COPU', long: 'Public Undertakings',   type: 'Joint' },
};

// Committee pill colours — reuse existing cat-badge palette from
// index.html (DFG green / AT navy / SUBJ orange). Keys map to CSS
// classes cat-DFG / cat-AT / cat-SUBJ defined globally.
const COMMITTEE_PILL_CLASS = {
  pac:       'DFG',
  estimates: 'AT',
  copu:      'SUBJ',
};

const SUMMARY_PROMPT = `You are summarising a Financial Committee report from the Indian Parliament. The Financial Committees (Public Accounts, Estimates, Public Undertakings) examine government finance — auditor's reports, budget estimates, public sector enterprises. Read the report excerpt below and produce a clear, plain-English briefing for a busy reader. Use this structure:

1. **What the report covers** (1-2 sentences — committee, scope, time period under review)
2. **Key findings / observations** (3-6 bullets — what the committee found, with figures where available)
3. **Recommendations** (3-6 bullets — what the committee recommends government do)
4. **Action Taken status** (1-2 sentences if this is an Action Taken Report — i.e. follow-up on earlier recommendations)
5. **Why it matters** (1-2 sentences — fiscal impact, accountability, oversight angle)

Keep it neutral, factual, and accessible to a non-specialist. Do not invent figures, ministries, or recommendations that aren't in the text.

REPORT:
{TEXT}`;

function buildAskPrompt({ summary, text, searchResults, question }) {
  const parts = [
    'You are answering questions about a specific Financial Committee report from the Indian Parliament. Use only the supplied material below. If the answer isn\'t in the supplied material, say so clearly.',
  ];
  if (summary) parts.push('', 'SUMMARY (previously generated by AI):', summary);
  parts.push('', 'REPORT:', text);
  if (searchResults && searchResults.length) {
    parts.push('', 'RECENT WEB CONTEXT (use cautiously, prefer the report itself when they conflict):');
    for (const r of searchResults) parts.push(`- ${r.title}\n  ${r.url}\n  ${r.snippet}`);
  }
  parts.push('', '---', '', 'QUESTION: ' + question);
  return parts.join('\n');
}

// ── Module-private state ────────────────────────────────────────────────────

const state = {
  // reports is a COMMITTEE-keyed dict: { pac: [reports...], estimates: [...], copu: [...] }
  data: { reports: {}, manifest: {}, meta: null },
  filtered: [],
  selectedReport: null,
  filters: { search: '', committee: '', lok_sabha: '', year: '', sort: 'ls_num_desc' },

  cache: {
    summaries: {},   // reportKey -> string
    text:      {},   // reportKey -> string (in-memory; IDB-backed)
    chats:     {},   // reportKey -> [{role, content, error?}]
  },

  dialogChat: [],

  searchBundle: null,
  bundleLoading: false,
  bundleLoaded:  false,

  searchIndex:  null,
  indexLoading: false,
  indexLoaded:  false,

  deepSearch: false,
  matchAny:   false,

  streamingContext: null,
};

let _deps = null;
let _activated = false;   // gates one-time setup

// ── Helpers ─────────────────────────────────────────────────────────────────

function reportKey(r) {
  return `fc|${r.committee}|${r.lok_sabha}|${r.report_number}`;
}

function parseDate(s) {
  if (!s) return null;
  // sansad.in dates are typically DD-Mon-YYYY ("17-Mar-2026") or
  // DD/MM/YYYY. Try both.
  const m1 = String(s).match(/^(\d{1,2})-([A-Za-z]+)-(\d{4})$/);
  if (m1) {
    const d = new Date(`${m1[2]} ${m1[1]}, ${m1[3]}`);
    if (!isNaN(d)) return d;
  }
  const m2 = String(s).match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
  if (m2) {
    const d = new Date(`${m2[3]}-${m2[2]}-${m2[1]}`);
    if (!isNaN(d)) return d;
  }
  const d3 = new Date(s);
  if (!isNaN(d3)) return d3;
  return null;
}

function reportDate(r) {
  return parseDate(r.presented_in_ls)
      || parseDate(r.laid_in_rs)
      || parseDate(r.date_of_presentation)
      || parseDate(r.date_of_adoption);
}

function reportYear(r) {
  const d = reportDate(r);
  return d ? d.getFullYear() : null;
}

function formatDate(d) {
  if (!d) return '—';
  return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

// ── Data fetching ───────────────────────────────────────────────────────────

async function fetchData(forceRefresh = false) {
  const splash    = document.getElementById('splash');
  const dataUrl   = _deps.config.dataBaseUrl;

  if (!forceRefresh) {
    try {
      const [reportsBlob, manifestBlob, metaBlob] = await Promise.all([
        idbGet('blobs', 'fc-reports.json'),
        idbGet('blobs', 'fc-manifest.json'),
        idbGet('blobs', 'fc-meta.json'),
      ]);
      if (reportsBlob && manifestBlob) {
        state.data.reports  = reportsBlob;
        state.data.manifest = manifestBlob;
        state.data.meta     = metaBlob || null;
      }
    } catch (e) { console.warn('FC IDB cache miss', e); }
  }

  const haveCache = Object.values(state.data.reports).some(v => Array.isArray(v) && v.length);
  const bucket = Math.floor(Date.now() / 300000);
  const v = forceRefresh ? `?v=${Date.now()}` : `?v=${bucket}`;
  const fetchOpts = { cache: 'no-cache' };

  try {
    const [reports, manifest, meta] = await Promise.all([
      fetch(dataUrl + CORPUS_PREFIX + 'reports.json'  + v, fetchOpts).then(r => r.ok ? r.json() : Promise.reject(`reports.json: ${r.status}`)),
      fetch(dataUrl + CORPUS_PREFIX + 'manifest.json' + v, fetchOpts).then(r => r.ok ? r.json() : { texts: {} }).catch(() => ({ texts: {} })),
      fetch(dataUrl + CORPUS_PREFIX + 'meta.json'     + v, fetchOpts).then(r => r.ok ? r.json() : null).catch(() => null),
    ]);
    state.data.reports  = reports;
    state.data.manifest = manifest;
    state.data.meta     = meta;

    idbPut('blobs', 'fc-reports.json',  reports).catch(() => {});
    idbPut('blobs', 'fc-manifest.json', manifest).catch(() => {});
    if (meta) idbPut('blobs', 'fc-meta.json', meta).catch(() => {});
  } catch (err) {
    console.error('FC fetch failed', err);
    if (!haveCache) {
      _deps.ui.toast('Could not fetch FC data — see console for details');
      return false;
    }
    _deps.ui.toast('FC offline — using cached data');
  }

  splash?.classList.add('hide');
  return true;
}

function fileId(r) {
  return `LS${r.lok_sabha}_${r.report_number}`;
}

async function fetchReportText(report) {
  const key = reportKey(report);
  if (state.cache.text[key]) return state.cache.text[key];

  try {
    const cached = await idbGet('texts', key);
    if (cached) {
      state.cache.text[key] = cached;
      return cached;
    }
  } catch {}

  const fid = fileId(report);
  const entry = state.data.manifest?.texts?.[report.committee]?.[fid];
  if (!entry) return null;
  try {
    const res = await fetch(_deps.config.dataBaseUrl + CORPUS_PREFIX + entry.url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const text = await res.text();
    state.cache.text[key] = text;
    idbPut('texts', key, text).catch(() => {});
    _deps.disk?.write?.('fc', entry.url, text).catch(() => {});
    return text;
  } catch (e) {
    try {
      const fromDisk = await _deps.disk?.read?.('fc', entry.url);
      if (fromDisk) {
        state.cache.text[key] = fromDisk;
        idbPut('texts', key, fromDisk).catch(() => {});
        return fromDisk;
      }
    } catch {}
    console.warn('FC: failed to fetch text', e);
    return null;
  }
}

// ── Filtering / list rendering ──────────────────────────────────────────────

function getAllReports() {
  // Flatten the committee-keyed dict to a single list, with each record
  // carrying its own `committee` field (already present in upstream data).
  const out = [];
  for (const cmt of Object.keys(COMMITTEES)) {
    for (const r of (state.data.reports[cmt] || [])) {
      out.push({ ...r, _date: reportDate(r), _year: reportYear(r) });
    }
  }
  return out;
}

function applyFilters() {
  const all = getAllReports();
  const f = state.filters;
  const rawQ = f.search.trim();
  const parsedQ = rawQ ? parseQuery(rawQ) : null;
  const bundle = state.searchBundle;

  const tokenIndexSets = parsedQ
    ? parsedQ.tokens.map(t => expandTokenToDocs(state.searchIndex, t))
    : [];

  const filtered = all.filter(r => {
    if (f.committee && r.committee !== f.committee) return false;
    if (f.lok_sabha && String(r.lok_sabha) !== f.lok_sabha) return false;
    if (f.year && String(r._year || '') !== f.year) return false;
    if (!parsedQ) return true;

    const key = reportKey(r);
    const titleLower  = (r.title || '').toLowerCase();
    const bundleEntry = bundle ? bundle.map.get(key) : null;
    const headLower   = bundleEntry ? bundleEntry.head.toLowerCase() : '';
    const cached      = state.cache.text[key];
    const cachedLower = cached ? cached.toLowerCase() : '';

    function tokenHits(tok, indexSet) {
      if (indexSet && indexSet.has(key)) return true;
      if (titleLower.includes(tok)) return true;
      if (headLower && headLower.includes(tok)) return true;
      if (cachedLower && cachedLower.includes(tok)) return true;
      return false;
    }
    function phraseHits(phrase) {
      if (titleLower.includes(phrase)) return true;
      if (headLower && headLower.includes(phrase)) return true;
      if (cachedLower && cachedLower.includes(phrase)) return true;
      return false;
    }

    if (state.matchAny) {
      const hit = parsedQ.tokens.some((t, i) => tokenHits(t, tokenIndexSets[i]))
              ||  parsedQ.phrases.some(phraseHits);
      if (!hit) return false;
    } else {
      if (!parsedQ.tokens.every((t, i) => tokenHits(t, tokenIndexSets[i]))) return false;
      if (!parsedQ.phrases.every(phraseHits)) return false;
    }
    return true;
  });

  filtered.sort((a, b) => {
    switch (f.sort) {
      case 'date_desc':    return (b._date || 0) - (a._date || 0);
      case 'date_asc':     return (a._date || 0) - (b._date || 0);
      case 'ls_num_asc':   return (a.lok_sabha - b.lok_sabha) || (a.report_number - b.report_number);
      case 'committee':    return (a.committee || '').localeCompare(b.committee || '')
                              || ((b.lok_sabha || 0) - (a.lok_sabha || 0))
                              || ((b.report_number || 0) - (a.report_number || 0));
      case 'ls_num_desc':
      default:             return ((b.lok_sabha || 0) - (a.lok_sabha || 0))
                              || ((b.report_number || 0) - (a.report_number || 0));
    }
  });

  state.filtered = filtered;
  renderList();
  renderResultsLine();
}

function renderResultsLine() {
  const el = document.getElementById('resultsLine');
  if (!el) return;
  const total = getAllReports().length;
  const shown = state.filtered.length;
  const meta = state.data.meta;
  let metaLine = '';
  if (meta?.generated_at) {
    metaLine = `Mirror updated <b>${escapeHtml(formatLocalTimestamp(meta.generated_at))}</b>`;
  }

  let indexLine = '';
  const bundle = state.searchBundle;
  const idx = state.searchIndex;
  const mirrorWithText = Object.values(state.data.manifest?.texts || {}).reduce(
    (n, byFid) => n + Object.keys(byFid || {}).length, 0);
  const loading = state.bundleLoading || state.indexLoading;
  if (loading) {
    const what = state.bundleLoading && state.indexLoading
      ? 'bundle + index'
      : state.bundleLoading ? 'bundle' : 'index';
    indexLine = `<span class="indexing">Loading search ${what}…</span>`;
  } else if (state.deepSearch && state.bundleLoaded && bundle) {
    const tooltip = idx
      ? `Search hits titles + first ${bundle.head_chars} chars of every report, plus body-token presence across the corpus.`
      : `Search hits titles + first ${bundle.head_chars} chars of every report.`;
    indexLine = `<span title="${escapeHtml(tooltip)}">Full-text search · ${bundle.total} reports</span>`
              + ` · <label class="match-any-toggle"><input type="checkbox" id="matchAnyToggle"${state.matchAny ? ' checked' : ''}>match any</label>`;
  } else if (mirrorWithText === 0) {
    indexLine = '';
  } else {
    indexLine = `<span>Title search only · <b>${mirrorWithText}</b> reports with text · <a href="#" id="enableDeepLink" style="color:var(--accent)">enable deep search</a></span>`;
  }
  el.innerHTML = `<div class="rl-primary">Showing <b>${shown}</b> of <b>${total}</b> Financial Committee reports. ${metaLine}</div>${indexLine ? `<div class="rl-secondary">${indexLine}</div>` : ''}`;

  const enableLink = document.getElementById('enableDeepLink');
  if (enableLink) {
    enableLink.addEventListener('click', (e) => {
      e.preventDefault();
      state.deepSearch = true;
      const s = loadSettings();
      s.fc_deepSearch = true;
      saveSettings(s);
      renderResultsLine();
      Promise.all([loadSearchBundle(), loadSearchIndex()]).then(() => {
        renderResultsLine();
        if (state.filters.search) applyFilters();
      });
    });
  }
  const matchAnyToggle = document.getElementById('matchAnyToggle');
  if (matchAnyToggle) {
    matchAnyToggle.addEventListener('change', (e) => {
      state.matchAny = !!e.target.checked;
      const s = loadSettings();
      s.fc_matchAny = state.matchAny;
      saveSettings(s);
      applyFilters();
    });
  }

  const sumBtn = document.getElementById('exportSummariesBtn');
  if (sumBtn) {
    const n = Object.keys(state.cache.summaries || {}).length;
    sumBtn.disabled = n === 0;
    sumBtn.textContent = n ? `⬇ Summaries (MD, ${n})` : '⬇ Summaries (MD)';
  }
}

function hasExtractedText(r) {
  const fid = fileId(r);
  return !!state.data.manifest?.texts?.[r.committee]?.[fid];
}
function hasSummary(r) {
  return !!state.cache.summaries[reportKey(r)];
}

function renderList() {
  const list = document.getElementById('reportsList');
  if (!list) return;
  if (!state.filtered.length) {
    list.innerHTML = `<div class="empty-state"><h3>No reports match</h3><p>Try clearing filters.</p></div>`;
    return;
  }
  const slice = state.filtered.slice(0, 200);
  const rawQ = state.filters.search.trim();
  const parsedQ = rawQ ? parseQuery(rawQ) : null;
  list.innerHTML = slice.map(r => {
    const titleHTML = parsedQ ? highlightMatches(r.title || '(untitled)', parsedQ)
                              : escapeHtml(r.title || '(untitled)');
    const cmt       = COMMITTEES[r.committee] || { short: '??', long: '?' };
    const cmtClass  = COMMITTEE_PILL_CLASS[r.committee] || 'ASSURE';
    const subline   = `Report #${r.report_number} · LS${r.lok_sabha} · ${escapeHtml(r.presented_in_ls || '—')}`;
    return `
      <div class="report-row" data-key="${escapeHtml(reportKey(r))}">
        <div>
          <div class="report-title">${titleHTML}</div>
          <div class="report-meta">${subline}</div>
        </div>
        <span class="cat-badge cat-${cmtClass}" title="${escapeHtml(cmt.long)}">${escapeHtml(cmt.short)}</span>
        <span class="report-meta">LS${r.lok_sabha}</span>
        <span class="text-status ${hasSummary(r) ? 'summary' : (hasExtractedText(r) ? 'ok' : '')}">
          ${hasSummary(r) ? 'summary' : (hasExtractedText(r) ? 'text' : 'metadata')}
        </span>
      </div>
    `;
  }).join('');
  if (state.filtered.length > 200) {
    list.insertAdjacentHTML('beforeend',
      `<div class="empty-state" style="padding:18px"><p>Showing first 200 of ${state.filtered.length} matches — refine filters to narrow further.</p></div>`);
  }
}

function renderHeaderStats() {
  const el = document.getElementById('headerStats');
  if (!el) return;
  const total = getAllReports().length;
  const withText = Object.values(state.data.manifest?.texts || {}).reduce(
    (n, byFid) => n + Object.keys(byFid || {}).length, 0);
  el.innerHTML = `
    <span><b>${total}</b> reports</span>
    <span><b>${withText}</b> with text</span>
  `;
}

function populateFilters() {
  const reports = getAllReports();
  const lsSet   = new Set();
  const yearSet = new Set();
  for (const r of reports) {
    if (r.lok_sabha != null) lsSet.add(r.lok_sabha);
    if (r._year) yearSet.add(r._year);
  }

  const cmtSel = document.getElementById('filterCommittee');
  if (cmtSel) {
    cmtSel.innerHTML = '<option value="">All committees</option>' +
      Object.entries(COMMITTEES).map(([k, c]) =>
        `<option value="${k}">${escapeHtml(c.long)}</option>`).join('');
  }
  const lsSel = document.getElementById('filterLokSabha');
  if (lsSel) {
    lsSel.innerHTML = '<option value="">All LS terms</option>' +
      [...lsSet].sort((a, b) => b - a).map(v =>
        `<option value="${v}">${v}th Lok Sabha</option>`).join('');
  }
  const yearSel = document.getElementById('filterYear');
  if (yearSel) {
    yearSel.innerHTML = '<option value="">All years</option>' +
      [...yearSet].sort((a, b) => b - a).map(v =>
        `<option value="${v}">${v}</option>`).join('');
  }

  if (cmtSel)  cmtSel.value  = state.filters.committee || '';
  if (lsSel)   lsSel.value   = state.filters.lok_sabha || '';
  if (yearSel) yearSel.value = state.filters.year      || '';
}

// ── Report dialog ───────────────────────────────────────────────────────────

function openReportByKey(key) {
  const all = getAllReports();
  const r = all.find(x => reportKey(x) === key);
  if (!r) return;
  if (_deps.ai.streaming() && state.streamingContext?.reportKey !== key) {
    _deps.ai.stop();
    state.streamingContext = null;
  }
  state.selectedReport = r;
  state.dialogChat = state.cache.chats[key] ? [...state.cache.chats[key]] : [];
  document.getElementById('reportTitle').textContent = r.title || '(untitled)';
  renderDetailsTab(r);
  switchReportTab('details');
  document.getElementById('reportModal').classList.add('open');
}

function renderDetailsTab(r) {
  const cmt = COMMITTEES[r.committee] || { short: '?', long: '?', type: '?' };
  document.getElementById('detailsTab').innerHTML = `
    <dl class="meta-grid">
      <dt>Title</dt><dd>${escapeHtml(r.title || '—')}</dd>
      <dt>Committee</dt><dd>${escapeHtml(cmt.long)} (${escapeHtml(cmt.type)})</dd>
      <dt>Report no.</dt><dd>${escapeHtml(String(r.report_number))}</dd>
      <dt>Lok Sabha</dt><dd>${escapeHtml(String(r.lok_sabha))}th</dd>
      ${r.presented_in_ls ? `<dt>Presented in LS</dt><dd>${escapeHtml(r.presented_in_ls)}</dd>` : ''}
      ${r.laid_in_rs ? `<dt>Laid in RS</dt><dd>${escapeHtml(r.laid_in_rs)}</dd>` : ''}
      ${r.date_of_adoption ? `<dt>Date of adoption</dt><dd>${escapeHtml(r.date_of_adoption)}</dd>` : ''}
      ${r.pdf_url ? `<dt>PDF</dt><dd><a href="${escapeHtml(r.pdf_url)}" target="_blank" rel="noopener">${escapeHtml(r.pdf_url.split('/').pop().split('?')[0])}</a></dd>` : ''}
      ${r.pdf_url_hindi ? `<dt>PDF (Hindi)</dt><dd><a href="${escapeHtml(r.pdf_url_hindi)}" target="_blank" rel="noopener">हिंदी</a></dd>` : ''}
      <dt>Source</dt><dd><a href="https://sansad.in/ls/committees" target="_blank" rel="noopener">sansad.in</a></dd>
    </dl>
    <p style="margin-top:14px; font-size:0.82rem; color:var(--muted)">
      ${hasExtractedText(r)
        ? 'Full text has been extracted by the mirror — see the "Full text" tab or generate an AI summary.'
        : 'Full text has not yet been extracted by the mirror. The daily Action picks reports up incrementally — check back, or open the PDF directly.'}
    </p>
  `;
}

async function loadTextTab() {
  const r = state.selectedReport;
  const tab = document.getElementById('textTab');
  if (!r) { tab.innerHTML = ''; return; }
  if (!hasExtractedText(r)) {
    tab.innerHTML = `<p>Full text hasn't been extracted yet. Open the PDF link from the Details tab.</p>`;
    return;
  }
  tab.innerHTML = `<p style="color:var(--muted)">Loading…</p>`;
  const text = await fetchReportText(r);
  if (!text) { tab.innerHTML = `<p>Could not load the extracted text.</p>`; return; }
  tab.innerHTML = `<pre>${escapeHtml(text)}</pre>`;
  renderList();
}

function switchReportTab(name) {
  // Multi-corpus guard — see CONV.md "Multi-corpus shared-DOM guard".
  if (_deps.activeCorpus?.() !== 'fc') return;
  document.querySelectorAll('#reportModal .tab-btn').forEach(b => b.classList.toggle('active', b.dataset.tab === name));
  document.querySelectorAll('#reportModal .tab-pane').forEach(p => p.classList.remove('active'));
  document.getElementById(name + 'Tab').classList.add('active');
  if (name === 'text')    loadTextTab();
  if (name === 'summary') renderSummaryTab();
  if (name === 'chat')    renderChatTab();
}

function renderSummaryTab() {
  const tab = document.getElementById('summaryTab');
  const r = state.selectedReport;
  if (!r) { tab.innerHTML = ''; return; }
  if (!_deps.ai.isUsable()) {
    tab.innerHTML = _deps.ai.notReadyHTML();
    _deps.ai.bindNotReadyCTA(tab);
    return;
  }
  const key = reportKey(r);
  const cached = state.cache.summaries[key];
  const isStreaming = state.streamingContext?.reportKey === key
                  &&  state.streamingContext?.tab === 'summary';

  if (isStreaming) {
    tab.innerHTML = `
      <div class="summary-actions">
        <span class="label">Generating summary… (streams in below)</span>
        <button class="ghost sm" id="stopSummaryBtn">Stop</button>
      </div>
      <div class="summary-box" id="summaryBox">${escapeHtml(cached || '')}</div>
    `;
    document.getElementById('stopSummaryBtn').addEventListener('click', () => {
      _deps.ai.stop();
      state.streamingContext = null;
    });
    return;
  }

  tab.innerHTML = `
    <div class="summary-actions">
      <span class="label">Generate a plain-English summary using your configured AI:</span>
      <button class="primary" id="generateSummaryBtn">${cached ? 'Regenerate' : 'Generate'}</button>
      <button class="ghost sm" id="copySummaryBtn" ${cached ? '' : 'style="display:none"'}>Copy</button>
    </div>
    <div class="summary-box" id="summaryBox">${cached ? escapeHtml(cached) : 'No summary yet.'}</div>
  `;
  document.getElementById('generateSummaryBtn').addEventListener('click', generateSummary);
  document.getElementById('copySummaryBtn').addEventListener('click', () => {
    navigator.clipboard.writeText(document.getElementById('summaryBox').textContent || '');
    _deps.ui.toast('Copied');
  });
}

function renderChatTab() {
  const tab = document.getElementById('chatTab');
  const r = state.selectedReport;
  if (!r) { tab.innerHTML = ''; return; }
  if (!_deps.ai.isUsable()) {
    tab.innerHTML = _deps.ai.notReadyHTML();
    _deps.ai.bindNotReadyCTA(tab);
    return;
  }
  const key = reportKey(r);
  const isStreaming = state.streamingContext?.reportKey === key
                  &&  state.streamingContext?.tab === 'chat';

  const messages = state.dialogChat.length
    ? state.dialogChat
    : [{ role: 'system', content: 'Ask anything about this Financial Committee report. Your question + the report text are sent to the AI you configured (local Gemma or BYOK).' }];

  const threadHTML = messages.map(m => {
    const cls = `chat-msg ${m.role}${m.error ? ' error' : ''}`;
    return `<div class="${cls}">${escapeHtml(m.content)}</div>`;
  }).join('');

  const searchOn = _deps.search.isConfigured();
  tab.innerHTML = `
    <div class="chat-thread" id="chatThread">${threadHTML}</div>
    <div class="chat-input-row">
      <textarea id="chatInput" rows="2" placeholder="Ask a question about this Financial Committee report..." ${isStreaming ? 'disabled' : ''}></textarea>
      ${searchOn ? `<button class="ghost sm" id="chatSearchSendBtn" title="Search the web AND Send" ${isStreaming ? 'disabled' : ''}>&#127760;</button>` : ''}
      <button class="primary" id="chatSendBtn" ${isStreaming ? 'disabled' : ''}>Send</button>
      <button class="ghost sm" id="chatStopBtn" ${isStreaming ? '' : 'style="display:none"'}>Stop</button>
    </div>
  `;
  document.getElementById('chatSendBtn').addEventListener('click', () => chatSend({}));
  if (searchOn) document.getElementById('chatSearchSendBtn').addEventListener('click', () => chatSend({ withSearch: true }));
  document.getElementById('chatStopBtn').addEventListener('click', () => {
    _deps.ai.stop();
    state.streamingContext = null;
  });
  document.getElementById('chatInput').addEventListener('keydown', e => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); chatSend({}); }
  });
  const t = document.getElementById('chatThread');
  if (t) t.scrollTop = t.scrollHeight;
}

function _truncateForContext(text) {
  const limit = _deps.ai.mode() === 'local' ? 12000 : 60000;
  if (text.length <= limit) return text;
  return text.slice(0, limit) + '\n\n[...truncated for context window...]';
}

async function generateSummary() {
  const r = state.selectedReport;
  if (!r) return;
  const text = await fetchReportText(r);
  if (!text) {
    _deps.ui.toast('Full text not available — extract pending');
    return;
  }
  const key = reportKey(r);
  const prompt = SUMMARY_PROMPT.replace('{TEXT}', _truncateForContext(text));
  const messages = [
    { role: 'system', content: 'You are a careful, accurate summariser of parliamentary financial-oversight reports.' },
    { role: 'user',   content: prompt },
  ];

  const previousCached = state.cache.summaries[key] || '';
  state.streamingContext = { reportKey: key, tab: 'summary' };
  renderSummaryTab();
  try {
    const result = await streamWithPersistence({
      generate: _deps.ai.generate,
      messages,
      onText: (full) => {
        if (state.streamingContext?.reportKey === key) {
          const box = document.getElementById('summaryBox');
          if (box) box.textContent = full;
        }
      },
    });
    if (result.ok) {
      state.cache.summaries[key] = result.text;
      idbPut('summaries', key, result.text).catch(() => {});
      if (_deps.disk?.saveAi?.() && _deps.disk?.isConnected?.()) {
        _deps.disk.write('fc', `ai/${r.committee}/${fileId(r)}.summary.md`, result.text).catch(() => {});
      }
    } else {
      state.cache.summaries[key] = previousCached;
      _deps.ui.toast('Summary generation failed: ' + result.error.message);
    }
  } finally {
    state.streamingContext = null;
    renderSummaryTab();
    renderList();
  }
}

async function chatSend(opts) {
  opts = opts || {};
  const r = state.selectedReport;
  if (!r) return;
  const input = document.getElementById('chatInput');
  const q = input.value.trim();
  if (!q) return;
  if (_deps.ai.streaming()) { _deps.ui.toast('Already responding…'); return; }
  const text = await fetchReportText(r);
  if (!text) { _deps.ui.toast('Full text not available'); return; }

  const k = reportKey(r);
  state.dialogChat.push({ role: 'user', content: q });
  try {
    let searchResults = null;
    if (opts.withSearch) {
      if (!_deps.search.isConfigured()) {
        state.dialogChat.push({ role: 'system', content: 'Web search not configured. Open Settings → Web search to add a provider.' });
        input.value = '';
        renderChatTab();
        return;
      }
      state.dialogChat.push({ role: 'system', content: `Searching the web for "${q}"…` });
      renderChatTab();
      try {
        searchResults = await _deps.search.run(q);
        const resultLine = searchResults.length
          ? `Found ${searchResults.length} result${searchResults.length === 1 ? '' : 's'}: ${searchResults.map(x => x.title).slice(0, 3).join(' · ')}${searchResults.length > 3 ? '…' : ''}`
          : 'No web results.';
        state.dialogChat[state.dialogChat.length - 1] = { role: 'system', content: resultLine };
      } catch (e) {
        state.dialogChat[state.dialogChat.length - 1] = { role: 'system', content: 'Search failed: ' + e.message };
        searchResults = null;
      }
    }
    state.dialogChat.push({ role: 'assistant', content: '' });
    state.streamingContext = { reportKey: reportKey(r), tab: 'chat' };
    input.value = '';
    renderChatTab();
    const summary = state.cache.summaries[reportKey(r)];
    const userPrompt = buildAskPrompt({
      summary: summary || null,
      text: _truncateForContext(text),
      searchResults,
      question: q,
    });
    const messages = [
      { role: 'system', content: 'You answer questions about Financial Committee reports from the Indian Parliament. Use only the supplied material. If the answer is not present, say so.' },
      { role: 'user',   content: userPrompt },
    ];
    const result = await streamWithPersistence({
      generate: _deps.ai.generate,
      messages,
      onText: (full) => {
        const last = state.dialogChat[state.dialogChat.length - 1];
        last.content = full;
        const lastEl = document.querySelector('#chatThread .chat-msg.assistant:last-child');
        if (lastEl) {
          lastEl.textContent = full;
          const t = document.getElementById('chatThread');
          if (t) t.scrollTop = t.scrollHeight;
        }
      },
    });
    const last = state.dialogChat[state.dialogChat.length - 1];
    if (result.ok) {
      last.content = result.text;
    } else {
      last.error = true;
      last.content = 'Error: ' + result.error.message;
    }
  } finally {
    state.streamingContext = null;
    renderChatTab();
    state.cache.chats[k] = [...state.dialogChat];
    idbPut('chats', k, state.dialogChat).catch(() => {});
    if (_deps.disk?.saveAi?.() && _deps.disk?.isConnected?.()) {
      _deps.disk.write('fc', `ai/${r.committee}/${fileId(r)}.chat.json`, JSON.stringify(state.dialogChat, null, 2)).catch(() => {});
    }
  }
}

// ── Search bundle + index ──────────────────────────────────────────────────

async function loadSearchBundle() {
  return sharedLoadSearchBundle({
    state, corpusId: 'fc',
    idbKey: 'fc-search-bundle.json',
    urlPath: CORPUS_PREFIX,
    meta: state.data.meta,
    deps: _deps,
    onChange: renderResultsLine,
    onAfterLoad: () => { if (state.filters.search) applyFilters(); },
  });
}

async function loadSearchIndex() {
  return sharedLoadSearchIndex({
    state, corpusId: 'fc',
    idbKey: 'fc-search-index.json',
    urlPath: CORPUS_PREFIX,
    meta: state.data.meta,
    deps: _deps,
    onChange: renderResultsLine,
    onAfterLoad: () => { if (state.filters.search) applyFilters(); },
  });
}

// ── Export ──────────────────────────────────────────────────────────────────

function _csvCell(v) {
  if (v == null) return '';
  const s = String(v);
  if (/[",\n\r]/.test(s)) return '"' + s.replace(/"/g, '""') + '"';
  return s;
}

function _downloadBlob(filename, mime, content) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  setTimeout(() => { URL.revokeObjectURL(url); a.remove(); }, 100);
}

function _ts() {
  const d = new Date();
  const pad = n => String(n).padStart(2, '0');
  return `${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}`;
}

function exportMetadataCSV() {
  const rows = state.filtered;
  if (!rows.length) { _deps.ui.toast('No reports to export'); return; }
  const headers = ['committee', 'lok_sabha', 'report_number', 'title',
    'presented_in_ls', 'laid_in_rs', 'date_of_adoption',
    'pdf_url', 'has_text', 'has_summary'];
  const lines = [headers.join(',')];
  for (const r of rows) {
    lines.push([
      r.committee, r.lok_sabha, r.report_number, r.title,
      r.presented_in_ls, r.laid_in_rs, r.date_of_adoption,
      r.pdf_url,
      hasExtractedText(r) ? 'yes' : 'no',
      hasSummary(r) ? 'yes' : 'no',
    ].map(_csvCell).join(','));
  }
  _downloadBlob(`sansadsaar-fc-metadata-${_ts()}.csv`, 'text/csv', lines.join('\n') + '\n');
  _deps.ui.toast(`Exported ${rows.length} Financial Committee reports`);
}

function exportSummariesMD() {
  const all = getAllReports();
  const out = [];
  out.push(`# SansadSaar — Financial Committee summaries`);
  out.push('');
  out.push(`Exported ${new Date().toLocaleString('en-IN')}. Source: <https://sansadsaar.naklitechie.com>.`);
  out.push('');
  let n = 0;
  for (const r of all) {
    const key = reportKey(r);
    const summary = state.cache.summaries[key];
    if (!summary) continue;
    n++;
    out.push('---');
    out.push('');
    const cmt = COMMITTEES[r.committee] || { long: r.committee };
    out.push(`## ${cmt.long} #${r.report_number} (LS${r.lok_sabha}) — ${r.title || '(untitled)'}`);
    out.push('');
    const meta = [r.presented_in_ls, r.laid_in_rs, r.date_of_adoption].filter(Boolean).join(' · ');
    if (meta) out.push(`*${meta}*`);
    if (r.pdf_url) out.push(`*PDF: <${r.pdf_url}>*`);
    out.push('');
    out.push(summary);
    out.push('');
  }
  if (!n) { _deps.ui.toast('No FC summaries cached yet'); return; }
  _downloadBlob(`sansadsaar-fc-summaries-${_ts()}.md`, 'text/markdown', out.join('\n'));
  _deps.ui.toast(`Exported ${n} summaries`);
}

// ── IDB hydration ──────────────────────────────────────────────────────────

const _matchFcKey = (k) => k.startsWith('fc|');

async function loadCachedSummaries() {
  // Caller gates renderList() on !silent — see drsc/index.js loadCachedSummaries
  // for rationale (silent cross-corpus preloads must not touch visible DOM).
  await hydrateFromIDB({ store: 'summaries', target: state.cache.summaries, matches: _matchFcKey });
}
async function loadCachedChats() {
  await hydrateFromIDB({ store: 'chats', target: state.cache.chats, matches: _matchFcKey });
}
async function loadCachedTexts() {
  const { added } = await hydrateFromIDB({ store: 'texts', target: state.cache.text, matches: _matchFcKey });
  return added;
}

// ── Filter row + handlers ──────────────────────────────────────────────────

function renderFilterRow() {
  const container = document.getElementById('filtersContainer');
  if (!container) return;
  container.innerHTML = `
    <input type="search" id="filterSearch" placeholder="Search Financial Committee reports..." autocomplete="off">
    <select id="filterCommittee"><option value="">All committees</option></select>
    <select id="filterLokSabha"><option value="">All LS terms</option></select>
    <select id="filterYear"><option value="">All years</option></select>
    <select id="filterSort">
      <option value="ls_num_desc">LS + report no. (high→low)</option>
      <option value="ls_num_asc">LS + report no. (low→high)</option>
      <option value="date_desc">Date presented (newest first)</option>
      <option value="date_asc">Date presented (oldest first)</option>
      <option value="committee">Group by committee</option>
    </select>
    <button class="ghost sm" id="resetFiltersBtn" title="Reset filters">&times;</button>
  `;
  document.getElementById('filterSearch').value = state.filters.search || '';
  document.getElementById('filterSort').value   = state.filters.sort   || 'ls_num_desc';
}

function attachHandlers() {
  const debouncedSearch = debounce(() => { state.filters.search = document.getElementById('filterSearch').value; applyFilters(); }, 200);
  document.getElementById('filterSearch').addEventListener('input', debouncedSearch);
  document.getElementById('filterCommittee').addEventListener('change', e => { state.filters.committee = e.target.value; applyFilters(); });
  document.getElementById('filterLokSabha').addEventListener('change',  e => { state.filters.lok_sabha = e.target.value; applyFilters(); });
  document.getElementById('filterYear').addEventListener('change',      e => { state.filters.year      = e.target.value; applyFilters(); });
  document.getElementById('filterSort').addEventListener('change',      e => { state.filters.sort      = e.target.value; applyFilters(); });
  document.getElementById('resetFiltersBtn').addEventListener('click', () => {
    state.filters = { search: '', committee: '', lok_sabha: '', year: '', sort: 'ls_num_desc' };
    document.getElementById('filterSearch').value    = '';
    document.getElementById('filterCommittee').value = '';
    document.getElementById('filterLokSabha').value  = '';
    document.getElementById('filterYear').value      = '';
    document.getElementById('filterSort').value      = 'ls_num_desc';
    applyFilters();
  });

  document.getElementById('reportsList').addEventListener('click', e => {
    const row = e.target.closest('.report-row');
    if (row) openReportByKey(row.dataset.key);
  });

  document.querySelectorAll('#reportModal .tab-btn').forEach(b => {
    if (b.dataset._fcWired) return;
    b.dataset._fcWired = '1';
    b.addEventListener('click', () => switchReportTab(b.dataset.tab));
  });
  const closeBtn = document.getElementById('reportCloseBtn');
  if (closeBtn && !closeBtn.dataset._fcWired) {
    closeBtn.dataset._fcWired = '1';
    closeBtn.addEventListener('click', () => _deps.ui.closeModal('reportModal'));
  }

  const exportMeta = document.getElementById('exportMetaBtn');
  const exportSum  = document.getElementById('exportSummariesBtn');
  if (exportMeta) exportMeta.onclick = exportMetadataCSV;
  if (exportSum)  exportSum.onclick  = exportSummariesMD;
}

// ── Activation / lifecycle ──────────────────────────────────────────────────

async function activate(deps, { silent = false } = {}) {
  _deps = deps;

  if (!silent) {
    renderFilterRow();
    attachHandlers();
  }

  if (!_activated) {
    _activated = true;

    const settings = loadSettings();
    state.deepSearch = !!settings.fc_deepSearch;
    state.matchAny   = !!settings.fc_matchAny;

    const ok = await fetchData();
    if (!ok) return false;

    if (!silent) {
      populateFilters();
      renderHeaderStats();
      applyFilters();
    }

    loadCachedSummaries().then(() => { if (!silent) renderList(); });
    loadCachedChats();
    loadCachedTexts().then((n) => {
      if (n && !silent) {
        renderList();
        renderResultsLine();
      }
      if (state.deepSearch) {
        loadSearchBundle();
        loadSearchIndex();
      }
    });
  } else if (!silent) {
    populateFilters();
    renderHeaderStats();
    applyFilters();
  }

  return true;
}

function refreshAIDependentTabs() {
  if (!state.selectedReport) return;
  const sumActive  = document.getElementById('summaryTab')?.classList.contains('active');
  const chatActive = document.getElementById('chatTab')?.classList.contains('active');
  if (sumActive)  renderSummaryTab();
  if (chatActive) renderChatTab();
}

// ── Settings section ───────────────────────────────────────────────────────

function renderSettingsSection(container) {
  const meta = state.data.meta;
  const bundle = state.searchBundle;
  const indexStats = meta?.search_index;
  const bundleStats = meta?.search_bundle;

  let estimateLine;
  if (state.bundleLoaded && state.indexLoaded && bundle && state.searchIndex) {
    estimateLine = `Search bundle + body index loaded: ${bundle.total} reports, ${state.searchIndex.vocab_size.toLocaleString()} tokens indexed.`;
  } else if (state.bundleLoaded && bundle) {
    estimateLine = `Bundle loaded (${bundle.total} reports). Body index will load next.`;
  } else if (bundleStats?.size_bytes && indexStats?.size_bytes) {
    const totalMB = ((bundleStats.size_bytes + indexStats.size_bytes) / (1024 * 1024)).toFixed(1);
    estimateLine = `~${totalMB} MB total across all FC shards (CF gzip serves ~30%, cached locally after).`;
  } else {
    estimateLine = `Sharded download, cached locally after first load.`;
  }

  container.innerHTML = `
    <div class="settings-section">
      <h3>Search (Financial Committees)</h3>
      <p>Enable deep search to fetch the FC bundle (title + first 5K chars per report) and body index — both cached locally after first load. Search semantics + match-any toggle work the same as for other corpora.</p>
      <div class="settings-row">
        <label for="fcDeepSearch">Deep search</label>
        <div>
          <label style="display:inline-flex; align-items:center; gap:6px; font-size:0.86rem; color:var(--text)">
            <input type="checkbox" id="fcDeepSearch" ${state.deepSearch ? 'checked' : ''} style="width:auto"> Enable full-text search across Financial Committee reports
          </label>
          <p style="font-size:0.78rem; color:var(--muted); margin-top:4px">${escapeHtml(estimateLine)}</p>
        </div>
      </div>
    </div>

    <div class="settings-section">
      <h3>Data (Financial Committees)</h3>
      <p id="fcDataInfo">${meta
        ? `Last updated ${escapeHtml(meta.generated_at)} · ${escapeHtml(String(meta.total_reports))} reports total · ${escapeHtml(String(meta.total_with_text))} with text · LSes ${escapeHtml((meta.lok_sabhas || []).join(', '))}`
        : `Source: ${escapeHtml(_deps?.config?.dataBaseUrl || '')}fc/`}</p>
      <button class="sm" id="fcRefreshDataBtn">Refresh from mirror</button>
    </div>
  `;

  document.getElementById('fcRefreshDataBtn').addEventListener('click', async () => {
    _deps.ui.toast('Refreshing FC…');
    await fetchData(true);
    populateFilters();
    renderHeaderStats();
    applyFilters();
    _deps.broadcast('fc:data-refreshed');
    renderSettingsSection(container);
    _deps.ui.toast('FC data refreshed');
  });
}

function applySettingsFromUI() {
  const wasDeep = state.deepSearch;
  const cbox = document.getElementById('fcDeepSearch');
  if (cbox) state.deepSearch = !!cbox.checked;
  const s = loadSettings();
  s.fc_deepSearch = state.deepSearch;
  saveSettings(s);
  if (state.deepSearch && !wasDeep) {
    loadSearchBundle();
    loadSearchIndex();
  }
}

// ── Status (per-corpus pill) ───────────────────────────────────────────────

async function fetchStatus() {
  const meta = state.data.meta;
  const withText = Object.values(state.data.manifest?.texts || {}).reduce(
    (n, byFid) => n + Object.keys(byFid || {}).length, 0);
  if (!meta) return { lastUpdate: null, items: getAllReports().length, withText, error: null };
  return {
    lastUpdate: meta.generated_at || null,
    items: meta.total_reports || getAllReports().length,
    withText,
    error: null,
  };
}

// ── JS API surface ─────────────────────────────────────────────────────────

const api = {
  list({ committee, lok_sabha, year } = {}) {
    return getAllReports().filter(r => {
      if (committee && r.committee !== committee) return false;
      if (lok_sabha != null && String(r.lok_sabha) !== String(lok_sabha)) return false;
      if (year != null && String(r._year) !== String(year)) return false;
      return true;
    });
  },
  get(key) {
    return getAllReports().find(r => reportKey(r) === key) || null;
  },
  async search(query, opts = {}) {
    if (opts.deep && (!state.bundleLoaded || !state.indexLoaded)) {
      state.deepSearch = true;
      await Promise.all([loadSearchBundle(), loadSearchIndex()]);
    }
    const parsedQ = parseQuery(query);
    if (!parsedQ.tokens.length && !parsedQ.phrases.length) return getAllReports();
    const bundle = state.searchBundle;
    const tokenIndexSets = parsedQ.tokens.map(t => expandTokenToDocs(state.searchIndex, t));
    const anyMode = !!opts.any;
    return getAllReports().filter(r => {
      const key = reportKey(r);
      const titleLower  = (r.title || '').toLowerCase();
      const bundleEntry = bundle ? bundle.map.get(key) : null;
      const headLower   = bundleEntry ? bundleEntry.head.toLowerCase() : '';
      const cached      = state.cache.text[key];
      const cachedLower = cached ? cached.toLowerCase() : '';
      const tokHit = (t, idxSet) => (idxSet && idxSet.has(key))
        || titleLower.includes(t)
        || (headLower && headLower.includes(t))
        || (cachedLower && cachedLower.includes(t));
      const phHit = p => titleLower.includes(p)
        || (headLower && headLower.includes(p))
        || (cachedLower && cachedLower.includes(p));
      if (anyMode) {
        return parsedQ.tokens.some((t, i) => tokHit(t, tokenIndexSets[i]))
            || parsedQ.phrases.some(phHit);
      }
      return parsedQ.tokens.every((t, i) => tokHit(t, tokenIndexSets[i]))
          && parsedQ.phrases.every(phHit);
    });
  },
  open(key) {
    const r = api.get(key);
    if (!r) return false;
    openReportByKey(reportKey(r));
    return true;
  },
  async searchForGlobal(query, { deep = true, limit = 10 } = {}) {
    const items = await api.search(query, { deep });
    const subs = (r) => {
      const parts = [];
      const cmt = COMMITTEES[r.committee];
      if (cmt) parts.push(cmt.short);
      parts.push(`LS${r.lok_sabha}`);
      parts.push(`#${r.report_number}`);
      return parts.join(' · ');
    };
    return items.slice(0, limit).map(r => ({
      key:      reportKey(r),
      title:    r.title || '(untitled)',
      subtitle: subs(r),
    }));
  },
  committees: () => Object.keys(COMMITTEES),
};

// ── Export the corpus contract ─────────────────────────────────────────────

export const FCCorpus = {
  id:          'fc',
  label:       'Financial Committees',
  shortLabel:  'FC',
  macroGroup:  'oversight',
  primaryUnit: 'report',

  fetchStatus,
  activate,

  api,
  renderSettingsSection,
  applySettingsFromUI,
  refreshAIDependentTabs,
};
