// app/corpora/gazettes/index.js
// Central Gazette of India — Weekly + Extraordinary notifications.
// ~170K records target across 1947→present. Records served from
// sansadsaar-gazettes (separate CF Pages project) per the 2026-05-14
// repo split. PDFs served directly from archive.org.
//
// Eighth registered corpus. Structurally mirrors the CAG module
// (flat reportKey shape, sharded reports fetch from debates module).
// Macro group: `executive` — first corpus in that group; future state
// gazettes (if added) would join.
//
// reportKey shape: `gazettes|central|<e|w>|<YYYY-MM-DD>|<ugid>`.
// composite_id used in text shards: `central|<file_id>` where
// file_id = `central_<e|w>_<YYYYMMDD>_<ugid>`.

import {
  idbGet, idbPut, idbCursor,
  escapeHtml, debounce,
  loadSettings, saveSettings,
  formatLocalTimestamp,
} from '../../deps.js';
import { streamWithPersistence } from '../../ai-streaming.js';
import {
  parseQuery, highlightMatches,
  loadSearchBundle as sharedLoadSearchBundle,
  loadSearchIndex  as sharedLoadSearchIndex,
  expandTokenToDocs,
} from '../../corpus-search.js';
import { hydrateFromIDB } from '../../corpus-data.js';
import { loadTextFromShards } from '../../text-shards.js';

const CORPUS_PREFIX = 'gazettes/';

// ── Constants ───────────────────────────────────────────────────────────────

// Display labels + colour-class mapping. Reuses the existing house-pill /
// cat-badge CSS classes so no new CSS is needed.
const CATEGORY_SHORT = {
  'extraordinary': 'EX',
  'weekly':        'WK',
};
const CATEGORY_PILL = {            // -> house-pill class suffix
  'extraordinary': 'R',            // navy (denser, more numerous)
  'weekly':        'L',            // orange
};

// language combos for the cat-badge
const LANG_INFO = {
  'eng':      { short: 'EN',     class: 'DFG',     label: 'English' },
  'hin':      { short: 'HI',     class: 'AT',      label: 'Hindi' },
  'eng+hin':  { short: 'EN+HI',  class: 'SUBJ',    label: 'English + Hindi' },
};
const DEFAULT_LANG = { short: '?', class: 'ASSURE', label: 'Language unknown' };

const SUMMARY_PROMPT = `You are summarising a notification from the Central Gazette of India. The text below is one extraordinary or weekly gazette notification (typically a rule, order, appointment, amendment, tariff change, or similar government action). Produce a clear, plain-English briefing for a busy reader. Use this structure:

1. **What this is** (1 sentence — type of action, issuing ministry, date)
2. **What it does** (3-5 bullets — the substantive provisions)
3. **Who it affects** (1-2 sentences — affected entities, regions, industries)
4. **Why it matters** (1-2 sentences — policy / legal / fiscal significance, if any)

Keep it neutral, factual, and accessible to a non-specialist. Don't invent specifics not in the text. If the notification is bilingual (English + Hindi side-by-side), summarise once — the languages mirror each other.

NOTIFICATION:
{TEXT}`;

function buildAskPrompt({ summary, text, searchResults, question }) {
  const parts = [
    'You are answering questions about a specific Central Gazette notification from the Government of India. Use only the supplied material below to answer. If the answer isn\'t in the supplied material, say so clearly.',
  ];
  if (summary) parts.push('', 'SUMMARY (previously generated by AI):', summary);
  parts.push('', 'NOTIFICATION:', text);
  if (searchResults && searchResults.length) {
    parts.push('', 'RECENT WEB CONTEXT (use cautiously, prefer the notification itself when they conflict):');
    for (const r of searchResults) parts.push(`- ${r.title}\n  ${r.url}\n  ${r.snippet}`);
  }
  parts.push('', '---', '', 'QUESTION: ' + question);
  return parts.join('\n');
}

// ── Module-private state ────────────────────────────────────────────────────

const state = {
  // reports is a FLAT dict keyed by id-as-string (different from DRSC's
  // Records arrive sharded (reports-central-NN.json); we flatten into
  // a single array on load. Schema per record: identifier, category,
  // type_letter, issue_date, ugid, ministry, department, subject,
  // gazette_id, gazette_source_url, languages[], pdf_url, topics[].
  data: { reports: [], manifest: {}, meta: null },
  filtered: [],
  selectedReport: null,
  filters: { search: '', category: '', ministry: '', year: '', language: '', sort: 'date_desc' },

  cache: {
    summaries: {},   // reportKey -> string
    text:      {},   // reportKey -> string (in-memory; IDB-backed)
    chats:     {},   // reportKey -> [{role, content, error?}]
  },

  dialogChat: [],

  searchBundle: null,
  bundleLoading: false,
  bundleLoaded:  false,

  searchIndex:  null,
  indexLoading: false,
  indexLoaded:  false,

  deepSearch: false,
  matchAny:   false,

  streamingContext: null,
};

let _deps = null;
let _activated = false;   // gates one-time setup; activate() can re-run cheaply

// ── Helpers ─────────────────────────────────────────────────────────────────

function reportKey(r) {
  return `gazettes|central|${r.type_letter}|${r.issue_date}|${r.ugid}`;
}

// Composite id used in the text shards' record_to_shard map. Mirrors
// build_gazettes.py's file_id() format: `central_<e|w>_<YYYYMMDD>_<ugid>`.
function fileId(r) {
  const date_compact = (r.issue_date || '').replace(/-/g, '');
  return `central_${r.type_letter}_${date_compact}_${r.ugid}`;
}

function reportDate(r) {
  // Gazette issue_date is always ISO YYYY-MM-DD from build_gazettes.py.
  if (!r.issue_date) return null;
  const d = new Date(r.issue_date);
  return isNaN(d) ? null : d;
}

function reportYear(r) {
  if (r.issue_date) {
    const y = parseInt(r.issue_date.slice(0, 4), 10);
    if (!isNaN(y)) return y;
  }
  return null;
}

function formatDate(d) {
  if (!d) return '—';
  return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

function categoryLabel(r) {
  if (r.category === 'extraordinary') return 'Extraordinary';
  if (r.category === 'weekly') return 'Weekly';
  return r.category || '?';
}

function languageKey(r) {
  const langs = r.languages || [];
  if (langs.length === 0) return '?';
  if (langs.includes('eng') && langs.includes('hin')) return 'eng+hin';
  return langs[0];
}

function langInfo(r) {
  return LANG_INFO[languageKey(r)] || DEFAULT_LANG;
}

// ── Data fetching ───────────────────────────────────────────────────────────

// Sharded reports loader. The gazettes index emits reports-meta.json
// (manifest) + reports-central-NN.json (records). Returns a flat array.
async function fetchReports(dataUrl, v, fetchOpts) {
  const metaResp = await fetch(dataUrl + CORPUS_PREFIX + 'reports-meta.json' + v, fetchOpts);
  if (!metaResp.ok) throw new Error(`reports-meta.json: ${metaResp.status}`);
  const reportsMeta = await metaResp.json();
  const shards = (reportsMeta?.shards?.central) || [];
  const tasks = shards.map(entry =>
    fetch(dataUrl + CORPUS_PREFIX + entry.file + v, fetchOpts)
      .then(r => {
        if (!r.ok) throw new Error(`${entry.file}: ${r.status}`);
        return r.json();
      })
      .then(payload => ({ idx: payload?.shard_index ?? 0, records: payload?.records || [] }))
  );
  const shardResults = await Promise.all(tasks);
  shardResults.sort((a, b) => a.idx - b.idx);
  const merged = [];
  for (const { records } of shardResults) merged.push(...records);
  return merged;
}

async function fetchData(forceRefresh = false) {
  const splash    = document.getElementById('splash');   // shared with shell
  const splashErr = document.getElementById('splashError');
  const dataUrl   = _deps.config.dataBaseUrl;

  if (!forceRefresh) {
    try {
      const [reportsBlob, manifestBlob, metaBlob] = await Promise.all([
        idbGet('blobs', 'gazettes-reports.json'),
        idbGet('blobs', 'gazettes-manifest.json'),
        idbGet('blobs', 'gazettes-meta.json'),
      ]);
      if (reportsBlob && manifestBlob) {
        state.data.reports  = reportsBlob;
        state.data.manifest = manifestBlob;
        state.data.meta     = metaBlob || null;
      }
    } catch (e) { console.warn('gazettes IDB cache miss', e); }
  }

  const haveCache = Array.isArray(state.data.reports) && state.data.reports.length > 0;
  const bucket = Math.floor(Date.now() / 300000);
  const v = forceRefresh ? `?v=${Date.now()}` : `?v=${bucket}`;
  const fetchOpts = { cache: 'no-cache' };

  try {
    const [reports, manifest, meta] = await Promise.all([
      fetchReports(dataUrl, v, fetchOpts),
      fetch(dataUrl + CORPUS_PREFIX + 'manifest.json' + v, fetchOpts).then(r => r.ok ? r.json() : { texts: {} }).catch(() => ({ texts: {} })),
      fetch(dataUrl + CORPUS_PREFIX + 'meta.json'     + v, fetchOpts).then(r => r.ok ? r.json() : null).catch(() => null),
    ]);
    state.data.reports  = reports;
    state.data.manifest = manifest;
    state.data.meta     = meta;

    idbPut('blobs', 'gazettes-reports.json',  reports).catch(() => {});
    idbPut('blobs', 'gazettes-manifest.json', manifest).catch(() => {});
    if (meta) idbPut('blobs', 'gazettes-meta.json', meta).catch(() => {});
  } catch (err) {
    console.error('gazettes fetch failed', err);
    if (!haveCache) {
      _deps.ui.toast('Could not fetch Gazettes data — see console for details');
      return false;
    }
    _deps.ui.toast('Gazettes offline — using cached data');
  }

  splash?.classList.add('hide');
  return true;
}

async function fetchReportText(report) {
  const key = reportKey(report);
  if (state.cache.text[key]) return state.cache.text[key];

  try {
    const cached = await idbGet('texts', key);
    if (cached) {
      state.cache.text[key] = cached;
      return cached;
    }
  } catch {}

  // Gazettes always uses bundled text-shards. Composite key in the
  // shards is `central|<file_id>` (build_gazettes.py prefixes with
  // category, not corpus, because future state-gazette categories
  // could share the same shard set conceptually).
  const fid = fileId(report);
  const compositeKey = `central|${fid}`;
  try {
    const text = await loadTextFromShards('gazettes', compositeKey, _deps.config.dataBaseUrl);
    if (text !== null) {
      state.cache.text[key] = text;
      idbPut('texts', key, text).catch(() => {});
      _deps.disk?.write?.('gazettes', `text/${fid}.txt`, text).catch(() => {});
      return text;
    }
  } catch (e) {
    console.warn('gazettes: text-shard fetch failed', e);
  }

  // Offline fallback: disk-saved copy from a previous online session.
  try {
    const fromDisk = await _deps.disk?.read?.('gazettes', `text/${fid}.txt`);
    if (fromDisk) {
      state.cache.text[key] = fromDisk;
      idbPut('texts', key, fromDisk).catch(() => {});
      return fromDisk;
    }
  } catch {}
  return null;
}

// ── Filtering / list rendering ──────────────────────────────────────────────

function getAllReports() {
  return (Array.isArray(state.data.reports) ? state.data.reports : []).map(r => ({
    ...r,
    _date: reportDate(r),
    _year: reportYear(r),
    _langInfo: langInfo(r),
  }));
}

function applyFilters() {
  const all = getAllReports();
  const f = state.filters;
  const rawQ = f.search.trim();
  const parsedQ = rawQ ? parseQuery(rawQ) : null;
  const bundle = state.searchBundle;

  const tokenIndexSets = parsedQ
    ? parsedQ.tokens.map(t => expandTokenToDocs(state.searchIndex, t))
    : [];

  const filtered = all.filter(r => {
    if (f.category && r.category !== f.category) return false;
    if (f.ministry && r.ministry !== f.ministry) return false;
    if (f.year && String(r._year || '') !== f.year) return false;
    if (f.language && languageKey(r) !== f.language) return false;
    if (!parsedQ) return true;

    const key = reportKey(r);
    // Subject is the closest analogue to "title". Plus ministry + department.
    const subjectLower  = (r.subject || '').toLowerCase();
    const ministryLower = (r.ministry || '').toLowerCase();
    const deptLower     = (r.department || '').toLowerCase();
    const bundleEntry = bundle ? bundle.map.get(key) : null;
    const headLower   = bundleEntry ? bundleEntry.head.toLowerCase() : '';
    const cached      = state.cache.text[key];
    const cachedLower = cached ? cached.toLowerCase() : '';

    function tokenHits(tok, indexSet) {
      if (indexSet && indexSet.has(key)) return true;
      if (subjectLower.includes(tok)) return true;
      if (ministryLower.includes(tok)) return true;
      if (deptLower.includes(tok)) return true;
      if (headLower && headLower.includes(tok)) return true;
      if (cachedLower && cachedLower.includes(tok)) return true;
      return false;
    }
    function phraseHits(phrase) {
      if (subjectLower.includes(phrase)) return true;
      if (ministryLower.includes(phrase)) return true;
      if (deptLower.includes(phrase)) return true;
      if (headLower && headLower.includes(phrase)) return true;
      if (cachedLower && cachedLower.includes(phrase)) return true;
      return false;
    }

    if (state.matchAny) {
      const hit = parsedQ.tokens.some((t, i) => tokenHits(t, tokenIndexSets[i]))
              ||  parsedQ.phrases.some(phraseHits);
      if (!hit) return false;
    } else {
      if (!parsedQ.tokens.every((t, i) => tokenHits(t, tokenIndexSets[i]))) return false;
      if (!parsedQ.phrases.every(phraseHits)) return false;
    }
    return true;
  });

  filtered.sort((a, b) => {
    switch (f.sort) {
      case 'date_asc':  return (a._date || 0) - (b._date || 0);
      case 'ugid_desc': return parseInt(b.ugid || '0', 10) - parseInt(a.ugid || '0', 10);
      case 'ugid_asc':  return parseInt(a.ugid || '0', 10) - parseInt(b.ugid || '0', 10);
      case 'date_desc':
      default:          return (b._date || 0) - (a._date || 0);
    }
  });

  state.filtered = filtered;
  renderList();
  renderResultsLine();
}

function renderResultsLine() {
  const el = document.getElementById('resultsLine');
  if (!el) return;
  const total = getAllReports().length;
  const shown = state.filtered.length;
  const meta = state.data.meta;
  let metaLine = '';
  if (meta?.generated_at) {
    metaLine = `Mirror updated <b>${escapeHtml(formatLocalTimestamp(meta.generated_at))}</b>`;
  }

  let indexLine = '';
  const bundle = state.searchBundle;
  const idx = state.searchIndex;
  const mirrorWithText = Object.keys(state.data.manifest?.texts || {}).length;
  const loading = state.bundleLoading || state.indexLoading;
  if (loading) {
    const what = state.bundleLoading && state.indexLoading
      ? 'bundle + index'
      : state.bundleLoading ? 'bundle' : 'index';
    indexLine = `<span class="indexing">Loading search ${what}…</span>`;
  } else if (state.deepSearch && state.bundleLoaded && bundle) {
    const tooltip = idx
      ? `Search hits titles + first ${bundle.head_chars} chars of every report, plus body-token presence across the corpus.`
      : `Search hits titles + first ${bundle.head_chars} chars of every report.`;
    indexLine = `<span title="${escapeHtml(tooltip)}">Full-text search · ${bundle.total} reports</span>`
              + ` · <label class="match-any-toggle"><input type="checkbox" id="matchAnyToggle"${state.matchAny ? ' checked' : ''}>match any</label>`;
  } else if (mirrorWithText === 0) {
    indexLine = '';
  } else {
    indexLine = `<span>Title search only · <b>${mirrorWithText}</b> reports with text · <a href="#" id="enableDeepLink" style="color:var(--accent)">enable deep search</a></span>`;
  }
  el.innerHTML = (shown > 0 && shown < total)
    ? `<div class="rl-primary">Showing <b>${shown}</b> of <b>${total}</b></div>`
    : '';

  const enableLink = document.getElementById('enableDeepLink');
  if (enableLink) {
    enableLink.addEventListener('click', (e) => {
      e.preventDefault();
      state.deepSearch = true;
      const s = loadSettings();
      s.gazettes_deepSearch = true;
      saveSettings(s);
      renderResultsLine();
      Promise.all([loadSearchBundle(), loadSearchIndex()]).then(() => {
        renderResultsLine();
        if (state.filters.search) applyFilters();
      });
    });
  }
  const matchAnyToggle = document.getElementById('matchAnyToggle');
  if (matchAnyToggle) {
    matchAnyToggle.addEventListener('change', (e) => {
      state.matchAny = !!e.target.checked;
      const s = loadSettings();
      s.gazettes_matchAny = state.matchAny;
      saveSettings(s);
      applyFilters();
    });
  }

  const sumBtn = document.getElementById('exportSummariesBtn');
  if (sumBtn) {
    const n = Object.keys(state.cache.summaries || {}).length;
    sumBtn.disabled = n === 0;
    sumBtn.textContent = n ? `⬇ Summaries (MD, ${n})` : '⬇ Summaries (MD)';
  }
}

// Bundled-records signal: a record has text if its composite id is in
// the manifest's texts map (build_gazettes derive populates this from
// the texts-meta.json record_to_shard).
function hasExtractedText(r) {
  return !!state.data.manifest?.texts?.[`central|${fileId(r)}`];
}
function hasSummary(r) {
  return !!state.cache.summaries[reportKey(r)];
}

function renderList() {
  const list = document.getElementById('reportsList');
  if (!list) return;
  if (!state.filtered.length) {
    list.innerHTML = `<div class="empty-state"><h3>No notifications match</h3><p>Try clearing filters.</p></div>`;
    return;
  }
  const slice = state.filtered.slice(0, 200);
  const rawQ = state.filters.search.trim();
  const parsedQ = rawQ ? parseQuery(rawQ) : null;
  list.innerHTML = slice.map(r => {
    const subjectHTML = parsedQ ? highlightMatches(r.subject || '(untitled)', parsedQ)
                                : escapeHtml(r.subject || '(untitled)');
    const catShort  = CATEGORY_SHORT[r.category] || '?';
    const catPill   = CATEGORY_PILL[r.category]  || 'L';
    const li        = r._langInfo;
    const subline   = [r.ministry, r.department].filter(Boolean).join(' · ')
                    + (r.gazette_id ? ` · ${r.gazette_id}` : '');
    const dateStr   = formatDate(r._date);
    return `
      <div class="report-row" data-key="${escapeHtml(reportKey(r))}">
        <div>
          <div class="report-title">${subjectHTML}</div>
          <div class="report-meta">${escapeHtml(subline) || '—'}</div>
        </div>
        <span class="house-pill house-${catPill}" title="${escapeHtml(categoryLabel(r))} Gazette">${escapeHtml(catShort)}</span>
        <span class="cat-badge cat-${li.class}" title="${escapeHtml(li.label)}">${escapeHtml(li.short)}</span>
        <span class="report-meta">${escapeHtml(dateStr)}</span>
        <span class="text-status ${hasSummary(r) ? 'summary' : (hasExtractedText(r) ? 'ok' : '')}">
          ${hasSummary(r) ? 'summary' : (hasExtractedText(r) ? 'text' : 'metadata')}
        </span>
      </div>
    `;
  }).join('');
  if (state.filtered.length > 200) {
    list.insertAdjacentHTML('beforeend',
      `<div class="empty-state" style="padding:18px"><p>Showing first 200 of ${state.filtered.length} matches — refine filters to narrow further.</p></div>`);
  }
}

function renderHeaderStats() {
  const el = document.getElementById('headerStats');
  if (!el) return;
  const total = (Array.isArray(state.data.reports) ? state.data.reports.length : 0);
  const withText = Object.keys(state.data.manifest?.texts || {}).length;
  el.innerHTML = `
    <span><b>${total}</b> notifications</span>
    <span><b>${withText}</b> with text</span>
  `;
}

function populateFilters() {
  const reports = Array.isArray(state.data.reports) ? state.data.reports : [];
  // Compute distinct values per filter dimension from the loaded data.
  const categorySet = new Set();
  const ministrySet = new Set();
  const langSet     = new Set();
  const yearSet     = new Set();
  for (const r of reports) {
    if (r.category) categorySet.add(r.category);
    if (r.ministry) ministrySet.add(r.ministry);
    const lk = languageKey(r);
    if (lk && lk !== '?') langSet.add(lk);
    const y = reportYear(r);
    if (y) yearSet.add(y);
  }

  const catSel = document.getElementById('filterCategory');
  if (catSel) {
    catSel.innerHTML = '<option value="">All categories</option>' +
      [...categorySet].sort().map(v =>
        `<option value="${escapeHtml(v)}">${escapeHtml(v === 'extraordinary' ? 'Extraordinary' : v === 'weekly' ? 'Weekly' : v)}</option>`).join('');
  }
  const minSel = document.getElementById('filterMinistry');
  if (minSel) {
    minSel.innerHTML = '<option value="">All ministries</option>' +
      [...ministrySet].sort().map(v => `<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('');
  }
  const langSel = document.getElementById('filterLanguage');
  if (langSel) {
    langSel.innerHTML = '<option value="">All languages</option>' +
      [...langSet].sort().map(v => {
        const info = LANG_INFO[v] || DEFAULT_LANG;
        return `<option value="${escapeHtml(v)}">${escapeHtml(info.label)}</option>`;
      }).join('');
  }
  const yearSel = document.getElementById('filterYear');
  if (yearSel) {
    yearSel.innerHTML = '<option value="">All years</option>' +
      [...yearSet].sort((a, b) => b - a).map(v => `<option value="${v}">${v}</option>`).join('');
  }

  // Re-apply persisted state values so corpus-switch round-trips show the
  // active selection in the dropdown UI (not just in state.filters).
  if (catSel)   catSel.value   = state.filters.category || '';
  if (minSel)   minSel.value   = state.filters.ministry || '';
  if (langSel)  langSel.value  = state.filters.language || '';
  if (yearSel)  yearSel.value  = state.filters.year     || '';
}

// ── Report dialog ───────────────────────────────────────────────────────────

function openReportByKey(key) {
  const all = getAllReports();
  const r = all.find(x => reportKey(x) === key);
  if (!r) return;
  if (_deps.ai.streaming() && state.streamingContext?.reportKey !== key) {
    _deps.ai.stop();
    state.streamingContext = null;
  }
  state.selectedReport = r;
  state.dialogChat = state.cache.chats[key] ? [...state.cache.chats[key]] : [];
  document.getElementById('reportTitle').textContent = r.subject || r.title || '(untitled)';
  renderDetailsTab(r);
  switchReportTab('details');
  document.getElementById('reportModal').classList.add('open');
}

function renderDetailsTab(r) {
  const li = langInfo(r);
  const dateStr = formatDate(r._date || reportDate(r));
  const categoryDisplay = categoryLabel(r);
  document.getElementById('detailsTab').innerHTML = `
    <dl class="meta-grid">
      <dt>Subject</dt><dd>${escapeHtml(r.subject || '—')}</dd>
      <dt>Category</dt><dd><span class="house-pill house-${CATEGORY_PILL[r.category] || 'L'}">${escapeHtml(CATEGORY_SHORT[r.category] || '?')}</span> ${escapeHtml(categoryDisplay)} Gazette</dd>
      <dt>Issue date</dt><dd>${escapeHtml(dateStr)}</dd>
      ${r.ministry ? `<dt>Ministry</dt><dd>${escapeHtml(r.ministry)}</dd>` : ''}
      ${r.department ? `<dt>Department</dt><dd>${escapeHtml(r.department)}</dd>` : ''}
      ${r.office ? `<dt>Office</dt><dd>${escapeHtml(r.office)}</dd>` : ''}
      ${r.gazette_id ? `<dt>Gazette ID</dt><dd><code>${escapeHtml(r.gazette_id)}</code></dd>` : ''}
      ${r.ugid ? `<dt>UGID</dt><dd>${escapeHtml(r.ugid)}</dd>` : ''}
      <dt>Language</dt><dd><span class="cat-badge cat-${li.class}">${escapeHtml(li.label)}</span></dd>
      ${r.pdf_url ? `<dt>PDF</dt><dd><a href="${escapeHtml(r.pdf_url)}" target="_blank" rel="noopener">archive.org →</a></dd>` : ''}
      ${r.gazette_source_url ? `<dt>Original</dt><dd><a href="${escapeHtml(r.gazette_source_url)}" target="_blank" rel="noopener">egazette.gov.in →</a></dd>` : ''}
    </dl>
    <p style="margin-top:14px; font-size:0.82rem; color:var(--muted)">
      ${hasExtractedText(r)
        ? 'Full text (English + Hindi where bilingual) has been OCR\'d by archive.org and bundled into the mirror — see the "Full text" tab or generate an AI summary.'
        : 'Full text not yet bundled. The cron picks records up incrementally — check back, or open the PDF directly on archive.org.'}
    </p>
  `;
}

async function loadTextTab() {
  const r = state.selectedReport;
  const tab = document.getElementById('textTab');
  if (!r) { tab.innerHTML = ''; return; }
  if (!hasExtractedText(r)) {
    tab.innerHTML = `<p>Full text hasn't been extracted yet. Open the PDF link from the Details tab.</p>`;
    return;
  }
  tab.innerHTML = `<p style="color:var(--muted)">Loading…</p>`;
  const text = await fetchReportText(r);
  if (!text) { tab.innerHTML = `<p>Could not load the extracted text.</p>`; return; }
  tab.innerHTML = `<pre>${escapeHtml(text)}</pre>`;
  renderList();
}

function switchReportTab(name) {
  // Multi-corpus guard — every corpus binds a click listener on the
  // shared #reportModal .tab-btn elements at activate time, so clicks
  // fan out to all corpora. Only the active corpus should respond;
  // the others must bail before they mutate the dialog. Without this
  // guard, the last-to-fire wins and wipes the active corpus's
  // rendered tab. See CONV.md "Multi-corpus shared-DOM guard".
  if (_deps.activeCorpus?.() !== 'gazettes') return;
  document.querySelectorAll('#reportModal .tab-btn').forEach(b => b.classList.toggle('active', b.dataset.tab === name));
  document.querySelectorAll('#reportModal .tab-pane').forEach(p => p.classList.remove('active'));
  document.getElementById(name + 'Tab').classList.add('active');
  if (name === 'text')    loadTextTab();
  if (name === 'summary') renderSummaryTab();
  if (name === 'chat')    renderChatTab();
}

function renderSummaryTab() {
  const tab = document.getElementById('summaryTab');
  const r = state.selectedReport;
  if (!r) { tab.innerHTML = ''; return; }
  if (!_deps.ai.isUsable()) {
    tab.innerHTML = _deps.ai.notReadyHTML();
    _deps.ai.bindNotReadyCTA(tab);
    return;
  }
  const key = reportKey(r);
  const cached = state.cache.summaries[key];
  const isStreaming = state.streamingContext?.reportKey === key
                  &&  state.streamingContext?.tab === 'summary';

  if (isStreaming) {
    tab.innerHTML = `
      <div class="summary-actions">
        <span class="label">Generating summary… (streams in below)</span>
        <button class="ghost sm" id="stopSummaryBtn">Stop</button>
      </div>
      <div class="summary-box" id="summaryBox">${escapeHtml(cached || '')}</div>
    `;
    document.getElementById('stopSummaryBtn').addEventListener('click', () => {
      _deps.ai.stop();
      state.streamingContext = null;
    });
    return;
  }

  tab.innerHTML = `
    <div class="summary-actions">
      <span class="label">Generate a plain-English summary using your configured AI:</span>
      <button class="primary" id="generateSummaryBtn">${cached ? 'Regenerate' : 'Generate'}</button>
      <button class="ghost sm" id="copySummaryBtn" ${cached ? '' : 'style="display:none"'}>Copy</button>
    </div>
    <div class="summary-box" id="summaryBox">${cached ? escapeHtml(cached) : 'No summary yet.'}</div>
  `;
  document.getElementById('generateSummaryBtn').addEventListener('click', generateSummary);
  document.getElementById('copySummaryBtn').addEventListener('click', () => {
    navigator.clipboard.writeText(document.getElementById('summaryBox').textContent || '');
    _deps.ui.toast('Copied');
  });
}

function renderChatTab() {
  const tab = document.getElementById('chatTab');
  const r = state.selectedReport;
  if (!r) { tab.innerHTML = ''; return; }
  if (!_deps.ai.isUsable()) {
    tab.innerHTML = _deps.ai.notReadyHTML();
    _deps.ai.bindNotReadyCTA(tab);
    return;
  }
  const key = reportKey(r);
  const isStreaming = state.streamingContext?.reportKey === key
                  &&  state.streamingContext?.tab === 'chat';

  const messages = state.dialogChat.length
    ? state.dialogChat
    : [{ role: 'system', content: 'Ask anything about this gazette notification. Your question + the notification text are sent to the AI you configured (local Gemma or BYOK).' }];

  const threadHTML = messages.map(m => {
    const cls = `chat-msg ${m.role}${m.error ? ' error' : ''}`;
    return `<div class="${cls}">${escapeHtml(m.content)}</div>`;
  }).join('');

  const searchOn = _deps.search.isConfigured();
  tab.innerHTML = `
    <div class="chat-thread" id="chatThread">${threadHTML}</div>
    <div class="chat-input-row">
      <textarea id="chatInput" rows="2" placeholder="Ask a question about this notification..." ${isStreaming ? 'disabled' : ''}></textarea>
      ${searchOn ? `<button class="ghost sm" id="chatSearchSendBtn" title="Search the web AND Send" ${isStreaming ? 'disabled' : ''}>&#127760;</button>` : ''}
      <button class="primary" id="chatSendBtn" ${isStreaming ? 'disabled' : ''}>Send</button>
      <button class="ghost sm" id="chatStopBtn" ${isStreaming ? '' : 'style="display:none"'}>Stop</button>
    </div>
  `;
  document.getElementById('chatSendBtn').addEventListener('click', () => chatSend({}));
  if (searchOn) document.getElementById('chatSearchSendBtn').addEventListener('click', () => chatSend({ withSearch: true }));
  document.getElementById('chatStopBtn').addEventListener('click', () => {
    _deps.ai.stop();
    state.streamingContext = null;
  });
  document.getElementById('chatInput').addEventListener('keydown', e => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); chatSend({}); }
  });
  const t = document.getElementById('chatThread');
  if (t) t.scrollTop = t.scrollHeight;
}

function _truncateForContext(text) {
  const limit = _deps.ai.mode() === 'local' ? 12000 : 60000;
  if (text.length <= limit) return text;
  return text.slice(0, limit) + '\n\n[...truncated for context window...]';
}

async function generateSummary() {
  const r = state.selectedReport;
  if (!r) return;
  const text = await fetchReportText(r);
  if (!text) {
    _deps.ui.toast('Full text not available — extract pending');
    return;
  }
  const key = reportKey(r);
  const prompt = SUMMARY_PROMPT.replace('{TEXT}', _truncateForContext(text));
  const messages = [
    { role: 'system', content: 'You are a careful, accurate summariser of Indian government gazette notifications.' },
    { role: 'user',   content: prompt },
  ];

  // Stream via the shared helper — owns the inflight buffer + commit
  // decision. We just supply the live-DOM hook and persist on the
  // decision the helper returns. See app/ai-streaming.js + CONV.md
  // "Streaming AI persistence pattern".
  const previousCached = state.cache.summaries[key] || '';
  state.streamingContext = { reportKey: key, tab: 'summary' };
  renderSummaryTab();
  try {
    const result = await streamWithPersistence({
      generate: _deps.ai.generate,
      messages,
      onText: (full) => {
        if (state.streamingContext?.reportKey === key) {
          const box = document.getElementById('summaryBox');
          if (box) box.textContent = full;
        }
      },
    });
    if (result.ok) {
      state.cache.summaries[key] = result.text;
      idbPut('summaries', key, result.text).catch(() => {});
      // Opt-in disk mirror (Settings → Save to Disk → AI artifacts).
      // Best-effort: writes to <folder>/gazettes/ai/<ugid>.summary.md.
      // Silent when disabled or folder not connected.
      if (_deps.disk?.saveAi?.() && _deps.disk?.isConnected?.()) {
        _deps.disk.write('gazettes', `ai/${r.ugid}.summary.md`, result.text).catch(() => {});
      }
    } else {
      // Immediate-fail — preserve previous cached, surface the error.
      state.cache.summaries[key] = previousCached;
      _deps.ui.toast('Summary generation failed: ' + result.error.message);
    }
  } finally {
    state.streamingContext = null;
    renderSummaryTab();
    renderList();
  }
}

async function chatSend(opts) {
  opts = opts || {};
  const r = state.selectedReport;
  if (!r) return;
  const input = document.getElementById('chatInput');
  const q = input.value.trim();
  if (!q) return;
  if (_deps.ai.streaming()) { _deps.ui.toast('Already responding…'); return; }
  const text = await fetchReportText(r);
  if (!text) { _deps.ui.toast('Full text not available'); return; }

  // From here on, state.dialogChat is mutated. Wrap in try/finally so
  // EVERY exit path (including early returns from the search-config
  // branch and the search-fail branch) persists the conversation to
  // IDB. Without this, a user's just-typed question was lost on reload
  // when search wasn't configured (Bug 3 from the persistence audit).
  const k = reportKey(r);
  state.dialogChat.push({ role: 'user', content: q });
  try {
    let searchResults = null;
    if (opts.withSearch) {
      if (!_deps.search.isConfigured()) {
        state.dialogChat.push({ role: 'system', content: 'Web search not configured. Open Settings → Web search to add a provider.' });
        input.value = '';
        renderChatTab();
        return;
      }
      state.dialogChat.push({ role: 'system', content: `Searching the web for "${q}"…` });
      renderChatTab();
      try {
        searchResults = await _deps.search.run(q);
        const resultLine = searchResults.length
          ? `Found ${searchResults.length} result${searchResults.length === 1 ? '' : 's'}: ${searchResults.map(x => x.title).slice(0, 3).join(' · ')}${searchResults.length > 3 ? '…' : ''}`
          : 'No web results.';
        state.dialogChat[state.dialogChat.length - 1] = { role: 'system', content: resultLine };
      } catch (e) {
        state.dialogChat[state.dialogChat.length - 1] = { role: 'system', content: 'Search failed: ' + e.message };
        searchResults = null;
      }
    }
    state.dialogChat.push({ role: 'assistant', content: '' });
    state.streamingContext = { reportKey: reportKey(r), tab: 'chat' };
    input.value = '';
    renderChatTab();
    const summary = state.cache.summaries[reportKey(r)];
    const userPrompt = buildAskPrompt({
      summary: summary || null,
      text: _truncateForContext(text),
      searchResults,
      question: q,
    });
    const messages = [
      { role: 'system', content: 'You answer questions about audit reports from the Comptroller and Auditor General of India. Use only the supplied material. If the answer is not present, say so.' },
      { role: 'user',   content: userPrompt },
    ];
    const result = await streamWithPersistence({
      generate: _deps.ai.generate,
      messages,
      onText: (full) => {
        const last = state.dialogChat[state.dialogChat.length - 1];
        last.content = full;   // helper passes cumulative
        const lastEl = document.querySelector('#chatThread .chat-msg.assistant:last-child');
        if (lastEl) {
          lastEl.textContent = full;
          const t = document.getElementById('chatThread');
          if (t) t.scrollTop = t.scrollHeight;
        }
      },
    });
    const last = state.dialogChat[state.dialogChat.length - 1];
    if (result.ok) {
      last.content = result.text;   // success or substantive partial
    } else {
      last.error = true;
      last.content = 'Error: ' + result.error.message;
    }
  } finally {
    state.streamingContext = null;
    renderChatTab();
    state.cache.chats[k] = [...state.dialogChat];
    idbPut('chats', k, state.dialogChat).catch(() => {});
    if (_deps.disk?.saveAi?.() && _deps.disk?.isConnected?.()) {
      _deps.disk.write('gazettes', `ai/${r.ugid}.chat.json`, JSON.stringify(state.dialogChat, null, 2)).catch(() => {});
    }
  }
}

// ── Search bundle (sharded, v1.0c) ─────────────────────────────────────────

// ── Search bundle + index ─────────────────────────────────────────────────
//
// Mechanism lives in app/corpus-search.js; these are thin wrappers that
// supply the corpus-specific IDB key + URL prefix + meta + state-update
// hooks (renderResultsLine and applyFilters-if-active-search).

async function loadSearchBundle() {
  return sharedLoadSearchBundle({
    state,
    corpusId:    'gazettes',
    idbKey:      'gazettes-search-bundle.json',
    urlPath:     CORPUS_PREFIX,
    meta:        state.data.meta,
    deps:        _deps,
    onChange:    renderResultsLine,
    onAfterLoad: () => { if (state.filters.search) applyFilters(); },
  });
}

async function loadSearchIndex() {
  return sharedLoadSearchIndex({
    state,
    corpusId:    'gazettes',
    idbKey:      'gazettes-search-index.json',
    urlPath:     CORPUS_PREFIX,
    meta:        state.data.meta,
    deps:        _deps,
    onChange:    renderResultsLine,
    onAfterLoad: () => { if (state.filters.search) applyFilters(); },
  });
}

// ── Export ──────────────────────────────────────────────────────────────────

function _csvCell(v) {
  if (v == null) return '';
  const s = String(v);
  if (/[",\n\r]/.test(s)) return '"' + s.replace(/"/g, '""') + '"';
  return s;
}

function _downloadBlob(filename, mime, content) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  setTimeout(() => { URL.revokeObjectURL(url); a.remove(); }, 100);
}

function _ts() {
  const d = new Date();
  const pad = n => String(n).padStart(2, '0');
  return `${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}`;
}

function exportMetadataCSV() {
  const rows = state.filtered;
  if (!rows.length) { _deps.ui.toast('No notifications to export'); return; }
  const headers = [
    'ugid', 'category', 'issue_date', 'subject', 'ministry', 'department',
    'gazette_id', 'language', 'pdf_url', 'has_text', 'has_summary',
  ];
  const lines = [headers.join(',')];
  for (const r of rows) {
    lines.push([
      r.ugid, r.category, r.issue_date, r.subject, r.ministry, r.department,
      r.gazette_id, (r.languages || []).join('+'), r.pdf_url,
      hasExtractedText(r) ? 'yes' : 'no',
      hasSummary(r) ? 'yes' : 'no',
    ].map(_csvCell).join(','));
  }
  const csv = lines.join('\n') + '\n';
  _downloadBlob(`sansadsaar-gazettes-metadata-${_ts()}.csv`, 'text/csv', csv);
  _deps.ui.toast(`Exported ${rows.length} notifications`);
}

function exportSummariesMD() {
  const all = getAllReports();
  const out = [];
  out.push(`# SansadSaar — Central Gazette summaries`);
  out.push('');
  out.push(`Exported ${new Date().toLocaleString('en-IN')}. Source: <https://sansadsaar.naklitechie.com>.`);
  out.push('');
  let n = 0;
  for (const r of all) {
    const key = reportKey(r);
    const summary = state.cache.summaries[key];
    if (!summary) continue;
    n++;
    out.push('---');
    out.push('');
    out.push(`## ${r.subject || '(untitled)'}`);
    out.push('');
    const meta = [categoryLabel(r), r.ministry, r.issue_date, r.gazette_id].filter(Boolean).join(' · ');
    if (meta) out.push(`*${meta}*`);
    if (r.pdf_url) out.push(`*PDF: <${r.pdf_url}>*`);
    out.push('');
    out.push(summary);
    out.push('');
  }
  if (!n) { _deps.ui.toast('No gazette summaries cached yet'); return; }
  _downloadBlob(`sansadsaar-gazettes-summaries-${_ts()}.md`, 'text/markdown', out.join('\n'));
  _deps.ui.toast(`Exported ${n} summaries`);
}

// ── IDB hydration ──────────────────────────────────────────────────────────

// IDB hydration — mechanism lives in app/corpus-data.js; we just declare
// the store + key prefix + target object. Only gazettes|-prefixed keys
// are touched so other corpora's entries in the shared stores stay alone.

const _matchGazettesKey = (k) => k.startsWith('gazettes|');

async function loadCachedSummaries() {
  await hydrateFromIDB({ store: 'summaries', target: state.cache.summaries, matches: _matchGazettesKey });
}

async function loadCachedChats() {
  await hydrateFromIDB({ store: 'chats', target: state.cache.chats, matches: _matchGazettesKey });
}

async function loadCachedTexts() {
  const { added } = await hydrateFromIDB({
    store: 'texts', target: state.cache.text, matches: _matchGazettesKey,
  });
  return added;
}

// ── Filter row HTML + handlers ──────────────────────────────────────────────

function renderFilterRow() {
  const container = document.getElementById('filtersContainer');
  if (!container) return;
  container.innerHTML = `
    <input type="search" id="filterSearch" placeholder="Search notifications..." autocomplete="off">
    <select id="filterCategory"><option value="">All categories</option></select>
    <select id="filterMinistry"><option value="">All ministries</option></select>
    <select id="filterLanguage"><option value="">All languages</option></select>
    <select id="filterYear"><option value="">All years</option></select>
    <select id="filterSort">
      <option value="date_desc">Newest first</option>
      <option value="date_asc">Oldest first</option>
      <option value="ugid_desc">UGID (high→low)</option>
      <option value="ugid_asc">UGID (low→high)</option>
    </select>
    <button class="ghost sm" id="resetFiltersBtn" title="Reset filters">&times;</button>
  `;
  // Restore current filter values after re-render.
  document.getElementById('filterSearch').value     = state.filters.search      || '';
  document.getElementById('filterSort').value       = state.filters.sort        || 'date_desc';
}

function attachHandlers() {
  const debouncedSearch = debounce(() => { state.filters.search = document.getElementById('filterSearch').value; applyFilters(); }, 200);
  document.getElementById('filterSearch').addEventListener('input', debouncedSearch);
  document.getElementById('filterCategory').addEventListener('change', e => { state.filters.category = e.target.value; applyFilters(); });
  document.getElementById('filterMinistry').addEventListener('change', e => { state.filters.ministry = e.target.value; applyFilters(); });
  document.getElementById('filterLanguage').addEventListener('change', e => { state.filters.language = e.target.value; applyFilters(); });
  document.getElementById('filterYear').addEventListener('change',     e => { state.filters.year     = e.target.value; applyFilters(); });
  document.getElementById('filterSort').addEventListener('change',     e => { state.filters.sort     = e.target.value; applyFilters(); });
  document.getElementById('resetFiltersBtn').addEventListener('click', () => {
    state.filters = { search: '', category: '', ministry: '', year: '', language: '', sort: 'date_desc' };
    document.getElementById('filterSearch').value   = '';
    document.getElementById('filterCategory').value = '';
    document.getElementById('filterMinistry').value = '';
    document.getElementById('filterLanguage').value = '';
    document.getElementById('filterYear').value     = '';
    document.getElementById('filterSort').value     = 'date_desc';
    applyFilters();
  });

  // Reports list (event delegation)
  document.getElementById('reportsList').addEventListener('click', e => {
    const row = e.target.closest('.report-row');
    if (row) openReportByKey(row.dataset.key);
  });

  // Tab buttons (shared across corpora; guard against double-binding)
  document.querySelectorAll('#reportModal .tab-btn').forEach(b => {
    if (b.dataset._gazettesWired) return;
    b.dataset._gazettesWired = '1';
    b.addEventListener('click', () => switchReportTab(b.dataset.tab));
  });
  const closeBtn = document.getElementById('reportCloseBtn');
  if (closeBtn && !closeBtn.dataset._gazettesWired) {
    closeBtn.dataset._gazettesWired = '1';
    closeBtn.addEventListener('click', () => _deps.ui.closeModal('reportModal'));
  }

  // Toolbar exports
  const exportMeta = document.getElementById('exportMetaBtn');
  const exportSum  = document.getElementById('exportSummariesBtn');
  if (exportMeta) exportMeta.onclick = exportMetadataCSV;
  if (exportSum)  exportSum.onclick  = exportSummariesMD;
}

// ── Activation / lifecycle ──────────────────────────────────────────────────

async function activate(deps, { silent = false } = {}) {
  _deps = deps;

  // Always re-render filter row + handlers so a corpus switch back to
  // gazettes restores the right UI in #filtersContainer. Skip when
  // silent (preload mode — shell prefetches data for cross-corpus
  // search without disturbing the visible DOM that belongs to another
  // corpus).
  if (!silent) {
    renderFilterRow();
    attachHandlers();
  }

  if (!_activated) {
    _activated = true;

    const settings = loadSettings();
    state.deepSearch = !!settings.gazettes_deepSearch;
    state.matchAny   = !!settings.gazettes_matchAny;

    const ok = await fetchData();
    if (!ok) return false;

    if (!silent) {
      populateFilters();
      renderHeaderStats();
      applyFilters();
    }

    loadCachedSummaries().then(() => { if (!silent) renderList(); });
    loadCachedChats();
    loadCachedTexts().then((n) => {
      if (n && !silent) {
        renderList();
        renderResultsLine();
      }
      if (state.deepSearch) {
        loadSearchBundle();
        loadSearchIndex();
      }
    });
  } else if (!silent) {
    populateFilters();
    renderHeaderStats();
    applyFilters();
  }

  return true;
}

function refreshAIDependentTabs() {
  if (!state.selectedReport) return;
  const sumActive  = document.getElementById('summaryTab')?.classList.contains('active');
  const chatActive = document.getElementById('chatTab')?.classList.contains('active');
  if (sumActive)  renderSummaryTab();
  if (chatActive) renderChatTab();
}

// ── Settings section ───────────────────────────────────────────────────────

function renderSettingsSection(container) {
  const meta = state.data.meta;
  const bundle = state.searchBundle;
  const indexStats = meta?.search_index;
  const bundleStats = meta?.search_bundle;

  let estimateLine;
  if (state.bundleLoaded && state.indexLoaded && bundle && state.searchIndex) {
    estimateLine = `Search bundle + body index loaded: ${bundle.total} reports, ${state.searchIndex.vocab_size.toLocaleString()} tokens indexed.`;
  } else if (state.bundleLoaded && bundle) {
    estimateLine = `Bundle loaded (${bundle.total} reports). Body index will load next.`;
  } else if (bundleStats?.size_bytes && indexStats?.size_bytes) {
    const totalMB = ((bundleStats.size_bytes + indexStats.size_bytes) / (1024 * 1024)).toFixed(1);
    estimateLine = `~${totalMB} MB total across all gazette shards (CF gzip serves ~30%, cached locally after).`;
  } else {
    estimateLine = `Sharded download (multiple files), cached locally after first load.`;
  }

  container.innerHTML = `
    <div class="settings-section">
      <h3>Search (Central Gazette)</h3>
      <p>Enable deep search to fetch the gazette bundle (subject + first 5K chars per notification) and body index — both cached locally after first load. Search semantics + match-any toggle work the same as for other corpora.</p>
      <div class="settings-row">
        <label for="gazettesDeepSearch">Deep search</label>
        <div>
          <label style="display:inline-flex; align-items:center; gap:6px; font-size:0.86rem; color:var(--text)">
            <input type="checkbox" id="gazettesDeepSearch" ${state.deepSearch ? 'checked' : ''} style="width:auto"> Enable full-text search across gazette notifications
          </label>
          <p style="font-size:0.78rem; color:var(--muted); margin-top:4px">${escapeHtml(estimateLine)}</p>
        </div>
      </div>
    </div>

    <div class="settings-section">
      <h3>Data (Central Gazette)</h3>
      <p id="gazettesDataInfo">${meta
        ? `${_deps.ui.stalenessIndicatorHTML('gazettes', meta)} · ${escapeHtml(String((meta.totals && meta.totals.central) || 0))} notifications total`
        : `Source: ${escapeHtml(_deps?.config?.dataBaseUrl || '')}gazettes/`}</p>
      <button class="sm" id="gazettesRefreshDataBtn">Refresh from mirror</button>
    </div>
  `;
  _deps.ui.bindStalenessIndicators(container);

  document.getElementById('gazettesRefreshDataBtn').addEventListener('click', async () => {
    _deps.ui.toast('Refreshing Gazettes…');
    await fetchData(true);
    populateFilters();
    renderHeaderStats();
    applyFilters();
    _deps.broadcast('gazettes:data-refreshed');
    renderSettingsSection(container);
    _deps.ui.toast('Gazettes data refreshed');
  });
}

function applySettingsFromUI() {
  const wasDeep = state.deepSearch;
  const cbox = document.getElementById('gazettesDeepSearch');
  if (cbox) state.deepSearch = !!cbox.checked;
  const s = loadSettings();
  s.gazettes_deepSearch = state.deepSearch;
  saveSettings(s);
  if (state.deepSearch && !wasDeep) {
    loadSearchBundle();
    loadSearchIndex();
  }
}

// ── Status (per-corpus pill) ───────────────────────────────────────────────

async function fetchStatus() {
  const meta = state.data.meta;
  const withText = Object.keys(state.data.manifest?.texts || {}).length;
  const items = (Array.isArray(state.data.reports) ? state.data.reports.length : 0);
  if (!meta) return { lastUpdate: null, items, withText, error: null };
  return {
    lastUpdate: meta.generated_at || null,
    items: (meta.totals && meta.totals.central) || items,
    withText,
    error: null,
  };
}

// ── JS API surface ─────────────────────────────────────────────────────────

const api = {
  list({ category, ministry, year, language } = {}) {
    return getAllReports().filter(r => {
      if (category && r.category !== category) return false;
      if (ministry && r.ministry !== ministry) return false;
      if (year != null && String(reportYear(r)) !== String(year)) return false;
      if (language && languageKey(r) !== language) return false;
      return true;
    });
  },
  get(key) {
    return getAllReports().find(r => reportKey(r) === key) || null;
  },
  async search(query, opts = {}) {
    if (opts.deep && (!state.bundleLoaded || !state.indexLoaded)) {
      state.deepSearch = true;
      await Promise.all([loadSearchBundle(), loadSearchIndex()]);
    }
    const parsedQ = parseQuery(query);
    if (!parsedQ.tokens.length && !parsedQ.phrases.length) return getAllReports();
    const bundle = state.searchBundle;
    const tokenIndexSets = parsedQ.tokens.map(t => expandTokenToDocs(state.searchIndex, t));
    const anyMode = !!opts.any;
    return getAllReports().filter(r => {
      const key = reportKey(r);
      const subjectLower  = (r.subject || '').toLowerCase();
      const ministryLower = (r.ministry || '').toLowerCase();
      const bundleEntry = bundle ? bundle.map.get(key) : null;
      const headLower   = bundleEntry ? bundleEntry.head.toLowerCase() : '';
      const cached      = state.cache.text[key];
      const cachedLower = cached ? cached.toLowerCase() : '';
      const tokHit = (t, idxSet) => (idxSet && idxSet.has(key))
        || subjectLower.includes(t)
        || ministryLower.includes(t)
        || (headLower && headLower.includes(t))
        || (cachedLower && cachedLower.includes(t));
      const phHit = p => subjectLower.includes(p)
        || ministryLower.includes(p)
        || (headLower && headLower.includes(p))
        || (cachedLower && cachedLower.includes(p));
      if (anyMode) {
        return parsedQ.tokens.some((t, i) => tokHit(t, tokenIndexSets[i]))
            || parsedQ.phrases.some(phHit);
      }
      return parsedQ.tokens.every((t, i) => tokHit(t, tokenIndexSets[i]))
          && parsedQ.phrases.every(phHit);
    });
  },
  open(key) {
    const r = api.get(key);
    if (!r) return false;
    openReportByKey(reportKey(r));
    return true;
  },
  /**
   * Cross-corpus search adapter — calls api.search and pre-formats hits
   * into the shape the global-search modal expects:
   *   { key, title, subtitle, meta? }
   */
  async searchForGlobal(query, { deep = true, limit = 10 } = {}) {
    const items = await api.search(query, { deep });
    const subs = (r) => {
      const parts = [];
      parts.push(CATEGORY_SHORT[r.category] || '?');
      if (r.ministry) parts.push(r.ministry);
      if (r.issue_date) parts.push(r.issue_date);
      if (r.ugid) parts.push(`UGID ${r.ugid}`);
      return parts.join(' · ');
    };
    return items.slice(0, limit).map(r => ({
      key:      reportKey(r),
      title:    r.subject || '(untitled)',
      subtitle: subs(r),
    }));
  },
  categories: () => Object.keys(CATEGORY_SHORT),
  languages:  () => Object.keys(LANG_INFO),
};

// ── Export the corpus contract ─────────────────────────────────────────────

export const GazettesCorpus = {
  id:          'gazettes',
  label:       'Central Gazette',
  shortLabel:  'Gazettes',
  macroGroup:  'executive',
  primaryUnit: 'notification',

  fetchStatus,
  activate,

  api,
  renderSettingsSection,
  applySettingsFromUI,
  refreshAIDependentTabs,
};
