// app/corpora/cag/index.js
// CAG = Comptroller and Auditor General of India.
// ~2,710 audit reports across Union / State / Local Bodies. Daily-mirrored
// from cag.gov.in via parliamentwatch-data's build_cag.py + cag-backfill.yml.
//
// Second registered corpus under SansadSaar. Structurally mirrors the DRSC
// module (data fetch, list/detail rendering, deep-search bundle+index) with
// CAG-specifics: flat reportKeys (`cag|<id>`), filters by government-type /
// report-type / sector / year, no committee or Lok Sabha groupings.
//
// Independence Principle: this file does not import from drsc/index.js.
// Some helper code is duplicated (parseQuery, highlightMatches, posting
// decoders) — the duplication is intentional per spec v0.4 §"Independence
// Principle". Refactor into a shared util when a third corpus arrives.

import {
  idbGet, idbPut, idbCursor,
  escapeHtml, debounce,
  loadSettings, saveSettings,
} from '../../deps.js';
import { streamWithPersistence } from '../../ai-streaming.js';

const CORPUS_PREFIX = 'cag/';

// ── Constants ───────────────────────────────────────────────────────────────

// Display labels + colour-class mapping. Reuse the existing house-pill /
// cat-badge CSS classes from the DRSC styling so no new CSS is needed at
// v1.0b session 2.
const GOV_TYPE_SHORT = {
  'Union':        'UN',
  'State':        'ST',
  'Local Bodies': 'LB',
};
const GOV_TYPE_PILL = {       // -> house-pill class suffix
  'Union':        'L',        // orange (matches Lok Sabha colour)
  'State':        'R',        // navy   (matches Rajya Sabha colour)
  'Local Bodies': 'L',        // fallback to orange — distinct from state
};

// report_type → short code + class on cat-badge
const REPORT_TYPE_INFO = {
  'Financial Audit':   { short: 'FIN',  class: 'DFG',     label: 'Financial' },
  'Compliance Audit':  { short: 'COMP', class: 'AT',      label: 'Compliance' },
  'Performance Audit': { short: 'PERF', class: 'SUBJ',    label: 'Performance' },
};
const DEFAULT_REPORT_TYPE = { short: 'AUD', class: 'ASSURE', label: 'Audit' };

const SUMMARY_PROMPT = `You are summarising an audit report from the Comptroller and Auditor General of India (CAG). Read the report excerpt below and produce a clear, plain-English briefing for a busy reader. Use this structure:

1. **What the audit covers** (1 sentence)
2. **Key findings / observations** (3-5 bullets)
3. **Recommendations** (3-5 bullets, if present)
4. **Why it matters** (1-2 sentences — fiscal impact, accountability, governance)

Keep it neutral, factual, and accessible to a non-specialist. Do not invent figures or claims that aren't in the text.

REPORT:
{TEXT}`;

function buildAskPrompt({ summary, text, searchResults, question }) {
  const parts = [
    'You are answering questions about a specific audit report from the Comptroller and Auditor General of India (CAG). Use only the supplied material below to answer. If the answer isn\'t in the supplied material, say so clearly.',
  ];
  if (summary) parts.push('', 'SUMMARY (previously generated by AI):', summary);
  parts.push('', 'REPORT:', text);
  if (searchResults && searchResults.length) {
    parts.push('', 'RECENT WEB CONTEXT (use cautiously, prefer the report itself when they conflict):');
    for (const r of searchResults) parts.push(`- ${r.title}\n  ${r.url}\n  ${r.snippet}`);
  }
  parts.push('', '---', '', 'QUESTION: ' + question);
  return parts.join('\n');
}

// ── Module-private state ────────────────────────────────────────────────────

const state = {
  // reports is a FLAT dict keyed by id-as-string (different from DRSC's
  // committee-grouped structure).
  data: { reports: {}, manifest: {}, meta: null },
  filtered: [],
  selectedReport: null,
  filters: { search: '', gov_type: '', sector: '', report_type: '', year: '', sort: 'date_desc' },

  cache: {
    summaries: {},   // reportKey -> string
    text:      {},   // reportKey -> string (in-memory; IDB-backed)
    chats:     {},   // reportKey -> [{role, content, error?}]
  },

  dialogChat: [],

  searchBundle: null,
  bundleLoading: false,
  bundleLoaded:  false,

  searchIndex:  null,
  indexLoading: false,
  indexLoaded:  false,

  deepSearch: false,
  matchAny:   false,

  streamingContext: null,
};

let _deps = null;
let _activated = false;   // gates one-time setup; activate() can re-run cheaply

// ── Helpers ─────────────────────────────────────────────────────────────────

function reportKey(r) {
  return `cag|${r.id}`;
}

function reportDate(r) {
  // CAG dates come as "Thu 02 Apr, 2026", "30/06/2023", or similar variants.
  // Best-effort to a JS Date for sorting.
  const candidates = [r.date_tabled, r.date_sent];
  for (const s of candidates) {
    if (!s) continue;
    // "Thu 02 Apr, 2026" → "Apr 02, 2026"
    const m1 = String(s).match(/(\d{1,2})\s+([A-Za-z]+),?\s+(\d{4})/);
    if (m1) {
      const d = new Date(`${m1[2]} ${m1[1]}, ${m1[3]}`);
      if (!isNaN(d)) return d;
    }
    // ISO or DD/MM/YYYY
    const s2 = String(s).replace(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/, '$3-$2-$1');
    const d2 = new Date(s2);
    if (!isNaN(d2)) return d2;
  }
  // Fallback: midnight Jan 1 of inferred year
  if (r.year) {
    const y = new Date(`Jan 1, ${r.year}`);
    if (!isNaN(y)) return y;
  }
  return null;
}

function formatDate(d) {
  if (!d) return '—';
  return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

function reportTypeInfo(r) {
  return REPORT_TYPE_INFO[r.report_type] || DEFAULT_REPORT_TYPE;
}

// ── Data fetching ───────────────────────────────────────────────────────────

async function fetchData(forceRefresh = false) {
  const splash    = document.getElementById('splash');   // shared with shell
  const splashErr = document.getElementById('splashError');
  const dataUrl   = _deps.config.dataBaseUrl;

  if (!forceRefresh) {
    try {
      const [reportsBlob, manifestBlob, metaBlob] = await Promise.all([
        idbGet('blobs', 'cag-reports.json'),
        idbGet('blobs', 'cag-manifest.json'),
        idbGet('blobs', 'cag-meta.json'),
      ]);
      if (reportsBlob && manifestBlob) {
        state.data.reports  = reportsBlob;
        state.data.manifest = manifestBlob;
        state.data.meta     = metaBlob || null;
      }
    } catch (e) { console.warn('CAG IDB cache miss', e); }
  }

  const haveCache = Object.keys(state.data.reports).length > 0;
  const bucket = Math.floor(Date.now() / 300000);
  const v = forceRefresh ? `?v=${Date.now()}` : `?v=${bucket}`;
  const fetchOpts = { cache: 'no-cache' };

  try {
    const [reports, manifest, meta] = await Promise.all([
      fetch(dataUrl + CORPUS_PREFIX + 'reports.json'  + v, fetchOpts).then(r => r.ok ? r.json() : Promise.reject(`reports.json: ${r.status}`)),
      fetch(dataUrl + CORPUS_PREFIX + 'manifest.json' + v, fetchOpts).then(r => r.ok ? r.json() : { texts: {} }).catch(() => ({ texts: {} })),
      fetch(dataUrl + CORPUS_PREFIX + 'meta.json'     + v, fetchOpts).then(r => r.ok ? r.json() : null).catch(() => null),
    ]);
    state.data.reports  = reports;
    state.data.manifest = manifest;
    state.data.meta     = meta;

    // Cache under cag-prefixed IDB keys so DRSC and CAG don't collide on
    // 'reports.json' / 'manifest.json' / 'meta.json'.
    idbPut('blobs', 'cag-reports.json',  reports).catch(() => {});
    idbPut('blobs', 'cag-manifest.json', manifest).catch(() => {});
    if (meta) idbPut('blobs', 'cag-meta.json', meta).catch(() => {});
  } catch (err) {
    console.error('CAG fetch failed', err);
    if (!haveCache) {
      // Splash error is corpus-agnostic; fall back to a toast so we don't
      // step on DRSC's splash error if it set one already.
      _deps.ui.toast('Could not fetch CAG data — see console for details');
      return false;
    }
    _deps.ui.toast('CAG offline — using cached data');
  }

  // Splash hide is shared with DRSC; first corpus to finish hides it.
  splash?.classList.add('hide');
  return true;
}

async function fetchReportText(report) {
  const key = reportKey(report);
  if (state.cache.text[key]) return state.cache.text[key];

  try {
    const cached = await idbGet('texts', key);
    if (cached) {
      state.cache.text[key] = cached;
      return cached;
    }
  } catch {}

  const entry = state.data.manifest?.texts?.[String(report.id)];
  if (!entry) return null;
  try {
    const res = await fetch(_deps.config.dataBaseUrl + CORPUS_PREFIX + entry.url);
    if (!res.ok) return null;
    const text = await res.text();
    state.cache.text[key] = text;
    idbPut('texts', key, text).catch(() => {});
    return text;
  } catch (e) {
    console.warn('CAG: failed to fetch text', e);
    return null;
  }
}

// ── Filtering / list rendering ──────────────────────────────────────────────

function getAllReports() {
  return Object.values(state.data.reports).map(r => ({
    ...r,
    _date: reportDate(r),
    _typeInfo: reportTypeInfo(r),
  }));
}

function applyFilters() {
  const all = getAllReports();
  const f = state.filters;
  const rawQ = f.search.trim();
  const parsedQ = rawQ ? parseQuery(rawQ) : null;
  const bundle = state.searchBundle;

  const tokenIndexSets = parsedQ
    ? parsedQ.tokens.map(t => _expandTokenToDocs(t))
    : [];

  const filtered = all.filter(r => {
    if (f.gov_type && r.gov_type !== f.gov_type) return false;
    if (f.sector && r.sector !== f.sector) return false;
    if (f.report_type && r.report_type !== f.report_type) return false;
    if (f.year && String(r.year || '') !== f.year) return false;
    if (!parsedQ) return true;

    const key = reportKey(r);
    const titleLower  = (r.title || '').toLowerCase();
    const bundleEntry = bundle ? bundle.map.get(key) : null;
    const headLower   = bundleEntry ? bundleEntry.head.toLowerCase() : '';
    const cached      = state.cache.text[key];
    const cachedLower = cached ? cached.toLowerCase() : '';

    function tokenHits(tok, indexSet) {
      if (indexSet && indexSet.has(key)) return true;
      if (titleLower.includes(tok)) return true;
      if (headLower && headLower.includes(tok)) return true;
      if (cachedLower && cachedLower.includes(tok)) return true;
      return false;
    }
    function phraseHits(phrase) {
      if (titleLower.includes(phrase)) return true;
      if (headLower && headLower.includes(phrase)) return true;
      if (cachedLower && cachedLower.includes(phrase)) return true;
      return false;
    }

    if (state.matchAny) {
      const hit = parsedQ.tokens.some((t, i) => tokenHits(t, tokenIndexSets[i]))
              ||  parsedQ.phrases.some(phraseHits);
      if (!hit) return false;
    } else {
      if (!parsedQ.tokens.every((t, i) => tokenHits(t, tokenIndexSets[i]))) return false;
      if (!parsedQ.phrases.every(phraseHits)) return false;
    }
    return true;
  });

  filtered.sort((a, b) => {
    switch (f.sort) {
      case 'date_asc':  return (a._date || 0) - (b._date || 0);
      case 'id_desc':   return (b.id || 0) - (a.id || 0);
      case 'id_asc':    return (a.id || 0) - (b.id || 0);
      case 'date_desc':
      default:          return (b._date || 0) - (a._date || 0);
    }
  });

  state.filtered = filtered;
  renderList();
  renderResultsLine();
}

function renderResultsLine() {
  const el = document.getElementById('resultsLine');
  if (!el) return;
  const total = getAllReports().length;
  const shown = state.filtered.length;
  const meta = state.data.meta;
  let metaLine = '';
  if (meta?.generated_at) {
    metaLine = `Mirror updated <b>${escapeHtml(meta.generated_at.replace('T', ' ').replace('Z', ' UTC'))}</b>`;
  }

  let indexLine = '';
  const bundle = state.searchBundle;
  const idx = state.searchIndex;
  const mirrorWithText = Object.keys(state.data.manifest?.texts || {}).length;
  const loading = state.bundleLoading || state.indexLoading;
  if (loading) {
    const what = state.bundleLoading && state.indexLoading
      ? 'bundle + index'
      : state.bundleLoading ? 'bundle' : 'index';
    indexLine = `<span class="indexing">Loading search ${what}…</span>`;
  } else if (state.deepSearch && state.bundleLoaded && bundle) {
    const tooltip = idx
      ? `Search hits titles + first ${bundle.head_chars} chars of every report, plus body-token presence across the corpus.`
      : `Search hits titles + first ${bundle.head_chars} chars of every report.`;
    indexLine = `<span title="${escapeHtml(tooltip)}">Full-text search · ${bundle.total} reports</span>`
              + ` · <label class="match-any-toggle"><input type="checkbox" id="matchAnyToggle"${state.matchAny ? ' checked' : ''}>match any</label>`;
  } else if (mirrorWithText === 0) {
    indexLine = '';
  } else {
    indexLine = `<span>Title search only · <b>${mirrorWithText}</b> reports with text · <a href="#" id="enableDeepLink" style="color:var(--accent)">enable deep search</a></span>`;
  }
  el.innerHTML = `Showing <b>${shown}</b> of <b>${total}</b> CAG audit reports. ${metaLine} ${indexLine}`;

  const enableLink = document.getElementById('enableDeepLink');
  if (enableLink) {
    enableLink.addEventListener('click', (e) => {
      e.preventDefault();
      state.deepSearch = true;
      const s = loadSettings();
      s.cag_deepSearch = true;
      saveSettings(s);
      renderResultsLine();
      Promise.all([loadSearchBundle(), loadSearchIndex()]).then(() => {
        renderResultsLine();
        if (state.filters.search) applyFilters();
      });
    });
  }
  const matchAnyToggle = document.getElementById('matchAnyToggle');
  if (matchAnyToggle) {
    matchAnyToggle.addEventListener('change', (e) => {
      state.matchAny = !!e.target.checked;
      const s = loadSettings();
      s.cag_matchAny = state.matchAny;
      saveSettings(s);
      applyFilters();
    });
  }

  const sumBtn = document.getElementById('exportSummariesBtn');
  if (sumBtn) {
    const n = Object.keys(state.cache.summaries || {}).length;
    sumBtn.disabled = n === 0;
    sumBtn.textContent = n ? `⬇ Summaries (MD, ${n})` : '⬇ Summaries (MD)';
  }
}

function hasExtractedText(r) {
  return !!state.data.manifest?.texts?.[String(r.id)];
}
function hasSummary(r) {
  return !!state.cache.summaries[reportKey(r)];
}

function renderList() {
  const list = document.getElementById('reportsList');
  if (!list) return;
  if (!state.filtered.length) {
    list.innerHTML = `<div class="empty-state"><h3>No reports match</h3><p>Try clearing filters.</p></div>`;
    return;
  }
  const slice = state.filtered.slice(0, 200);
  const rawQ = state.filters.search.trim();
  const parsedQ = rawQ ? parseQuery(rawQ) : null;
  list.innerHTML = slice.map(r => {
    const titleHTML = parsedQ ? highlightMatches(r.title || '(untitled)', parsedQ)
                              : escapeHtml(r.title || '(untitled)');
    const govShort  = GOV_TYPE_SHORT[r.gov_type] || '?';
    const govPill   = GOV_TYPE_PILL[r.gov_type]  || 'L';
    const ti        = r._typeInfo;
    const subline   = [r.sector, r.department, r.state].filter(Boolean).join(' · ')
                    + (r.report_no ? ` · #${r.report_no}` : '');
    const yearStr   = r.year ?? '—';
    return `
      <div class="report-row" data-key="${escapeHtml(reportKey(r))}">
        <div>
          <div class="report-title">${titleHTML}</div>
          <div class="report-meta">${escapeHtml(subline) || '—'}</div>
        </div>
        <span class="house-pill house-${govPill}" title="${escapeHtml(r.gov_type || '')}">${escapeHtml(govShort)}</span>
        <span class="cat-badge cat-${ti.class}" title="${escapeHtml(ti.label + ' Audit')}">${escapeHtml(ti.short)}</span>
        <span class="report-meta">${escapeHtml(String(yearStr))}</span>
        <span class="text-status ${hasSummary(r) ? 'summary' : (hasExtractedText(r) ? 'ok' : '')}">
          ${hasSummary(r) ? 'summary' : (hasExtractedText(r) ? 'text' : 'metadata')}
        </span>
      </div>
    `;
  }).join('');
  if (state.filtered.length > 200) {
    list.insertAdjacentHTML('beforeend',
      `<div class="empty-state" style="padding:18px"><p>Showing first 200 of ${state.filtered.length} matches — refine filters to narrow further.</p></div>`);
  }
}

function renderHeaderStats() {
  const el = document.getElementById('headerStats');
  if (!el) return;
  const total = Object.keys(state.data.reports).length;
  const withText = Object.keys(state.data.manifest?.texts || {}).length;
  el.innerHTML = `
    <span><b>${total}</b> audits</span>
    <span><b>${withText}</b> with text</span>
  `;
}

function populateFilters() {
  const reports = Object.values(state.data.reports);
  // Compute distinct values per filter dimension from the loaded data.
  const govSet    = new Set();
  const sectorSet = new Set();
  const typeSet   = new Set();
  const yearSet   = new Set();
  for (const r of reports) {
    if (r.gov_type) govSet.add(r.gov_type);
    if (r.sector) sectorSet.add(r.sector);
    if (r.report_type) typeSet.add(r.report_type);
    if (r.year) yearSet.add(r.year);
  }

  const govSel = document.getElementById('filterGovType');
  if (govSel) {
    govSel.innerHTML = '<option value="">All govt types</option>' +
      [...govSet].sort().map(v => `<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('');
  }
  const sectorSel = document.getElementById('filterSector');
  if (sectorSel) {
    sectorSel.innerHTML = '<option value="">All sectors</option>' +
      [...sectorSet].sort().map(v => `<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('');
  }
  const typeSel = document.getElementById('filterReportType');
  if (typeSel) {
    typeSel.innerHTML = '<option value="">All audit types</option>' +
      [...typeSet].sort().map(v => `<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('');
  }
  const yearSel = document.getElementById('filterYear');
  if (yearSel) {
    yearSel.innerHTML = '<option value="">All years</option>' +
      [...yearSet].sort((a, b) => b - a).map(v => `<option value="${v}">${v}</option>`).join('');
  }

  // Re-apply persisted state values so corpus-switch round-trips show the
  // active selection in the dropdown UI (not just in state.filters).
  if (govSel)    govSel.value    = state.filters.gov_type    || '';
  if (sectorSel) sectorSel.value = state.filters.sector      || '';
  if (typeSel)   typeSel.value   = state.filters.report_type || '';
  if (yearSel)   yearSel.value   = state.filters.year        || '';
}

// ── Report dialog ───────────────────────────────────────────────────────────

function openReportByKey(key) {
  const all = getAllReports();
  const r = all.find(x => reportKey(x) === key);
  if (!r) return;
  if (_deps.ai.streaming() && state.streamingContext?.reportKey !== key) {
    _deps.ai.stop();
    state.streamingContext = null;
  }
  state.selectedReport = r;
  state.dialogChat = state.cache.chats[key] ? [...state.cache.chats[key]] : [];
  document.getElementById('reportTitle').textContent = r.title || '(untitled)';
  renderDetailsTab(r);
  switchReportTab('details');
  document.getElementById('reportModal').classList.add('open');
}

function renderDetailsTab(r) {
  const ti = reportTypeInfo(r);
  const subline = [r.sector, r.department, r.state].filter(Boolean).join(' · ');
  document.getElementById('detailsTab').innerHTML = `
    <dl class="meta-grid">
      <dt>Title</dt><dd>${escapeHtml(r.title || '—')}</dd>
      ${r.report_no ? `<dt>Report no.</dt><dd>${escapeHtml(r.report_no)}</dd>` : ''}
      ${r.report_type ? `<dt>Audit type</dt><dd><span class="cat-badge cat-${ti.class}">${escapeHtml(ti.label)}</span></dd>` : ''}
      ${r.gov_type ? `<dt>Govt type</dt><dd>${escapeHtml(r.gov_type)}</dd>` : ''}
      ${r.department ? `<dt>Department</dt><dd>${escapeHtml(r.department)}</dd>` : ''}
      ${r.sector ? `<dt>Sector</dt><dd>${escapeHtml(r.sector)}</dd>` : ''}
      ${r.state ? `<dt>State</dt><dd>${escapeHtml(r.state)}</dd>` : ''}
      ${r.date_tabled ? `<dt>Date tabled</dt><dd>${escapeHtml(r.date_tabled)}</dd>` : ''}
      ${r.date_sent ? `<dt>Date sent</dt><dd>${escapeHtml(r.date_sent)}</dd>` : ''}
      ${r.year ? `<dt>Year</dt><dd>${r.year}</dd>` : ''}
      ${r.pdf_url ? `<dt>PDF</dt><dd><a href="${escapeHtml(r.pdf_url)}" target="_blank" rel="noopener">${escapeHtml(r.pdf_url.split('/').pop())}</a>${r.file_size_mb ? ` <span class="report-meta">(${r.file_size_mb.toFixed(1)} MB)</span>` : ''}</dd>` : ''}
      ${r.detail_url ? `<dt>Source</dt><dd><a href="${escapeHtml(r.detail_url)}" target="_blank" rel="noopener">cag.gov.in</a></dd>` : '<dt>Source</dt><dd><a href="https://cag.gov.in" target="_blank">cag.gov.in</a></dd>'}
    </dl>
    <p style="margin-top:14px; font-size:0.82rem; color:var(--muted)">
      ${hasExtractedText(r)
        ? 'Full text has been extracted by the mirror — see the "Full text" tab or generate an AI summary.'
        : 'Full text has not yet been extracted by the mirror. The daily Action picks reports up incrementally — check back, or open the PDF directly.'}
    </p>
  `;
}

async function loadTextTab() {
  const r = state.selectedReport;
  const tab = document.getElementById('textTab');
  if (!r) { tab.innerHTML = ''; return; }
  if (!hasExtractedText(r)) {
    tab.innerHTML = `<p>Full text hasn't been extracted yet. Open the PDF link from the Details tab.</p>`;
    return;
  }
  tab.innerHTML = `<p style="color:var(--muted)">Loading…</p>`;
  const text = await fetchReportText(r);
  if (!text) { tab.innerHTML = `<p>Could not load the extracted text.</p>`; return; }
  tab.innerHTML = `<pre>${escapeHtml(text)}</pre>`;
  renderList();
}

function switchReportTab(name) {
  // Multi-corpus guard — every corpus binds a click listener on the
  // shared #reportModal .tab-btn elements at activate time, so clicks
  // fan out to all corpora. Only the active corpus should respond;
  // the others must bail before they mutate the dialog. Without this
  // guard, the last-to-fire wins and wipes the active corpus's
  // rendered tab. See CONV.md "Multi-corpus shared-DOM guard".
  if (_deps.activeCorpus?.() !== 'cag') return;
  document.querySelectorAll('#reportModal .tab-btn').forEach(b => b.classList.toggle('active', b.dataset.tab === name));
  document.querySelectorAll('#reportModal .tab-pane').forEach(p => p.classList.remove('active'));
  document.getElementById(name + 'Tab').classList.add('active');
  if (name === 'text')    loadTextTab();
  if (name === 'summary') renderSummaryTab();
  if (name === 'chat')    renderChatTab();
}

function renderSummaryTab() {
  const tab = document.getElementById('summaryTab');
  const r = state.selectedReport;
  if (!r) { tab.innerHTML = ''; return; }
  if (!_deps.ai.isUsable()) {
    tab.innerHTML = _deps.ai.notReadyHTML();
    _deps.ai.bindNotReadyCTA(tab);
    return;
  }
  const key = reportKey(r);
  const cached = state.cache.summaries[key];
  const isStreaming = state.streamingContext?.reportKey === key
                  &&  state.streamingContext?.tab === 'summary';

  if (isStreaming) {
    tab.innerHTML = `
      <div class="summary-actions">
        <span class="label">Generating summary… (streams in below)</span>
        <button class="ghost sm" id="stopSummaryBtn">Stop</button>
      </div>
      <div class="summary-box" id="summaryBox">${escapeHtml(cached || '')}</div>
    `;
    document.getElementById('stopSummaryBtn').addEventListener('click', () => {
      _deps.ai.stop();
      state.streamingContext = null;
    });
    return;
  }

  tab.innerHTML = `
    <div class="summary-actions">
      <span class="label">Generate a plain-English summary using your configured AI:</span>
      <button class="primary" id="generateSummaryBtn">${cached ? 'Regenerate' : 'Generate'}</button>
      <button class="ghost sm" id="copySummaryBtn" ${cached ? '' : 'style="display:none"'}>Copy</button>
    </div>
    <div class="summary-box" id="summaryBox">${cached ? escapeHtml(cached) : 'No summary yet.'}</div>
  `;
  document.getElementById('generateSummaryBtn').addEventListener('click', generateSummary);
  document.getElementById('copySummaryBtn').addEventListener('click', () => {
    navigator.clipboard.writeText(document.getElementById('summaryBox').textContent || '');
    _deps.ui.toast('Copied');
  });
}

function renderChatTab() {
  const tab = document.getElementById('chatTab');
  const r = state.selectedReport;
  if (!r) { tab.innerHTML = ''; return; }
  if (!_deps.ai.isUsable()) {
    tab.innerHTML = _deps.ai.notReadyHTML();
    _deps.ai.bindNotReadyCTA(tab);
    return;
  }
  const key = reportKey(r);
  const isStreaming = state.streamingContext?.reportKey === key
                  &&  state.streamingContext?.tab === 'chat';

  const messages = state.dialogChat.length
    ? state.dialogChat
    : [{ role: 'system', content: 'Ask anything about this audit report. Your question + the report text are sent to the AI you configured (local Gemma or BYOK).' }];

  const threadHTML = messages.map(m => {
    const cls = `chat-msg ${m.role}${m.error ? ' error' : ''}`;
    return `<div class="${cls}">${escapeHtml(m.content)}</div>`;
  }).join('');

  const searchOn = _deps.search.isConfigured();
  tab.innerHTML = `
    <div class="chat-thread" id="chatThread">${threadHTML}</div>
    <div class="chat-input-row">
      <textarea id="chatInput" rows="2" placeholder="Ask a question about this audit report..." ${isStreaming ? 'disabled' : ''}></textarea>
      ${searchOn ? `<button class="ghost sm" id="chatSearchSendBtn" title="Search the web AND Send" ${isStreaming ? 'disabled' : ''}>&#127760;</button>` : ''}
      <button class="primary" id="chatSendBtn" ${isStreaming ? 'disabled' : ''}>Send</button>
      <button class="ghost sm" id="chatStopBtn" ${isStreaming ? '' : 'style="display:none"'}>Stop</button>
    </div>
  `;
  document.getElementById('chatSendBtn').addEventListener('click', () => chatSend({}));
  if (searchOn) document.getElementById('chatSearchSendBtn').addEventListener('click', () => chatSend({ withSearch: true }));
  document.getElementById('chatStopBtn').addEventListener('click', () => {
    _deps.ai.stop();
    state.streamingContext = null;
  });
  document.getElementById('chatInput').addEventListener('keydown', e => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); chatSend({}); }
  });
  const t = document.getElementById('chatThread');
  if (t) t.scrollTop = t.scrollHeight;
}

function _truncateForContext(text) {
  const limit = _deps.ai.mode() === 'local' ? 12000 : 60000;
  if (text.length <= limit) return text;
  return text.slice(0, limit) + '\n\n[...truncated for context window...]';
}

async function generateSummary() {
  const r = state.selectedReport;
  if (!r) return;
  const text = await fetchReportText(r);
  if (!text) {
    _deps.ui.toast('Full text not available — extract pending');
    return;
  }
  const key = reportKey(r);
  const prompt = SUMMARY_PROMPT.replace('{TEXT}', _truncateForContext(text));
  const messages = [
    { role: 'system', content: 'You are a careful, accurate summariser of public-sector audit reports.' },
    { role: 'user',   content: prompt },
  ];

  // Stream via the shared helper — owns the inflight buffer + commit
  // decision. We just supply the live-DOM hook and persist on the
  // decision the helper returns. See app/ai-streaming.js + CONV.md
  // "Streaming AI persistence pattern".
  const previousCached = state.cache.summaries[key] || '';
  state.streamingContext = { reportKey: key, tab: 'summary' };
  renderSummaryTab();
  try {
    const result = await streamWithPersistence({
      generate: _deps.ai.generate,
      messages,
      onText: (full) => {
        if (state.streamingContext?.reportKey === key) {
          const box = document.getElementById('summaryBox');
          if (box) box.textContent = full;
        }
      },
    });
    if (result.ok) {
      state.cache.summaries[key] = result.text;
      idbPut('summaries', key, result.text).catch(() => {});
    } else {
      // Immediate-fail — preserve previous cached, surface the error.
      state.cache.summaries[key] = previousCached;
      _deps.ui.toast('Summary generation failed: ' + result.error.message);
    }
  } finally {
    state.streamingContext = null;
    renderSummaryTab();
    renderList();
  }
}

async function chatSend(opts) {
  opts = opts || {};
  const r = state.selectedReport;
  if (!r) return;
  const input = document.getElementById('chatInput');
  const q = input.value.trim();
  if (!q) return;
  if (_deps.ai.streaming()) { _deps.ui.toast('Already responding…'); return; }
  const text = await fetchReportText(r);
  if (!text) { _deps.ui.toast('Full text not available'); return; }

  // From here on, state.dialogChat is mutated. Wrap in try/finally so
  // EVERY exit path (including early returns from the search-config
  // branch and the search-fail branch) persists the conversation to
  // IDB. Without this, a user's just-typed question was lost on reload
  // when search wasn't configured (Bug 3 from the persistence audit).
  const k = reportKey(r);
  state.dialogChat.push({ role: 'user', content: q });
  try {
    let searchResults = null;
    if (opts.withSearch) {
      if (!_deps.search.isConfigured()) {
        state.dialogChat.push({ role: 'system', content: 'Web search not configured. Open Settings → Web search to add a provider.' });
        input.value = '';
        renderChatTab();
        return;
      }
      state.dialogChat.push({ role: 'system', content: `Searching the web for "${q}"…` });
      renderChatTab();
      try {
        searchResults = await _deps.search.run(q);
        const resultLine = searchResults.length
          ? `Found ${searchResults.length} result${searchResults.length === 1 ? '' : 's'}: ${searchResults.map(x => x.title).slice(0, 3).join(' · ')}${searchResults.length > 3 ? '…' : ''}`
          : 'No web results.';
        state.dialogChat[state.dialogChat.length - 1] = { role: 'system', content: resultLine };
      } catch (e) {
        state.dialogChat[state.dialogChat.length - 1] = { role: 'system', content: 'Search failed: ' + e.message };
        searchResults = null;
      }
    }
    state.dialogChat.push({ role: 'assistant', content: '' });
    state.streamingContext = { reportKey: reportKey(r), tab: 'chat' };
    input.value = '';
    renderChatTab();
    const summary = state.cache.summaries[reportKey(r)];
    const userPrompt = buildAskPrompt({
      summary: summary || null,
      text: _truncateForContext(text),
      searchResults,
      question: q,
    });
    const messages = [
      { role: 'system', content: 'You answer questions about audit reports from the Comptroller and Auditor General of India. Use only the supplied material. If the answer is not present, say so.' },
      { role: 'user',   content: userPrompt },
    ];
    const result = await streamWithPersistence({
      generate: _deps.ai.generate,
      messages,
      onText: (full) => {
        const last = state.dialogChat[state.dialogChat.length - 1];
        last.content = full;   // helper passes cumulative
        const lastEl = document.querySelector('#chatThread .chat-msg.assistant:last-child');
        if (lastEl) {
          lastEl.textContent = full;
          const t = document.getElementById('chatThread');
          if (t) t.scrollTop = t.scrollHeight;
        }
      },
    });
    const last = state.dialogChat[state.dialogChat.length - 1];
    if (result.ok) {
      last.content = result.text;   // success or substantive partial
    } else {
      last.error = true;
      last.content = 'Error: ' + result.error.message;
    }
  } finally {
    state.streamingContext = null;
    renderChatTab();
    state.cache.chats[k] = [...state.dialogChat];
    idbPut('chats', k, state.dialogChat).catch(() => {});
  }
}

// ── Search bundle (sharded, v1.0c) ─────────────────────────────────────────

function _parseBundle(b) {
  const map = new Map();
  for (const e of (b.entries || [])) map.set(e.key, { title: e.title, head: e.head });
  return {
    generated_at: b.generated_at,
    head_chars:   b.head_chars,
    total:        b.total,
    map,
  };
}

async function loadSearchBundle() {
  if (state.bundleLoading) return state.searchBundle;
  state.bundleLoading = true;
  renderResultsLine();

  try {
    const cached = await idbGet('blobs', 'cag-search-bundle.json');
    if (cached) {
      state.searchBundle = _parseBundle(cached);
      state.bundleLoaded = true;
      renderResultsLine();
    }
  } catch {}

  try {
    const meta = state.data.meta;
    const shardList = meta?.search_bundle?.shards;
    if (!shardList || !shardList.length) {
      console.info('CAG: search_bundle.shards missing from meta; skipping fetch');
      return state.searchBundle;
    }
    const dataUrl = _deps.config.dataBaseUrl;
    const bucket  = Math.floor(Date.now() / 300000);
    const shards = await Promise.all(shardList.map(name =>
      fetch(dataUrl + CORPUS_PREFIX + name + '?v=' + bucket, { cache: 'no-cache' })
        .then(r => r.ok ? r.json() : Promise.reject(`${name}: ${r.status}`))
    ));

    let head_chars   = 5000;
    let generated_at = '';
    const entries    = [];
    for (const s of shards) {
      head_chars = s.head_chars || head_chars;
      if (s.generated_at && s.generated_at > generated_at) generated_at = s.generated_at;
      if (s.entries) entries.push(...s.entries);
    }
    const merged = { generated_at, head_chars, total: entries.length, entries };
    const cachedAt = state.searchBundle?.generated_at;
    if (!cachedAt || (generated_at && generated_at > cachedAt)) {
      state.searchBundle = _parseBundle(merged);
      state.bundleLoaded = true;
      idbPut('blobs', 'cag-search-bundle.json', merged).catch(() => {});
    }
  } catch (e) {
    console.warn('CAG: search-bundle fetch failed', e);
  } finally {
    state.bundleLoading = false;
    renderResultsLine();
    if (state.filters.search) applyFilters();
  }
  return state.searchBundle;
}

// ── Search index (sharded, v1.0c) ──────────────────────────────────────────

function _parseIndex(raw) {
  const shards = raw.shards || [];
  if (!shards.length) return null;
  const vocab = shards[0].vocab || [];
  let report_count = 0;
  let generated_at = '';
  for (const s of shards) {
    report_count += (s.report_keys || []).length;
    if (s.generated_at && s.generated_at > generated_at) generated_at = s.generated_at;
  }
  return {
    generated_at,
    report_count,
    vocab_size:    vocab.length,
    vocab,
    shards,
  };
}

async function loadSearchIndex() {
  if (state.indexLoading) return state.searchIndex;
  state.indexLoading = true;
  renderResultsLine();

  try {
    const cached = await idbGet('blobs', 'cag-search-index.json');
    if (cached && cached.shards) {
      state.searchIndex = _parseIndex(cached);
      state.indexLoaded = true;
      renderResultsLine();
    }
  } catch {}

  try {
    const meta = state.data.meta;
    const shardList = meta?.search_index?.shards;
    if (!shardList || !shardList.length) {
      console.info('CAG: search_index.shards missing from meta; skipping fetch');
      return state.searchIndex;
    }
    const dataUrl = _deps.config.dataBaseUrl;
    const bucket  = Math.floor(Date.now() / 300000);
    const shards = await Promise.all(shardList.map(name =>
      fetch(dataUrl + CORPUS_PREFIX + name + '?v=' + bucket, { cache: 'no-cache' })
        .then(r => r.ok ? r.json() : Promise.reject(`${name}: ${r.status}`))
    ));
    let generated_at = '';
    for (const s of shards) {
      if (s.generated_at && s.generated_at > generated_at) generated_at = s.generated_at;
    }
    const cachedAt = state.searchIndex?.generated_at;
    if (!cachedAt || (generated_at && generated_at > cachedAt)) {
      const blob = { shards };
      state.searchIndex = _parseIndex(blob);
      state.indexLoaded = true;
      idbPut('blobs', 'cag-search-index.json', blob).catch(() => {});
      _decodedPostingsCache.clear();
    }
  } catch (e) {
    console.warn('CAG: search-index fetch failed', e);
  } finally {
    state.indexLoading = false;
    renderResultsLine();
    if (state.filters.search) applyFilters();
  }
  return state.searchIndex;
}

// Per-session decoded posting cache. Key is `${shardIdx}:${vocabIdx}`.
const _decodedPostingsCache = new Map();
function _decodePostings(shardIdx, vi) {
  const cacheKey = shardIdx + ':' + vi;
  if (_decodedPostingsCache.has(cacheKey)) return _decodedPostingsCache.get(cacheKey);
  const idx = state.searchIndex;
  if (!idx || !idx.shards[shardIdx]) return [];
  const delta = idx.shards[shardIdx].postings[vi];
  if (!delta || !delta.length) return [];
  const out = new Array(delta.length);
  let acc = delta[0] | 0;
  out[0] = acc;
  for (let i = 1; i < delta.length; i++) {
    acc += delta[i] | 0;
    out[i] = acc;
  }
  _decodedPostingsCache.set(cacheKey, out);
  return out;
}

function _expandPrefix(prefix) {
  const idx = state.searchIndex;
  if (!idx || !idx.vocab.length || !prefix) return [];
  const vocab = idx.vocab;
  let lo = 0, hi = vocab.length;
  while (lo < hi) {
    const mid = (lo + hi) >>> 1;
    if (vocab[mid] < prefix) lo = mid + 1; else hi = mid;
  }
  const out = [];
  for (let i = lo; i < vocab.length && vocab[i].startsWith(prefix); i++) out.push(i);
  return out;
}

function _expandTokenToDocs(tokenStr) {
  const idx = state.searchIndex;
  if (!idx || !idx.shards || !idx.shards.length) return null;
  const vis = _expandPrefix(tokenStr);
  if (!vis.length) return new Set();
  const out = new Set();
  for (let si = 0; si < idx.shards.length; si++) {
    const shard = idx.shards[si];
    const shardKeys = shard.report_keys || [];
    for (const vi of vis) {
      for (const localIdx of _decodePostings(si, vi)) {
        out.add(shardKeys[localIdx]);
      }
    }
  }
  return out;
}

// ── Query parser + highlight (duplicated from DRSC for Independence) ────────

function parseQuery(raw) {
  const tokens = [];
  const phrases = [];
  let rem = String(raw || '');
  rem = rem.replace(/"([^"]+)"/g, (_, p) => {
    const cleaned = p.trim().toLowerCase();
    if (cleaned) phrases.push(cleaned);
    return ' ';
  });
  for (const word of rem.split(/\s+/)) {
    const w = word.toLowerCase().replace(/^[\W_]+|[\W_]+$/g, '');
    if (w) tokens.push(w);
  }
  return { tokens, phrases };
}

function _escapeRegex(s) {
  return String(s).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function highlightMatches(text, parsedQ) {
  const safeText = String(text ?? '');
  if (!parsedQ) return escapeHtml(safeText);
  const tokens = parsedQ.tokens.filter(Boolean);
  const phrases = parsedQ.phrases.filter(Boolean);
  if (!tokens.length && !phrases.length) return escapeHtml(safeText);
  const phrasePats = [...phrases].sort((a, b) => b.length - a.length).map(_escapeRegex);
  const tokenPats  = tokens.map(t => `\\b${_escapeRegex(t)}\\w*`);
  let pattern;
  try {
    pattern = new RegExp('(' + [...phrasePats, ...tokenPats].join('|') + ')', 'gi');
  } catch {
    return escapeHtml(safeText);
  }
  const parts = safeText.split(pattern);
  return parts.map((part, i) => (i % 2 === 1)
    ? `<mark>${escapeHtml(part)}</mark>`
    : escapeHtml(part)
  ).join('');
}

// ── Export ──────────────────────────────────────────────────────────────────

function _csvCell(v) {
  if (v == null) return '';
  const s = String(v);
  if (/[",\n\r]/.test(s)) return '"' + s.replace(/"/g, '""') + '"';
  return s;
}

function _downloadBlob(filename, mime, content) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  setTimeout(() => { URL.revokeObjectURL(url); a.remove(); }, 100);
}

function _ts() {
  const d = new Date();
  const pad = n => String(n).padStart(2, '0');
  return `${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}`;
}

function exportMetadataCSV() {
  const rows = state.filtered;
  if (!rows.length) { _deps.ui.toast('No reports to export'); return; }
  const headers = [
    'id', 'title', 'gov_type', 'report_type', 'report_no', 'department', 'sector', 'state',
    'date_tabled', 'year', 'pdf_url', 'file_size_mb', 'has_text', 'has_summary',
  ];
  const lines = [headers.join(',')];
  for (const r of rows) {
    lines.push([
      r.id, r.title, r.gov_type, r.report_type, r.report_no, r.department, r.sector, r.state,
      r.date_tabled, r.year, r.pdf_url, r.file_size_mb,
      hasExtractedText(r) ? 'yes' : 'no',
      hasSummary(r) ? 'yes' : 'no',
    ].map(_csvCell).join(','));
  }
  const csv = lines.join('\n') + '\n';
  _downloadBlob(`sansadsaar-cag-metadata-${_ts()}.csv`, 'text/csv', csv);
  _deps.ui.toast(`Exported ${rows.length} audit reports`);
}

function exportSummariesMD() {
  const all = getAllReports();
  const out = [];
  out.push(`# SansadSaar — CAG audit summaries`);
  out.push('');
  out.push(`Exported ${new Date().toLocaleString('en-IN')}. Source: <https://sansadsaar.naklitechie.com>.`);
  out.push('');
  let n = 0;
  for (const r of all) {
    const key = reportKey(r);
    const summary = state.cache.summaries[key];
    if (!summary) continue;
    n++;
    out.push('---');
    out.push('');
    out.push(`## ${r.title || '(untitled)'}`);
    out.push('');
    const meta = [r.gov_type, r.report_type, r.year, r.report_no && `#${r.report_no}`].filter(Boolean).join(' · ');
    if (meta) out.push(`*${meta}*`);
    if (r.pdf_url) out.push(`*PDF: <${r.pdf_url}>*`);
    out.push('');
    out.push(summary);
    out.push('');
  }
  if (!n) { _deps.ui.toast('No CAG summaries cached yet'); return; }
  _downloadBlob(`sansadsaar-cag-summaries-${_ts()}.md`, 'text/markdown', out.join('\n'));
  _deps.ui.toast(`Exported ${n} summaries`);
}

// ── IDB hydration ──────────────────────────────────────────────────────────

async function loadCachedSummaries() {
  try {
    await idbCursor('summaries', 'readonly', (key, value) => {
      // Only pick up cag-prefixed keys; leave DRSC's alone.
      if (typeof key === 'string' && key.startsWith('cag|')) {
        state.cache.summaries[key] = value;
      }
    });
    renderList();
  } catch {}
}

async function loadCachedChats() {
  try {
    await idbCursor('chats', 'readonly', (key, value) => {
      if (typeof key === 'string' && key.startsWith('cag|')) {
        state.cache.chats[key] = value;
      }
    });
  } catch {}
}

async function loadCachedTexts() {
  let hydrated = 0;
  try {
    await idbCursor('texts', 'readonly', (key, value) => {
      if (typeof key === 'string' && key.startsWith('cag|')) {
        state.cache.text[key] = value;
        hydrated++;
      }
    });
  } catch {}
  return hydrated;
}

// ── Filter row HTML + handlers ──────────────────────────────────────────────

function renderFilterRow() {
  const container = document.getElementById('filtersContainer');
  if (!container) return;
  container.innerHTML = `
    <input type="search" id="filterSearch" placeholder="Search audit reports..." autocomplete="off">
    <select id="filterGovType"><option value="">All govt types</option></select>
    <select id="filterReportType"><option value="">All audit types</option></select>
    <select id="filterSector"><option value="">All sectors</option></select>
    <select id="filterYear"><option value="">All years</option></select>
    <select id="filterSort">
      <option value="date_desc">Newest first</option>
      <option value="date_asc">Oldest first</option>
      <option value="id_desc">Report ID (high→low)</option>
      <option value="id_asc">Report ID (low→high)</option>
    </select>
    <button class="ghost sm" id="resetFiltersBtn" title="Reset filters">&times;</button>
  `;
  // Restore current filter values after re-render.
  document.getElementById('filterSearch').value     = state.filters.search      || '';
  document.getElementById('filterSort').value       = state.filters.sort        || 'date_desc';
}

function attachHandlers() {
  const debouncedSearch = debounce(() => { state.filters.search = document.getElementById('filterSearch').value; applyFilters(); }, 200);
  document.getElementById('filterSearch').addEventListener('input', debouncedSearch);
  document.getElementById('filterGovType').addEventListener('change',    e => { state.filters.gov_type    = e.target.value; applyFilters(); });
  document.getElementById('filterReportType').addEventListener('change', e => { state.filters.report_type = e.target.value; applyFilters(); });
  document.getElementById('filterSector').addEventListener('change',     e => { state.filters.sector      = e.target.value; applyFilters(); });
  document.getElementById('filterYear').addEventListener('change',       e => { state.filters.year        = e.target.value; applyFilters(); });
  document.getElementById('filterSort').addEventListener('change',       e => { state.filters.sort        = e.target.value; applyFilters(); });
  document.getElementById('resetFiltersBtn').addEventListener('click', () => {
    state.filters = { search: '', gov_type: '', sector: '', report_type: '', year: '', sort: 'date_desc' };
    document.getElementById('filterSearch').value     = '';
    document.getElementById('filterGovType').value    = '';
    document.getElementById('filterReportType').value = '';
    document.getElementById('filterSector').value     = '';
    document.getElementById('filterYear').value       = '';
    document.getElementById('filterSort').value       = 'date_desc';
    applyFilters();
  });

  // Reports list (event delegation)
  document.getElementById('reportsList').addEventListener('click', e => {
    const row = e.target.closest('.report-row');
    if (row) openReportByKey(row.dataset.key);
  });

  // Tab buttons (shared across corpora; guard against double-binding)
  document.querySelectorAll('#reportModal .tab-btn').forEach(b => {
    if (b.dataset._cagWired) return;
    b.dataset._cagWired = '1';
    b.addEventListener('click', () => switchReportTab(b.dataset.tab));
  });
  const closeBtn = document.getElementById('reportCloseBtn');
  if (closeBtn && !closeBtn.dataset._cagWired) {
    closeBtn.dataset._cagWired = '1';
    closeBtn.addEventListener('click', () => _deps.ui.closeModal('reportModal'));
  }

  // Toolbar exports
  const exportMeta = document.getElementById('exportMetaBtn');
  const exportSum  = document.getElementById('exportSummariesBtn');
  if (exportMeta) exportMeta.onclick = exportMetadataCSV;
  if (exportSum)  exportSum.onclick  = exportSummariesMD;
}

// ── Activation / lifecycle ──────────────────────────────────────────────────

async function activate(deps) {
  _deps = deps;

  // Always re-render filter row + handlers so a corpus switch back to CAG
  // restores the right UI in #filtersContainer.
  renderFilterRow();
  attachHandlers();

  if (!_activated) {
    _activated = true;

    const settings = loadSettings();
    state.deepSearch = !!settings.cag_deepSearch;
    state.matchAny   = !!settings.cag_matchAny;

    const ok = await fetchData();
    if (!ok) return false;

    populateFilters();
    renderHeaderStats();
    applyFilters();

    loadCachedSummaries();
    loadCachedChats();
    loadCachedTexts().then((n) => {
      if (n) {
        renderList();
        renderResultsLine();
      }
      if (state.deepSearch) {
        loadSearchBundle();
        loadSearchIndex();
      }
    });
  } else {
    populateFilters();
    renderHeaderStats();
    applyFilters();
  }

  return true;
}

function refreshAIDependentTabs() {
  if (!state.selectedReport) return;
  const sumActive  = document.getElementById('summaryTab')?.classList.contains('active');
  const chatActive = document.getElementById('chatTab')?.classList.contains('active');
  if (sumActive)  renderSummaryTab();
  if (chatActive) renderChatTab();
}

// ── Settings section ───────────────────────────────────────────────────────

function renderSettingsSection(container) {
  const meta = state.data.meta;
  const bundle = state.searchBundle;
  const indexStats = meta?.search_index;
  const bundleStats = meta?.search_bundle;

  let estimateLine;
  if (state.bundleLoaded && state.indexLoaded && bundle && state.searchIndex) {
    estimateLine = `Search bundle + body index loaded: ${bundle.total} reports, ${state.searchIndex.vocab_size.toLocaleString()} tokens indexed.`;
  } else if (state.bundleLoaded && bundle) {
    estimateLine = `Bundle loaded (${bundle.total} reports). Body index will load next.`;
  } else if (bundleStats?.size_bytes && indexStats?.size_bytes) {
    const totalMB = ((bundleStats.size_bytes + indexStats.size_bytes) / (1024 * 1024)).toFixed(1);
    estimateLine = `~${totalMB} MB total across all CAG shards (CF gzip serves ~30%, cached locally after).`;
  } else {
    estimateLine = `Sharded download (multiple files), cached locally after first load.`;
  }

  container.innerHTML = `
    <div class="settings-section">
      <h3>Search (CAG audits)</h3>
      <p>Enable deep search to fetch the CAG bundle (title + first 5K chars per report) and body index — both cached locally after first load. Search semantics + match-any toggle work the same as for Standing Committees.</p>
      <div class="settings-row">
        <label for="cagDeepSearch">Deep search</label>
        <div>
          <label style="display:inline-flex; align-items:center; gap:6px; font-size:0.86rem; color:var(--text)">
            <input type="checkbox" id="cagDeepSearch" ${state.deepSearch ? 'checked' : ''} style="width:auto"> Enable full-text search across CAG audit reports
          </label>
          <p style="font-size:0.78rem; color:var(--muted); margin-top:4px">${escapeHtml(estimateLine)}</p>
        </div>
      </div>
    </div>

    <div class="settings-section">
      <h3>Data (CAG audits)</h3>
      <p id="cagDataInfo">${meta
        ? `Last updated ${escapeHtml(meta.generated_at)} · ${escapeHtml(String(meta.total_reports))} reports total · ${escapeHtml(String(meta.total_with_text))} with text`
        : `Source: ${escapeHtml(_deps.config.dataBaseUrl)}cag/`}</p>
      <button class="sm" id="cagRefreshDataBtn">Refresh from mirror</button>
    </div>
  `;

  document.getElementById('cagRefreshDataBtn').addEventListener('click', async () => {
    _deps.ui.toast('Refreshing CAG…');
    await fetchData(true);
    populateFilters();
    renderHeaderStats();
    applyFilters();
    _deps.broadcast('cag:data-refreshed');
    renderSettingsSection(container);
    _deps.ui.toast('CAG data refreshed');
  });
}

function applySettingsFromUI() {
  const wasDeep = state.deepSearch;
  const cbox = document.getElementById('cagDeepSearch');
  if (cbox) state.deepSearch = !!cbox.checked;
  const s = loadSettings();
  s.cag_deepSearch = state.deepSearch;
  saveSettings(s);
  if (state.deepSearch && !wasDeep) {
    loadSearchBundle();
    loadSearchIndex();
  }
}

// ── Status (per-corpus pill) ───────────────────────────────────────────────

async function fetchStatus() {
  const meta = state.data.meta;
  const withText = Object.keys(state.data.manifest?.texts || {}).length;
  if (!meta) return { lastUpdate: null, items: getAllReports().length, withText, error: null };
  return {
    lastUpdate: meta.generated_at || null,
    items: meta.total_reports || getAllReports().length,
    withText,
    error: null,
  };
}

// ── JS API surface ─────────────────────────────────────────────────────────

const api = {
  list({ gov_type, report_type, sector, year } = {}) {
    return getAllReports().filter(r => {
      if (gov_type && r.gov_type !== gov_type) return false;
      if (report_type && r.report_type !== report_type) return false;
      if (sector && r.sector !== sector) return false;
      if (year != null && String(r.year) !== String(year)) return false;
      return true;
    });
  },
  get(key) {
    return getAllReports().find(r => reportKey(r) === key) || null;
  },
  async search(query, opts = {}) {
    if (opts.deep && (!state.bundleLoaded || !state.indexLoaded)) {
      state.deepSearch = true;
      await Promise.all([loadSearchBundle(), loadSearchIndex()]);
    }
    const parsedQ = parseQuery(query);
    if (!parsedQ.tokens.length && !parsedQ.phrases.length) return getAllReports();
    const bundle = state.searchBundle;
    const tokenIndexSets = parsedQ.tokens.map(t => _expandTokenToDocs(t));
    const anyMode = !!opts.any;
    return getAllReports().filter(r => {
      const key = reportKey(r);
      const titleLower  = (r.title || '').toLowerCase();
      const bundleEntry = bundle ? bundle.map.get(key) : null;
      const headLower   = bundleEntry ? bundleEntry.head.toLowerCase() : '';
      const cached      = state.cache.text[key];
      const cachedLower = cached ? cached.toLowerCase() : '';
      const tokHit = (t, idxSet) => (idxSet && idxSet.has(key))
        || titleLower.includes(t)
        || (headLower && headLower.includes(t))
        || (cachedLower && cachedLower.includes(t));
      const phHit = p => titleLower.includes(p)
        || (headLower && headLower.includes(p))
        || (cachedLower && cachedLower.includes(p));
      if (anyMode) {
        return parsedQ.tokens.some((t, i) => tokHit(t, tokenIndexSets[i]))
            || parsedQ.phrases.some(phHit);
      }
      return parsedQ.tokens.every((t, i) => tokHit(t, tokenIndexSets[i]))
          && parsedQ.phrases.every(phHit);
    });
  },
  open(key) {
    const r = api.get(key);
    if (!r) return false;
    openReportByKey(reportKey(r));
    return true;
  },
  govTypes:    () => Object.keys(GOV_TYPE_SHORT),
  reportTypes: () => Object.keys(REPORT_TYPE_INFO),
};

// ── Export the corpus contract ─────────────────────────────────────────────

export const CAGCorpus = {
  id:          'cag',
  label:       'Audit Reports (CAG)',
  shortLabel:  'CAG',
  macroGroup:  'oversight',
  primaryUnit: 'audit',

  fetchStatus,
  activate,

  api,
  renderSettingsSection,
  applySettingsFromUI,
  refreshAIDependentTabs,
};
